function summary = summarizeDOMPHistory(history)
% summarizeDOMPHistory - Convert DOMP iteration history to one table row.
% The summary is compact enough for result artifacts while retaining stop,
% conditioning, orthogonality, residual, and elapsed-time diagnostics.

required = {'selectedIndex','residualNorm','normalizedCorrelation', ...
    'conditionNumberSelected','elapsedTime','maxOrthogonalityError', ...
    'stopReason','selectedCount','requestedComponents', ...
    'initialResidualNorm','finalResidualNorm'};
if ~isstruct(history) || ~isscalar(history) || ...
        ~all(isfield(history, required))
    error('summarizeDOMPHistory:InvalidHistory', ...
        'history does not satisfy the DOMP history contract.');
end

SelectedComponents = history.selectedCount;
RequestedComponents = history.requestedComponents;
StopReason = string(history.stopReason);
InitialResidualNorm = history.initialResidualNorm;
FinalResidualNorm = history.finalResidualNorm;
MaximumNormalizedCorrelation = max(history.normalizedCorrelation, [], ...
    'omitmissing');
MaximumConditionNumber = max(history.conditionNumberSelected, [], ...
    'omitmissing');
MaximumOrthogonalityError = max(history.maxOrthogonalityError, [], ...
    'omitmissing');
ElapsedTimeSeconds = history.elapsedTime(end);

summary = table(SelectedComponents, RequestedComponents, StopReason, ...
    InitialResidualNorm, FinalResidualNorm, ...
    MaximumNormalizedCorrelation, MaximumConditionNumber, ...
    MaximumOrthogonalityError, ElapsedTimeSeconds);
end
