% Script: run_fair_PNNN_vs_PNGMP_DOMP
% Run the shared 10% identification/full-signal comparison from end to end.
% Linear models run first; PNNN reuses their active-parameter target.

clearvars;
clc;

project_root = fileparts(mfilename('fullpath'));
if isempty(project_root)
    project_root = pwd;
end
addpath(fullfile(project_root, 'config'));
addpath(fullfile(project_root, 'toolbox', 'metrics'));
addpath(fullfile(project_root, 'toolbox', 'complexity'));
addpath(fullfile(project_root, 'toolbox', 'domp'));
addpath(fullfile(project_root, 'toolbox', 'splits'));
addpath(fullfile(project_root, 'toolbox', 'pn_gmp_comparison'));
addpath(fullfile(project_root, 'toolbox', 'pnnn'));
addpath(fullfile(project_root, 'toolbox', 'pnnn', 'pruning'));

cfg = getFairDOMPComparisonConfig(project_root);
if cfg.warmStart.enabled || cfg.warmStart.useLatestDeploy
    error('run_fair_PNNN_vs_PNGMP_DOMP:WarmStartForbidden', ...
        'The fair comparison must initialize final networks from scratch.');
end

[data, split, result_directory] = prepareComparison(cfg);
diary(fullfile(result_directory, 'run_log.txt'));
diary_cleanup = onCleanup(@() diary('off'));

fprintf('\n=== Full-signal PNNN versus PN-GMP DOMP comparison ===\n');
fprintf('Result directory: %s\n', result_directory);
fprintf('Mapping: %s (local modeled-block X/Y convention)\n', cfg.mappingMode);
fprintf(['Internal train=%d | internal validation=%d | ' ...
    'identification=%d | full signal=%d\n'], ...
    numel(split.internalTrainIndices), ...
    numel(split.internalValidationIndices), ...
    numel(split.identificationIndices), numel(split.fullSignalIndices));
fprintf('Identification is contained in full signal: YES\n');

fprintf('\nFitting six linear DOMP models under the corrected protocol...\n');
linear_study = runPNGMPDOMPStudy(data.x, data.y, split, cfg);
independent_row = linear_study.comparisonResults.Model == ...
    "Independent PN-IQ full";
matched_row = linear_study.comparisonResults.Model == ...
    "Complex GMP DOMP parameter-matched";
if nnz(independent_row) ~= 1 || nnz(matched_row) ~= 1
    error('run_fair_PNNN_vs_PNGMP_DOMP:MissingParameterMatch', ...
        'Both parameter-matched model rows must appear exactly once.');
end
target_active_params = ...
    linear_study.comparisonResults.NumRealParameters(independent_row);
if linear_study.comparisonResults.NumRealParameters(matched_row) ~= ...
        target_active_params
    error('run_fair_PNNN_vs_PNGMP_DOMP:ParameterMismatch', ...
        'Independent PN-IQ and parameter-matched GMP must have equal size.');
end

pnnn_study = runPNNNComparisonStudy( ...
    data.x, data.y, split, cfg, target_active_params);
study = combineStudies(linear_study, pnnn_study, split, ...
    target_active_params);
saveStudy(data, split, study, cfg, result_directory);
printSummary(study, split, result_directory);
diary off;

function [data, split, resultDirectory] = prepareComparison(cfg)
measurement = load(cfg.measurementFile, 'x', 'y');
if ~all(isfield(measurement, {'x', 'y'}))
    error('run_fair_PNNN_vs_PNGMP_DOMP:InvalidMeasurement', ...
        'The configured measurement must contain x and y.');
end
[x, y] = selectXYByMapping(measurement.x, measurement.y, cfg.mappingMode);
x = x(:);
y = y(:);
if isempty(x) || numel(x) ~= numel(y) || ...
        any(~isfinite(x)) || any(~isfinite(y))
    error('run_fair_PNNN_vs_PNGMP_DOMP:InvalidSignals', ...
        'Modeled-block X and Y must be aligned finite vectors.');
end
if cfg.pnnn.removeDC
    x = x - mean(x);
    y = y - mean(y);
end

split = buildCommonComparisonSplit(x, y, cfg);
partition = sort([split.internalTrainIndices; ...
    split.internalValidationIndices]);
if ~isequal(partition, sort(split.identificationIndices)) || ...
        ~isempty(intersect(split.internalTrainIndices, ...
        split.internalValidationIndices)) || ...
        ~all(ismember(split.identificationIndices, split.fullSignalIndices))
    error('run_fair_PNNN_vs_PNGMP_DOMP:InvalidSplit', ...
        'The train/validation rows must partition identification.');
end

resultDirectory = fullfile(cfg.resultsRoot, ...
    char(datetime('now', 'Format', 'yyyyMMdd_HHmmss')));
mkdir(resultDirectory);
data = struct('x', x, 'y', y);
end

function study = combineStudies(linear, pnnn, split, targetParameters)
results = linear.comparisonResults;
n = height(results);
results.NNSeed = NaN(n, 1);
results.BestDenseEpoch = NaN(n, 1);
results.BestFineTuneEpoch = NaN(n, 1);
results.NNHiddenNeurons = NaN(n, 1);
results.TrainingTimeSeconds = NaN(n, 1);
results.TargetActiveParams = results.ParameterMatchedTarget;
results.ActualActiveParams = results.NumRealParameters;
results.ActiveWeights = results.NumRealParameters;
results.ActiveBiases = zeros(n, 1);
results.WeightSparsityPercent = zeros(n, 1);
results.FinalFitSamples = repmat(numel(split.identificationIndices), n, 1);
results.FullSignalSamples = repmat(numel(split.fullSignalIndices), n, 1);
results.NormalizationSamples = NaN(n, 1);
pnnnResults = pnnn.comparisonResults(:, results.Properties.VariableNames);
results = [results; pnnnResults];

flops = linear.complexityFLOPs;
flops.DenseExecutionCoreFLOPsPerSample = flops.CoreFLOPsPerSample;
flops.IdealSparseCoreFLOPsPerSample = flops.CoreFLOPsPerSample;
flops.DenseMatrixFLOPsPerSample = flops.FLOPsPerSample;
flops.SparseZeroWeightsSkipped = false(height(flops), 1);
flops.IdealSparseRealMultiplicationsPerSample = ...
    flops.RealMultiplicationsPerSample;
flops.IdealSparseRealAdditionsPerSample = flops.RealAdditionsPerSample;
flops.IdealSparseCostRequiresSparseKernel = false(height(flops), 1);
pnnnFlops = pnnn.complexityFLOPs(:, flops.Properties.VariableNames);
flops = [flops; pnnnFlops];

parameterColumns = {'Model','NumRealParameters','ParameterMatchedTarget', ...
    'ParameterDifference','ActualActiveParams','ActiveWeights', ...
    'ActiveBiases','WeightSparsityPercent','FinalFitSamples'};
hyperparameterColumns = {'Model','SelectedLambda','DOMPSupportSize', ...
    'InternalValidationNMSEdB','BestDenseEpoch', ...
    'BestFineTuneEpoch','SelectionMethod'};
mainModels = ["Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; "PNNN N12 sparse"];

study = struct( ...
    'comparisonResults', results, ...
    'complexityFLOPs', flops, ...
    'parameterSummary', results(:, parameterColumns), ...
    'selectedHyperparameters', results(:, hyperparameterColumns), ...
    'mainResults', results(ismember(results.Model, mainModels), :), ...
    'targetActiveParameters', targetParameters, ...
    'linear', linear, 'pnnn', pnnn);
end

function saveStudy(data, split, study, cfg, resultDirectory)
tables = {study.comparisonResults, 'comparison_results.csv'; ...
    study.parameterSummary, 'parameter_summary.csv'; ...
    study.selectedHyperparameters, 'selected_hyperparameters.csv'; ...
    study.complexityFLOPs, 'complexity_flops.csv'; ...
    study.linear.flopConvention, 'flop_convention.csv'; ...
    study.linear.dompHistorySummary, 'domp_history_summary.csv'; ...
    study.linear.regressorStructureSummary, ...
        'regressor_structure_summary.csv'};
for index = 1:size(tables, 1)
    writetable(tables{index, 1}, fullfile(resultDirectory, tables{index, 2}));
end

identification_indices = split.identificationIndices;
full_signal_indices = split.fullSignalIndices;
internal_train_indices = split.internalTrainIndices;
internal_validation_indices = split.internalValidationIndices;
save(fullfile(resultDirectory, 'split_indices.mat'), ...
    'identification_indices','full_signal_indices', ...
    'internal_train_indices','internal_validation_indices','split');

supports = study.linear.supports;
domp_histories = study.linear.dompHistories;
save(fullfile(resultDirectory, 'domp_supports.mat'), ...
    'supports','domp_histories');

identification_predictions = study.linear.identificationPredictions;
full_signal_predictions = study.linear.fullSignalPredictions;
fitNames = {'h4DenseFit','n12DenseFit','n12SparseFit'};
predictionNames = {'pnnnH4Dense','pnnnN12Dense','pnnnN12Sparse'};
for index = 1:numel(fitNames)
    fit = study.pnnn.(fitNames{index});
    identification_predictions.(predictionNames{index}) = ...
        fit.identificationPrediction;
    full_signal_predictions.(predictionNames{index}) = fit.fullSignalPrediction;
end
target_identification = data.y(identification_indices);
target_full_signal = data.y(full_signal_indices);
prediction_metadata = struct( ...
    'identificationSamples', numel(identification_indices), ...
    'fullSignalSamples', numel(full_signal_indices), ...
    'identificationIncludedInFullSignal', true, ...
    'fullSignalIsIndependentHoldout', false);
save(fullfile(resultDirectory, 'full_signal_predictions.mat'), ...
    'target_identification','target_full_signal', ...
    'identification_indices','full_signal_indices', ...
    'identification_predictions','full_signal_predictions', ...
    'prediction_metadata','-v7.3');

comparison_results = study.comparisonResults;
comparison_metadata = comparisonMetadata(study, split, cfg);
save(fullfile(resultDirectory, 'comparison_results.mat'), ...
    'comparison_results','comparison_metadata');
runtime_cfg = study.pnnn.runtimeConfig;
save(fullfile(resultDirectory, 'comparison_config.mat'), 'runtime_cfg','cfg');

createPlots(comparison_results, resultDirectory);
sparseCost = study.complexityFLOPs( ...
    study.complexityFLOPs.Model == "PNNN N12 sparse", :);
reportFile = fullfile(resultDirectory, 'fair_comparison_report.tex');
writeReport(reportFile, ...
    study.mainResults, split, cfg, study.linear.equivalenceRelativeError, ...
    sparseCost.DenseMatrixFLOPsPerSample);
if cfg.report.compilePDF
    [outputDirectory, ~] = fileparts(reportFile);
    command = sprintf(['pdflatex -interaction=nonstopmode -halt-on-error ' ...
        '-output-directory="%s" "%s"'], outputDirectory, reportFile);
    [status, output] = system(command);
    if status ~= 0
        error('run_fair_PNNN_vs_PNGMP_DOMP:LaTeXFailed', ...
            'pdflatex failed:%s%s', newline, output);
    end
end
end

function metadata = comparisonMetadata(study, split, cfg)
fitNames = {'h4DenseFit','n12DenseFit','n12SparseFit'};
metadata = struct( ...
    'measurementName', cfg.measurementName, ...
    'mappingMode', cfg.mappingMode, ...
    'sharedDCRemoval', cfg.pnnn.removeDC, ...
    'inputDimension', study.pnnn.inputDimension, ...
    'identificationSamples', numel(split.identificationIndices), ...
    'fullSignalSamples', numel(split.fullSignalIndices), ...
    'identificationIncludedInFullSignal', true, ...
    'fullSignalIsIndependentHoldout', false, ...
    'targetActiveParams', study.targetActiveParameters, ...
    'pnnnSelection', study.pnnn.selection, ...
    'trainingBudget', study.pnnn.budget, ...
    'linearStudySeconds', study.linear.totalTimeSeconds, ...
    'equivalenceRelativeError', study.linear.equivalenceRelativeError);
largeFields = {'network','normalization','identificationPrediction', ...
    'fullSignalPrediction','pruningState','finalTrainingInfo', ...
    'finalFineTuneInfo'};
outputNames = {'h4Dense','n12Dense','n12Sparse'};
for index = 1:numel(fitNames)
    fit = study.pnnn.(fitNames{index});
    metadata.(outputNames{index}) = rmfield(fit, ...
        intersect(largeFields, fieldnames(fit), 'stable'));
end
end

function createPlots(results, resultDirectory)
labels = string(results.Model);
plots = { ...
    results.NumRealParameters, 'Active real parameters', ...
        'Full-signal NMSE versus active real parameters', ...
        labels, 65*ones(height(results), 1), ...
        'comparison_nmse_parameters.png'; ...
    results.FLOPsPerSample, 'FLOPs/sample', ...
        'Full-signal NMSE versus inference FLOPs/sample', ...
        labels + " (p=" + string(results.NumRealParameters) + ")", ...
        45 + 100*sqrt(results.NumRealParameters ./ ...
        max(results.NumRealParameters)), 'comparison_flops.png'};
for index = 1:size(plots, 1)
    figureHandle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [100 100 1150 680]);
    scatter(plots{index, 1}, results.FullSignalNMSEdB, ...
        plots{index, 5}, 'filled');
    grid on;
    xlabel(plots{index, 2});
    ylabel('Full-signal NMSE (dB)');
    title(plots{index, 3});
    text(plots{index, 1}, results.FullSignalNMSEdB, ...
        "  " + plots{index, 4}, 'Interpreter', 'none', 'FontSize', 8);
    exportgraphics(figureHandle, fullfile(resultDirectory, ...
        plots{index, 6}), 'Resolution', 160);
    close(figureHandle);
end
end

function printSummary(study, split, resultDirectory)
disp(' ');
disp('=== Corrected full-signal main comparison ===');
disp(study.mainResults(:, {'Model','NumRealParameters', ...
    'IdentificationNMSEdB','FullSignalNMSEdB','FLOPsPerSample', ...
    'AdditionalOperationsPerSample'}));
disp(' ');
disp('=== All corrected-protocol models ===');
disp(study.comparisonResults(:, {'Model','NumRealParameters', ...
    'IdentificationNMSEdB','FullSignalNMSEdB','FLOPsPerSample'}));
fprintf('Complex/coupled full-signal relative error: %.6e\n', ...
    study.linear.equivalenceRelativeError);
fprintf('All final model fits used %d identification rows.\n', ...
    numel(split.identificationIndices));
fprintf(['Full-signal evaluation used %d rows and includes the ' ...
    'identification rows.\n'], numel(split.fullSignalIndices));
fprintf('Results: %s\n', resultDirectory);
end

function writeReport(filename, mainResults, split, cfg, ...
    equivalenceError, sparseDenseMatrixFLOPs)
fileId = fopen(filename, 'w');
if fileId < 0
    error('run_fair_PNNN_vs_PNGMP_DOMP:ReportOpenFailed', ...
        'Could not create the LaTeX report.');
end
cleanup = onCleanup(@() fclose(fileId));
identificationPercent = 100*split.identificationFraction;
activation = lower(string(cfg.pnnn.actType));

fprintf(fileId, '\\documentclass[10pt]{article}\n');
fprintf(fileId, '\\usepackage[margin=1.35cm]{geometry}\n');
fprintf(fileId, '\\usepackage{booktabs,amsmath,array,tabularx}\n');
fprintf(fileId, '\\setlength{\\emergencystretch}{2em}\n');
fprintf(fileId, ['\\title{Full-Signal PNNN versus PN-GMP DOMP ' ...
    'Comparison}\n\\author{}\\date{}\\begin{document}\\maketitle\n']);
fprintf(fileId, ['\\paragraph{Objective and methodology.} Complex GMP, ' ...
    'its exactly equivalent coupled PN-IQ representation, independent ' ...
    'PN-IQ controls, and parameter-matched PNNNs use the same modeled-block ' ...
    'X/Y samples. DOMP is used only during linear identification.\n']);
fprintf(fileId, ['\\paragraph{Fair comparison protocol.} The classic ' ...
    'selector provides %d identification rows (configured %.3g\\%% of ' ...
    'the capture). An internal %d/%d split selects regularization and ' ...
    'neural epochs. Every final model is fitted on all identification ' ...
    'rows and evaluated on all %d signal rows. \\textbf{The full-signal ' ...
    'evaluation includes the identification samples and therefore must ' ...
    'not be interpreted as an independent generalization test.}\n'], ...
    numel(split.identificationIndices), identificationPercent, ...
    numel(split.internalTrainIndices), ...
    numel(split.internalValidationIndices), ...
    numel(split.fullSignalIndices));
fprintf(fileId, ['\\paragraph{Main results.} NMSE uses ' ...
    '$10\\log_{10}(\\sum|y-\\hat y|^2/\\sum|y|^2)$.\n']);
fprintf(fileId, ...
    '\\begin{center}\\small\\begin{tabularx}{\\linewidth}{XrrrX}\n');
fprintf(fileId, '\\toprule\n');
fprintf(fileId, ['Model & Real parameters & Full-signal NMSE (dB) & ' ...
    'FLOPs/sample & Additional operations/sample \\\\ \\midrule\n']);
for index = 1:height(mainResults)
    fprintf(fileId, '%s & %d & %.3f & %d & %s \\\\ \n', ...
        latexEscape(mainResults.Model(index)), ...
        mainResults.NumRealParameters(index), ...
        mainResults.FullSignalNMSEdB(index), ...
        mainResults.FLOPsPerSample(index), ...
        latexEscape(mainResults.AdditionalOperationsPerSample(index)));
end
fprintf(fileId, '\\bottomrule\\end{tabularx}\\end{center}\n');
fprintf(fileId, ['\\paragraph{Computational cost.} FLOPs/sample counts ' ...
    'real additions and multiplications required for one complex output, ' ...
    'including feature generation, coefficients or weights, biases, phase ' ...
    'normalization, and phase restoration. Magnitudes, roots, divisions, ' ...
    'exponentials, and activation evaluations remain separate. DOMP is not ' ...
    'an inference cost. The sparse-PNNN FLOP count assumes that zero weights ' ...
    'are skipped. An implementation that executes the original full matrices ' ...
    'will require %d FLOPs/sample instead.\n'], sparseDenseMatrixFLOPs);
fprintf(fileId, ['\\paragraph{Interpretation and limitations.} Independent ' ...
    'PN-IQ provides the strongest NMSE in the main comparison; all three ' ...
    'main models use exactly the same number of active real parameters; and ' ...
    'the sparse PNNN uses the fewest counted FLOPs when zero weights are ' ...
    'actually skipped, while adding %s evaluations. Complex GMP DOMP-100 ' ...
    'and coupled PN-IQ remain numerically equivalent with relative error ' ...
    '$%.3e$. These analytical counts do not establish latency, energy, ' ...
    'or FPGA resource superiority.\n'], activation, equivalenceError);
fprintf(fileId, '\\end{document}\n');
end

function value = latexEscape(value)
value = char(string(value));
value = strrep(value, '\', '\textbackslash{}');
value = strrep(value, '_', '\_');
value = strrep(value, '%', '\%');
value = strrep(value, '&', '\&');
end
