function results = run_selected_comparison(selectedParameters, sweep)
% run_selected_comparison - Present one signed parameter-sweep point.
% The three main predictions come from checkpoints; six fixed-ridge
% predictions are refitted on the same stored supports before plotting.

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
for folder = ["metrics","pn_gmp_comparison","pnnn","splits","sweep"]
    addpath(fullfile(projectRoot, 'toolbox', folder));
end
cfg = getFairDOMPComparisonConfig(projectRoot);
addpath(cfg.paper.matlab2tikzSource);

if nargin < 2 || isempty(sweep)
    sweep = run_parameter_sweep(20:10:500);
end

%% Select the three comparable rows and load their signed checkpoints
identity = sweep.sweepIdentity;
signature = identity.experimentSignature;
fixedLambdas = identity.fixedRidgeLambdas(:);
if ~ismember(selectedParameters, identity.parameterGrid)
    error('run_selected_comparison:UnsignedTarget', ...
        'The requested target is not part of the signed grid.');
end
modelNames = ["Complex GMP DOMP sweep"; ...
    "Independent PN-IQ PN-DOMP sweep"; "Sparse PNNN N12"];
selectedRows = sweep.results([],:);
for model = modelNames.'
    row = string(sweep.results.Model) == model & ...
        sweep.results.TargetRealParameters == selectedParameters;
    if nnz(row) ~= 1
        error('run_selected_comparison:MissingSweepPoint', ...
            'Target %d must occur once in each model family.', ...
            selectedParameters);
    end
    selectedRows = [selectedRows; sweep.results(row,:)]; %#ok<AGROW>
end
if any(selectedRows.ActualRealParameters ~= selectedParameters)
    error('run_selected_comparison:ParameterMismatch', ...
        'Every selected model must have the requested real-parameter count.');
end

directory = char(string(sweep.resultDirectory));
stored = load(fullfile(directory, 'complexity_sweep.mat'), ...
    'checkpointArtifact');
artifact = stored.checkpointArtifact;
if ~isequaln(artifact.sweepIdentity, identity)
    error('run_selected_comparison:ExperimentMismatch', ...
        'The sweep summary belongs to another experiment.');
end
summaryPayload = artifact.payload;

stored = load(fullfile(directory, 'linear_sweep.mat'), ...
    'checkpointArtifact');
artifact = stored.checkpointArtifact;
if ~isequaln(artifact.sweepIdentity, identity)
    error('run_selected_comparison:ExperimentMismatch', ...
        'The linear checkpoint belongs to another experiment.');
end
linear = artifact.payload;

stored = load(fullfile(directory, 'sweep_dense_source.mat'), ...
    'checkpointArtifact');
artifact = stored.checkpointArtifact;
if ~isequaln(artifact.sweepIdentity, identity)
    error('run_selected_comparison:ExperimentMismatch', ...
        'The dense PNNN checkpoint belongs to another experiment.');
end
denseSource = artifact.payload;

stored = load(fullfile(directory, ...
    sprintf('pnnn_target_%04d.mat', selectedParameters)), ...
    'checkpointArtifact');
artifact = stored.checkpointArtifact;
if ~isequaln(artifact.sweepIdentity, identity)
    error('run_selected_comparison:ExperimentMismatch', ...
        'The sparse PNNN checkpoint belongs to another experiment.');
end
pnnn = artifact.payload;

if ~isequaln(summaryPayload.results, sweep.results) || ...
        ~isequaln(summaryPayload.evaluationProtocol, ...
        sweep.evaluationProtocol)
    error('run_selected_comparison:SummaryMismatch', ...
        'The in-memory sweep differs from its signed summary.');
end
if ~isfield(summaryPayload, 'selection')
    error('run_selected_comparison:MissingSelection', ...
        'The schema-v3 sweep summary must contain automatic selection data.');
end
automaticSelection = summaryPayload.selection;

complexIndex = find(linear.complexTable.TargetRealParameters == ...
        selectedParameters);
pnIndex = find(linear.pnTable.TargetRealParameters == selectedParameters);
if numel(complexIndex) ~= 1 || numel(pnIndex) ~= 1 || ...
        pnnn.row.TargetRealParameters ~= selectedParameters || ...
        pnnn.denseSourceDigest ~= denseSource.digest
    error('run_selected_comparison:ArtifactMismatch', ...
        'The selected linear or PNNN checkpoint is incompatible.');
end
if ~isequaln(linear.complexTable(complexIndex, :), selectedRows(1, :)) || ...
        ~isequaln(linear.pnTable(pnIndex, :), selectedRows(2, :)) || ...
        ~isequaln(pnnn.row, selectedRows(3, :))
    error('run_selected_comparison:ArtifactRowMismatch', ...
        'Artifact rows must equal the corresponding signed summary rows.');
end
complexPrediction = linear.predictions.complexFull(:, complexIndex);
pnPrediction = linear.predictions.pnFull(:, pnIndex);
pnnnPrediction = pnnn.fullSignalPrediction(:);

%% Recover the signed measurement and aligned full-signal target
measurement = load(cfg.measurementFile);
[x, y] = selectXYByMapping(measurement.x, measurement.y, cfg.mappingMode);
x = x(:);
y = y(:);
if ~isequaln(buildExperimentSignature(x, y, cfg), signature)
    error('run_selected_comparison:SignatureMismatch', ...
        'The configured measurement differs from the signed sweep.');
end
if cfg.pnnn.removeDC
    x = x - mean(x);
    y = y - mean(y);
end
split = buildCommonComparisonSplit(x, y, cfg);
fullSignalIndices = double(split.fullSignalIndices(:));
modelInput = x(fullSignalIndices);
targetFullSignal = y(fullSignalIndices);
sampleRateHz = resolveMeasurementSampleRate(measurement);

%% Refit the six fixed-ridge references on the selected supports
stored = load(fullfile(directory, ...
    'fixed_lambda_linear_sweep.mat'), 'checkpointArtifact');
artifact = stored.checkpointArtifact;
if ~isequaln(artifact.sweepIdentity, identity)
    error('run_selected_comparison:ExperimentMismatch', ...
        'The fixed-ridge checkpoint belongs to another experiment.');
end
fixedSweep = artifact.payload;
selectedLinear = struct( ...
    'complexTable', linear.complexTable(complexIndex, :), ...
    'pnTable', linear.pnTable(pnIndex, :), ...
    'paths', linear.paths, ...
    'pnPathMap', linear.pnPathMap);
selectedConfig = cfg;
selectedConfig.sweep.parameterGrid = selectedParameters;
evaluated = run_fixed_ridge_sweep( ...
    x, y, split, selectedConfig, selectedLinear, true);
fixedTable = orderFixedRows( ...
    fixedSweep, selectedParameters, fixedLambdas);
evaluatedRows = orderFixedRows( ...
    evaluated.table, selectedParameters, fixedLambdas);
if any(evaluatedRows.ActualRealParameters ~= ...
        fixedTable.ActualRealParameters) || ...
        any(evaluatedRows.FLOPsPerSample ~= fixedTable.FLOPsPerSample) || ...
        any(abs(evaluatedRows.IdentificationNMSEdB - ...
        fixedTable.IdentificationNMSEdB) > 1e-9) || ...
        any(abs(evaluatedRows.FullSignalNMSEdB - ...
        fixedTable.FullSignalNMSEdB) > 1e-9) || ...
        any(abs(evaluatedRows.MaxAbsRealParameter - ...
        fixedTable.MaxAbsRealParameter) > 1e-12)
    error('run_selected_comparison:FixedRidgeMismatch', ...
        'Selected ridge refits differ from the saved sweep.');
end
expectedFixedParameters = repelem( ...
    selectedRows.ActualRealParameters(1:2), numel(fixedLambdas));
expectedFixedFLOPs = repelem( ...
    selectedRows.FLOPsPerSample(1:2), numel(fixedLambdas));
if any(fixedTable.ActualRealParameters ~= expectedFixedParameters) || ...
        any(fixedTable.FLOPsPerSample ~= expectedFixedFLOPs)
    error('run_selected_comparison:FixedRidgeComplexityMismatch', ...
        'Fixed Ridge must retain the selected supports, parameters, and FLOPs.');
end
fixedPredictionMatrix = [evaluated.predictions.complexFull, ...
    evaluated.predictions.pnFull];

%% Build the public three-row comparison
comparisonTable = selectedRows;
comparisonTable.Model = ["Complex GMP-DOMP"; "PN-IQ PN-DOMP"; ...
    "Sparse PNNN N12"];
supportCount = selectedParameters/2;
pnFeatures = linear.paths.pn(1:supportCount);
completeComparisonTable = buildCompleteComparisonTable( ...
    comparisonTable, fixedTable);
results = struct('selectedParameters', selectedParameters, ...
    'automaticSelectedParameters', automaticSelection.selectedParameters, ...
    'operatingPointSelection', automaticSelection, ...
    'criterionName', automaticSelection.criterionName, ...
    'stabilizationWindowParameters', ...
        automaticSelection.stabilizationWindowParameters, ...
    'stabilizationToleranceDb', ...
        automaticSelection.stabilizationToleranceDb, ...
    'comparisonTable', comparisonTable, ...
    'fixedLambdaComparisonTable', fixedTable, ...
    'completeComparisonTable', completeComparisonTable, ...
    'linearSupports', struct( ...
        'complex', linear.paths.complex(1:supportCount), ...
        'pnFeatures', pnFeatures, ...
        'pnComplex', unique(linear.pnPathMap.SourceRegressorIndex( ...
            1:supportCount), 'stable')), ...
    'sampleRateHz', sampleRateHz, ...
    'evaluationProtocol', sweep.evaluationProtocol);

%% Compute one shared Welch spectrum and export four paper figures
mainPredictions = [complexPrediction, pnPrediction, pnnnPrediction];
spectrum = computeSelectedPointSpectra(targetFullSignal, mainPredictions, ...
    sampleRateHz, fixedPredictionMatrix);
selectedDirectory = fullfile(directory, ...
    sprintf('selected_point_%04d', selectedParameters));
if ~isfolder(selectedDirectory)
    mkdir(selectedDirectory);
end
completeTableFile = fullfile(selectedDirectory, ...
    'selected_complete_comparison.csv');
writetable(completeComparisonTable, completeTableFile);
results.completeComparisonTableFile = string(completeTableFile);
exportOptions = struct('latexmkCommand', cfg.paper.latexmkCommand);
[timeDomainFigureFiles, timeDomainWindow] = ...
    exportSelectedTimeDomainFigures(targetFullSignal, complexPrediction, ...
    pnPrediction, selectedDirectory, exportOptions);
results.timeDomainFigureFiles = timeDomainFigureFiles;
results.timeDomainRealFigure = timeDomainFigureFiles.real.png;
results.timeDomainImaginaryFigure = timeDomainFigureFiles.imaginary.png;
results.timeDomainWindow = timeDomainWindow;
ampmFigureFiles = exportSelectedAMPMFigure(modelInput, targetFullSignal, ...
    complexPrediction, pnPrediction, selectedDirectory, exportOptions);
results.ampmFigureFiles = ampmFigureFiles;
results.ampmFigure = ampmFigureFiles.png;
phaseErrorFigureFiles = exportSelectedPhaseErrorFigure(modelInput, ...
    targetFullSignal, complexPrediction, pnPrediction, selectedDirectory, ...
    exportOptions);
results.phaseErrorFigureFiles = phaseErrorFigureFiles;
results.phaseErrorFigure = phaseErrorFigureFiles.png;
figureFiles = exportSelectedSpectrumFigures(spectrum, selectedDirectory, ...
    fixedLambdas, exportOptions);
results.spectrumFigureFiles = figureFiles;
results.outputSpectrumFigure = figureFiles.output.png;
results.errorSpectrumFigure = figureFiles.error.png;
results.ridgeOutputSpectrumFigure = figureFiles.ridgeOutput.png;
results.ridgeErrorSpectrumFigure = figureFiles.ridgeError.png;
results.spectrumConfig = spectrum.config;
fprintf('\n=== Complete tutor comparison (principal and fixed Ridge) ===\n');
disp(completeComparisonTable);
fprintf('Complete tutor table: %s\n', completeTableFile);
fprintf('Reused linear, fixed-ridge, dense N12, and sparse point checkpoints: YES\n');
fprintf('Selected-point figures: %s\n', selectedDirectory);
end

function files = exportSelectedAMPMFigure(modelInput, target, ...
    complexPrediction, pnPrediction, directory, exportOptions)
% Export the measured and modeled full-signal AM/PM point clouds.

normalizedInputAmplitude = abs(modelInput) / max(abs(modelInput));
targetAMPM = 180/pi * fase_pmpi(angle(target) - angle(modelInput));
complexAMPM = 180/pi * fase_pmpi( ...
    angle(complexPrediction) - angle(modelInput));
pnAMPM = 180/pi * fase_pmpi(angle(pnPrediction) - angle(modelInput));
plotIndices = selectDeterministicPlotIndices(numel(modelInput), 5000);

style = getIEEEPaperStyle();
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Units', 'inches', 'Position', [1 1 7.0 4.2]);
cleanup = onCleanup(@() close(figureHandle));
axesHandle = axes(figureHandle);
plot(axesHandle, normalizedInputAmplitude(plotIndices), ...
    targetAMPM(plotIndices), '.', 'Color', 'k', 'MarkerSize', 4);
hold(axesHandle, 'on');
plot(axesHandle, normalizedInputAmplitude(plotIndices), ...
    complexAMPM(plotIndices), '.', 'Color', [0 0.45 0.74], ...
    'MarkerSize', 4);
plot(axesHandle, normalizedInputAmplitude(plotIndices), ...
    pnAMPM(plotIndices), '.', 'Color', [0.85 0.33 0.10], ...
    'MarkerSize', 4);
ylabel(axesHandle, 'Phase Shift (deg)');
xlabel(axesHandle, 'Normalized Input Amplitude');
title(axesHandle, 'Measured and Modeled AM/PM Characteristics', ...
    'Interpreter', 'none', 'FontWeight', 'normal');
legend(axesHandle, 'Measured target', 'Complex GMP', 'PN-IQ-GMP', ...
    'Location', 'northeast', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 1);
grid(axesHandle, 'on');
box(axesHandle, 'on');
set(axesHandle, 'FontName', style.fontName, ...
    'FontSize', style.fontSize, 'LineWidth', style.axisLineWidth);
exportOptions.figureHeight = '4.2in';
files = exportPaperFigure(figureHandle, ...
    fullfile(directory, 'selected_ampm'), exportOptions);
clear cleanup;
end

function files = exportSelectedPhaseErrorFigure(modelInput, target, ...
    complexPrediction, pnPrediction, directory, exportOptions)
% Export direct target-minus-prediction phase errors versus input amplitude.

normalizedInputAmplitude = abs(modelInput) / max(abs(modelInput));
complexPhaseError = 180/pi * fase_pmpi( ...
    angle(target) - angle(complexPrediction));
pnPhaseError = 180/pi * fase_pmpi(angle(target) - angle(pnPrediction));
plotIndices = selectDeterministicPlotIndices(numel(modelInput), 5000);

style = getIEEEPaperStyle();
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Units', 'inches', 'Position', [1 1 7.0 4.2]);
cleanup = onCleanup(@() close(figureHandle));
axesHandle = axes(figureHandle);
plot(axesHandle, normalizedInputAmplitude(plotIndices), ...
    complexPhaseError(plotIndices), '.', ...
    'Color', [0 0.45 0.74], 'MarkerSize', 4);
hold(axesHandle, 'on');
plot(axesHandle, normalizedInputAmplitude(plotIndices), ...
    pnPhaseError(plotIndices), '.', ...
    'Color', [0.85 0.33 0.10], 'MarkerSize', 4);
ylabel(axesHandle, 'Phase error, target - prediction (deg)')
xlabel(axesHandle, 'Normalized Input Amplitude');
title(axesHandle, 'Model Phase Error Characteristics', ...
    'Interpreter', 'none', 'FontWeight', 'normal');
legend(axesHandle, 'Complex GMP', 'PN-IQ-GMP', ...
    'Location', 'northeast', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 1);
grid(axesHandle, 'on');
box(axesHandle, 'on');
set(axesHandle, 'FontName', style.fontName, ...
    'FontSize', style.fontSize, 'LineWidth', style.axisLineWidth);
exportOptions.figureHeight = '4.2in';
files = exportPaperFigure(figureHandle, ...
    fullfile(directory, 'selected_phase_error'), exportOptions);
clear cleanup;
end

function indices = selectDeterministicPlotIndices(sampleCount, maximumPoints)
% Keep TikZ exports bounded without changing any computed result.

plotCount = min(sampleCount, maximumPoints);
indices = unique(round(linspace(1, sampleCount, plotCount))).';
end

function phase = fase_pmpi(phase)
phase = mod(phase + pi, 2*pi) - pi;
end

function complete = buildCompleteComparisonTable(mainRows, fixedRows)
% Combine the three principal rows and six fixed-Ridge references.

familyOrder = ["Complex GMP-DOMP", "PN-IQ PN-DOMP", "Sparse PNNN N12"];
complete = table();
for family = familyOrder
    if family == "Complex GMP-DOMP"
        mainIndex = 1;
    elseif family == "PN-IQ PN-DOMP"
        mainIndex = 2;
    else
        mainIndex = 3;
    end
    principal = mainRows(mainIndex, :);
    variant = "Principal / lambda=0";
    if family == "Sparse PNNN N12"
        variant = "Principal";
    end
    principalRow = table(family, variant, false, ...
        double(principal.SelectedLambda), ...
        double(principal.TargetRealParameters), ...
        double(principal.ActualRealParameters), ...
        double(principal.InternalValidationNMSEdB), ...
        double(principal.IdentificationNMSEdB), ...
        double(principal.FullSignalNMSEdB), ...
        double(principal.FLOPsPerSample), ...
        double(principal.ActiveWeights), ...
        double(principal.ActiveBiases), ...
        double(principal.WeightSparsityPercent), ...
        double(principal.FineTuneEpochs), ...
        double(principal.MaxAbsRealParameter), ...
        'VariableNames', {'Family','Variant','UsesFixedRidge','Lambda', ...
        'TargetRealParameters','ActualRealParameters', ...
        'InternalValidationNMSEdB','IdentificationNMSEdB', ...
        'FullSignalNMSEdB','FLOPsPerSample','ActiveWeights', ...
        'ActiveBiases','WeightSparsityPercent','FineTuneEpochs', ...
        'MaxAbsRealParameter'});
    if isempty(complete.Properties.VariableNames)
        complete = principalRow;
    else
        complete = [complete; principalRow]; %#ok<AGROW>
    end
    if family == "Sparse PNNN N12"
        continue;
    end
    familyFixed = fixedRows(string(fixedRows.Model) == family, :);
    for row = 1:height(familyFixed)
        ridgeRow = table(family, "Fixed Ridge", true, ...
            double(familyFixed.FixedLambda(row)), ...
            double(familyFixed.TargetRealParameters(row)), ...
            double(familyFixed.ActualRealParameters(row)), NaN, ...
            double(familyFixed.IdentificationNMSEdB(row)), ...
            double(familyFixed.FullSignalNMSEdB(row)), ...
            double(familyFixed.FLOPsPerSample(row)), ...
            double(familyFixed.ActualRealParameters(row)), 0, NaN, NaN, ...
            double(familyFixed.MaxAbsRealParameter(row)), ...
            'VariableNames', principalRow.Properties.VariableNames);
        complete = [complete; ridgeRow]; %#ok<AGROW>
    end
end
end

function rows = orderFixedRows(value, target, fixedLambdas)
models = ["Complex GMP-DOMP"; "PN-IQ PN-DOMP"];
rows = value([],:);
for model = models.'
    for lambda = fixedLambdas.'
        match = string(value.Model) == model & ...
            value.TargetRealParameters == target & value.FixedLambda == lambda;
        if nnz(match) ~= 1
            error('run_selected_comparison:MissingFixedRow', ...
                'Each family and fixed lambda must occur exactly once.');
        end
        rows = [rows; value(match,:)]; %#ok<AGROW>
    end
end
end

function [files, window] = exportSelectedTimeDomainFigures( ...
    target, complexPrediction, pnPrediction, directory, exportOptions)
% Export deterministic central time-domain views for the two linear models.

target = target(:);
complexPrediction = complexPrediction(:);
pnPrediction = pnPrediction(:);
sampleCount = numel(target);
if numel(complexPrediction) ~= sampleCount || ...
        numel(pnPrediction) ~= sampleCount
    error('run_selected_comparison:TimeDomainLengthMismatch', ...
        'The measured and linear-model signals must have equal lengths.');
end

windowLength = min(1000, sampleCount);
firstSample = floor((sampleCount - windowLength)/2) + 1;
lastSample = firstSample + windowLength - 1;
indices = (firstSample:lastSample).';
signals = [target(indices), complexPrediction(indices), pnPrediction(indices)];

window = struct('firstAlignedSample', firstSample, ...
    'lastAlignedSample', lastSample, 'sampleCount', windowLength);
files = struct();
files.real = exportOneTimeDomainFigure(indices, signals, 'real', ...
    fullfile(directory, 'selected_time_domain_real'), exportOptions);
files.imaginary = exportOneTimeDomainFigure(indices, signals, 'imaginary', ...
    fullfile(directory, 'selected_time_domain_imaginary'), exportOptions);
end

function files = exportOneTimeDomainFigure(sampleIndices, signals, component, ...
    baseFilename, exportOptions)
style = getIEEEPaperStyle();
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Units', 'inches', 'Position', [1 1 7.16 4.6]);
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
layout.OuterPosition = [0 0.22 1 0.74];

leftAxes = nexttile(layout);
legendLines = plotTimeDomainPanel(leftAxes, sampleIndices, abs(signals), ...
    style);
title(leftAxes, '(a) Magnitude', 'Interpreter', 'none', ...
    'FontSize', style.fontSize, 'FontWeight', 'normal');
ylabel(leftAxes, 'Magnitude');

rightAxes = nexttile(layout);
if component == "real"
    componentValues = real(signals);
    componentTitle = '(b) Real part';
    componentLabel = 'Real part';
else
    componentValues = imag(signals);
    componentTitle = '(b) Imaginary part';
    componentLabel = 'Imaginary part';
end
plotTimeDomainPanel(rightAxes, sampleIndices, componentValues, style);
title(rightAxes, componentTitle, 'Interpreter', 'none', ...
    'FontSize', style.fontSize, 'FontWeight', 'normal');
ylabel(rightAxes, componentLabel);

labels = ["Measured output", "Complex GMP", "PN-IQ"];
legendHandle = legend(leftAxes, legendLines, labels, ...
    'Orientation', 'horizontal', 'NumColumns', 3, ...
    'Interpreter', 'none', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 1);
legendHandle.Units = 'normalized';
legendHandle.Position = [0.10 0.03 0.80 0.10];
legendHandle.Units = 'pixels';
axesHandles = findobj(figureHandle, 'Type', 'axes');
for axesIndex = 1:numel(axesHandles)
    axesHandles(axesIndex).Units = 'pixels';
end

markerStep = max(1, floor(numel(sampleIndices)/14));
exportOptions.tikzExtraAxisOptions = { ...
    'legend columns=3', ...
    'legend style={at={(1.1,-0.22)},anchor=north}', ...
    sprintf('every axis plot/.append style={mark repeat=%d}', markerStep)};
exportOptions.figureHeight = '4.6in';
files = exportPaperFigure(figureHandle, baseFilename, exportOptions);
clear cleanup;
end

function lines = plotTimeDomainPanel(axesHandle, sampleIndices, values, style)
hold(axesHandle, 'on');
markerIndices = unique([1:max(1, floor(numel(sampleIndices)/14)): ...
    numel(sampleIndices), numel(sampleIndices)]);
lines = gobjects(3, 1);
lines(1) = plot(axesHandle, sampleIndices, values(:, 1), ...
    'Color', style.targetGray, 'LineStyle', '-', ...
    'LineWidth', style.targetLineWidth);
for familyIndex = 1:2
    lines(familyIndex + 1) = plot(axesHandle, sampleIndices, ...
        values(:, familyIndex + 1), ...
        'Color', style.mainColors(familyIndex, :), ...
        'LineStyle', style.mainLineStyles{familyIndex}, ...
        'Marker', style.mainMarkers{familyIndex}, ...
        'MarkerIndices', markerIndices, ...
        'MarkerSize', style.markerSize - 1, ...
        'LineWidth', style.mainLineWidth);
end
grid(axesHandle, 'on');
box(axesHandle, 'on');
xlabel(axesHandle, 'Aligned full-signal sample');
set(axesHandle, 'FontName', style.fontName, ...
    'FontSize', style.fontSize, 'LineWidth', style.axisLineWidth);
end
