function result = run_parameter_sweep(parameterGrid)
% run_parameter_sweep - Run or resume the three-family complexity sweep.
% The scientific stages appear in execution order, while signed checkpoints
% keep linear, fixed-ridge, dense N12, and sparse targets independent.

%% Configure the experiment
projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
for folder = ["complexity","domp","metrics","pn_gmp_comparison", ...
        "pnnn","pnnn/pruning","splits","sweep"]
    addpath(fullfile(projectRoot, 'toolbox', folder));
end

cfg = getFairDOMPComparisonConfig(projectRoot);
cfg.sweep.enabled = true;

if nargin >= 1 && ~isempty(parameterGrid)
    cfg.sweep.parameterGrid = unique(double(parameterGrid(:).'));
end

targets = cfg.sweep.parameterGrid;
minimumPNNNParameters = cfg.pnnn.sparseBaseHiddenNeurons + 3;
if isempty(targets) || any(~isfinite(targets)) || ...
        any(targets ~= floor(targets)) || any(targets < minimumPNNNParameters) || ...
        any(mod(targets, 2))
    error('run_parameter_sweep:InvalidTargets', ...
        'Targets must be unique, even integers of at least %d.', ...
        minimumPNNNParameters);
end
sweepTimer = tic;

%% Load the measurement and build the common split
measurement = load(cfg.measurementFile, 'x', 'y');
if ~all(isfield(measurement, {'x','y'}))
    error('run_parameter_sweep:InvalidMeasurement', ...
        'The configured measurement must contain x and y.');
end

[x, y] = selectXYByMapping(measurement.x, measurement.y, cfg.mappingMode);
x = x(:);
y = y(:);

cfg.experimentSignature = buildExperimentSignature(x, y, cfg);

if cfg.pnnn.removeDC
    x = x - mean(x);
    y = y - mean(y);
end

split = buildCommonComparisonSplit(x, y, cfg);

% TODO: review the scientific split protocol after this equivalence rewrite.
sweepIdentity = buildSweepIdentity(cfg);
resultDirectory = resolveResultDirectory(cfg, sweepIdentity);

if ~isfolder(resultDirectory)
    mkdir(resultDirectory);
end

fprintf('\n=== Signed parameter-complexity sweep ===\n');
fprintf('Targets: %s\n', formatTargets(targets));
fprintf('Result directory: %s\n', resultDirectory);

%% Complex GMP and PN-IQ: select paths, fit prefixes, and predict
linearTimer = tic;

[linear, reusable] = updateSweepCheckpoint(resultDirectory, "linear", [], ...
    sweepIdentity, cfg.experimentSignature);

if ~reusable || ~validLinearCheckpoint(linear, targets, split)
    fprintf('[Linear] Building designs, DOMP paths, fits, and predictions...\n');
    linear = run_linear_sweep(x, y, split, cfg);
    updateSweepCheckpoint(resultDirectory, "linear", [], ...
        sweepIdentity, cfg.experimentSignature, linear);
    fprintf('[Linear] Completed in %.1f s.\n', toc(linearTimer));

else
    fprintf('[Linear] Reused matrices, paths, fits, and predictions in %.1f s.\n', ...
        toc(linearTimer));
end

%% Fixed Ridge: refit both linear families on the stored supports
fixedTimer = tic;
[fixedLinear, reusable] = updateSweepCheckpoint(resultDirectory, ...
    "fixed_linear", [], sweepIdentity, cfg.experimentSignature);

if ~reusable || ~validFixedCheckpoint(fixedLinear, linear, targets, split)
    fixedLinear = run_fixed_ridge_sweep(x, y, split, cfg, linear);
    updateSweepCheckpoint(resultDirectory, "fixed_linear", [], ...
        sweepIdentity, cfg.experimentSignature, fixedLinear);
    fprintf('[Fixed ridge] Completed in %.1f s.\n', toc(fixedTimer));

else
    fprintf('[Fixed ridge] Reused supplementary checkpoint in %.1f s.\n', ...
        toc(fixedTimer));
end

%% Sparse PNNN: prepare or reuse one immutable dense N12 source
denseTimer = tic;
[denseSource, reusable] = updateSweepCheckpoint(resultDirectory, "dense", [], ...
    sweepIdentity, cfg.experimentSignature);

if ~reusable || ~validDenseCheckpoint(denseSource)
    fprintf('[PNNN] Selecting epochs and fitting one dense N12 source...\n');

    denseStudy = prepare_pnnn_dense_source( ...
        x, y, split, cfg, cfg.reducedRealParameterTarget);

    denseSource = struct('denseFit', denseStudy.n12DenseFit, ...
        'signature', buildNetworkSignature(denseStudy.n12DenseFit), ...
        'bestDenseEpoch', denseStudy.selection.n12Dense.bestDenseEpoch, ...
        'fineTuneEpochs', denseStudy.selection.n12Sparse.bestFineTuneEpoch, ...
        'fineTuneBudgetSource', "shared N12 internal selection", ...
        'runtimeConfig', denseStudy.runtimeConfig);

    updateSweepCheckpoint(resultDirectory, "dense", [], ...
        sweepIdentity, cfg.experimentSignature, denseSource);

    features = denseStudy.features;
    neuralTargets = denseStudy.targets;
    phaseRotation = denseStudy.rotation;
    fprintf('[PNNN] Dense source completed in %.1f s.\n', toc(denseTimer));

else
    denseSource.fineTuneBudgetSource = "shared N12 internal selection";
    [features, neuralTargets, phaseRotation] = buildPhaseNormDataset( ...
        x, y, cfg.pnnn.M, cfg.pnnn.orders, cfg.pnnn.featMode);
    features = features.';

    neuralTargets = neuralTargets.';
    phaseRotation = phaseRotation(:);
    fprintf('[PNNN] Reused dense N12 checkpoint in %.1f s.\n', ...
        toc(denseTimer));
end

%% Sparse PNNN: prune and predict every requested parameter budget
schema = cfg.sweep.resultSchema;
pnnnRows = table('Size', [0 numel(schema.names)], ...
    'VariableTypes', schema.types, 'VariableNames', schema.names);
for index = 1:numel(targets)
    target = targets(index);
    timer = tic;
    fprintf('[PNNN %d/%d] Target %d parameters...\n', ...
        index, numel(targets), target);
    [point, reusable, filename] = updateSweepCheckpoint( ...
        resultDirectory, "pnnn", target, sweepIdentity, ...
        cfg.experimentSignature);
    [~, base, extension] = fileparts(filename);
    artifactName = string(base) + string(extension);
    if reusable
        try
            point = normalizeArtifactFile(point, artifactName, ...
                string(base), string(extension));
        catch exception
            if strcmp(exception.identifier, ...
                    'run_parameter_sweep:InvalidArtifactFile')
                reusable = false;
            else
                rethrow(exception);
            end
        end
    end
    if ~reusable || ~validPNNNCheckpoint( ...
            point, target, artifactName, denseSource, split)
        point = fit_sparse_pnnn_target(denseSource, target, features, ...
            neuralTargets, phaseRotation, y, split, cfg);
        point.row.ArtifactFile = artifactName;
        updateSweepCheckpoint(resultDirectory, "pnnn", target, ...
            sweepIdentity, cfg.experimentSignature, point);
        fprintf('[PNNN %d/%d] Completed in %.1f s.\n', ...
            index, numel(targets), toc(timer));
    else
        point.row.FineTuneBudgetSource = denseSource.fineTuneBudgetSource;
        fprintf('[PNNN %d/%d] Reused checkpoint in %.1f s.\n', ...
            index, numel(targets), toc(timer));
    end
    pnnnRows(index, :) = point.row;
end

%% Build the two public tables
results = [linear.complexTable; linear.pnTable; pnnnRows];
fixedResults = fixedLinear.table;
expectedModels = sort(["Complex GMP DOMP sweep"; ...
    "Independent PN-IQ PN-DOMP sweep"; "Sparse PNNN N12"]);
if height(results) ~= 3*numel(targets) || ...
        height(fixedResults) ~= 6*numel(targets)
    error('run_parameter_sweep:ResultRowCount', ...
        'The principal and fixed-ridge tables must contain 3N and 6N rows.');
end
for target = targets
    rows = results.TargetRealParameters == target;
    if nnz(rows) ~= 3 || ...
            ~isequal(sort(string(results.Model(rows))), expectedModels) || ...
            any(results.ActualRealParameters(rows) ~= target)
        error('run_parameter_sweep:ResultTargetMismatch', ...
            'Each target must contain the three exact-parameter families.');
    end
end
pnnnMask = string(results.Model) == "Sparse PNNN N12";
if any(results.ActiveWeights(pnnnMask) + results.ActiveBiases(pnnnMask) ~= ...
        results.ActualRealParameters(pnnnMask))
    error('run_parameter_sweep:PNNNParameterMismatch', ...
        'PNNN active weights and biases must equal its parameter count.');
end

%% Write the canonical CSV files and two sweep figures
fprintf('[Output] Writing complexity_sweep.csv...\n');
writeTableAtomically(results, resultDirectory, 'complexity_sweep.csv');
fprintf('[Output] Writing fixed_lambda_linear_sweep.csv...\n');
writeTableAtomically(fixedResults, resultDirectory, ...
    'fixed_lambda_linear_sweep.csv');
fprintf('[Output] Writing NMSE-vs-parameters figure...\n');
plotSweepFigure(results, fixedResults, 'ActualRealParameters', ...
    'Active real parameters', fullfile(resultDirectory, ...
    'comparison_nmse_parameters_sweep.png'), true);
fprintf('[Output] Writing NMSE-vs-FLOPs figure...\n');
plotSweepFigure(results, table(), 'FLOPsPerSample', ...
    'FLOPs per sample', fullfile(resultDirectory, ...
    'comparison_nmse_flops_sweep.png'), false);

%% Save the signed summary without duplicating predictions
summary = struct('results', results, ...
    'metadata', struct('fullSignalIsIndependentHoldout', false, ...
        'fullSignalUsedOnlyForEvaluation', true, ...
        'resultDirectory', string(resultDirectory)), ...
    'sweepIdentity', sweepIdentity, ...
    'experimentSignature', cfg.experimentSignature, ...
    'artifactFiles', ["linear_sweep.mat"; ...
        "fixed_lambda_linear_sweep.mat"; "sweep_dense_source.mat"; ...
        pnnnRows.ArtifactFile], ...
    'linearSupports', linear.supports);
updateSweepCheckpoint(resultDirectory, "summary", [], sweepIdentity, ...
    cfg.experimentSignature, summary);
result = summary;
result.resultDirectory = string(resultDirectory);
disp(results(:, {'Model','SweepRole','ActualRealParameters', ...
    'SelectedLambda','FullSignalNMSEdB','FLOPsPerSample'}));
fprintf('Sweep completed in %.1f s.\n', toc(sweepTimer));
end

function identity = buildSweepIdentity(cfg)
identity = struct('schemaVersion', cfg.sweep.schemaVersion, ...
    'experimentDigest', cfg.experimentSignature.digest, ...
    'parameterGrid', cfg.sweep.parameterGrid, ...
    'lambdaGrid', cfg.lambdaGrid, ...
    'fixedRidgeLambda', cfg.fixedRidgeLambda, ...
    'gmpOrders', [cfg.gmp.Qpmax cfg.gmp.Qnmax cfg.gmp.Pmax], ...
    'maximumPopulation', max(cfg.sweep.parameterGrid)/2, ...
    'dompOptions', cfg.gmp.dompOptions, ...
    'predictionBlock', cfg.gmp.blockSize, ...
    'pnCandidateBlock', cfg.sweep.candidateBlockSize, ...
    'denseSelectionTarget', cfg.reducedRealParameterTarget, ...
    'pnnn', cfg.pnnn, 'training', cfg.training, ...
    'pruning', cfg.pruning, ...
    'resultColumns', {cfg.sweep.resultSchema.names});

engine = javaMethod('getInstance', ...
    'java.security.MessageDigest', 'SHA-256');

bytes = unicode2native(jsonencode(identity), 'UTF-8');
engine.update(typecast(uint8(bytes), 'int8'));
digest = typecast(int8(engine.digest()), 'uint8');
identity.digest = string(lower(reshape(dec2hex(digest, 2).', 1, [])));
end

function directory = resolveResultDirectory(cfg, identity)
name = "sweep_" + extractBefore(string(identity.digest), 13);
if ~cfg.sweep.resume
    name = name + "_" + string(datetime('now', ...
        'Format', 'yyyyMMdd_HHmmss'));
end
directory = fullfile(cfg.sweep.resultsRoot, name);
end

function valid = validLinearCheckpoint(value, targets, split)
required = {'complexTable','pnTable','supports','paths', ...
    'lambdas','predictions','featureMetadata','metadata'};
try
    requiredColumns = {'Model','TargetRealParameters', ...
        'ActualRealParameters','SelectedLambda','FullSignalNMSEdB', ...
        'FLOPsPerSample'};
    valid = isstruct(value) && all(isfield(value, required)) && ...
        istable(value.complexTable) && istable(value.pnTable) && ...
        all(ismember(requiredColumns, ...
        value.complexTable.Properties.VariableNames)) && ...
        all(ismember(requiredColumns, ...
        value.pnTable.Properties.VariableNames)) && ...
        isequal(value.complexTable.TargetRealParameters.', targets) && ...
        isequal(value.pnTable.TargetRealParameters.', targets) && ...
        all(string(value.complexTable.Model) == "Complex GMP DOMP sweep") && ...
        all(string(value.pnTable.Model) == ...
        "Independent PN-IQ PN-DOMP sweep") && ...
        all(value.complexTable.ActualRealParameters.' == targets) && ...
        all(value.pnTable.ActualRealParameters.' == targets) && ...
        numel(value.supports.complex) == numel(targets) && ...
        numel(value.supports.pnFeatures) == numel(targets) && ...
        numel(value.supports.pnComplex) == numel(targets) && ...
        numel(value.paths.complexIdentification) >= max(targets)/2 && ...
        numel(value.paths.pnIdentification) >= max(targets)/2 && ...
        numel(value.lambdas.complex) == numel(targets) && ...
        numel(value.lambdas.pn) == numel(targets) && ...
        isequal(value.complexTable.SelectedLambda(:), ...
        value.lambdas.complex(:)) && ...
        isequal(value.pnTable.SelectedLambda(:), value.lambdas.pn(:)) && ...
        size(value.predictions.complexIdentification, 1) == ...
        numel(split.identificationIndices) && ...
        size(value.predictions.pnIdentification, 1) == ...
        numel(split.identificationIndices) && ...
        size(value.predictions.complexFull, 1) == ...
        numel(split.fullSignalIndices) && ...
        size(value.predictions.pnFull, 1) == ...
        numel(split.fullSignalIndices) && ...
        size(value.predictions.complexFull, 2) == numel(targets) && ...
        size(value.predictions.pnFull, 2) == numel(targets) && ...
        size(value.predictions.complexIdentification, 2) == numel(targets) && ...
        size(value.predictions.pnIdentification, 2) == numel(targets) && ...
        istable(value.featureMetadata) && ...
        all(ismember({'SourceRegressorIndex','Component'}, ...
        value.featureMetadata.Properties.VariableNames)) && ...
        islogical(value.metadata.fullSignalUsedForSelection) && ...
        islogical(value.metadata.fullSignalUsedForFitting) && ...
        ~value.metadata.fullSignalUsedForSelection && ...
        ~value.metadata.fullSignalUsedForFitting;
    if ~valid
        return;
    end
    complexPath = double(value.paths.complexIdentification(:));
    pnPath = double(value.paths.pnIdentification(:));
    for index = 1:numel(targets)
        count = targets(index)/2;
        pnFeatures = pnPath(1:count);
        expectedPNComplex = unique( ...
            value.featureMetadata.SourceRegressorIndex(pnFeatures), 'stable');
        valid = valid && ...
            isequal(double(value.supports.complex{index}(:)), ...
            complexPath(1:count)) && ...
            isequal(double(value.supports.pnFeatures{index}(:)), pnFeatures) && ...
            isequal(double(value.supports.pnComplex{index}(:)), ...
            double(expectedPNComplex(:)));
    end
catch
    valid = false;
end
end

function valid = validFixedCheckpoint(value, linear, targets, split)
required = {'table','fixedLambdas','supports','paths','reference','metadata'};
try
    requiredColumns = {'Model','TargetRealParameters', ...
        'ActualRealParameters','FixedLambda','IdentificationNMSEdB', ...
        'FullSignalNMSEdB','FLOPsPerSample'};
    models = ["Complex GMP-DOMP"; "PN-IQ PN-DOMP"];
    lambdas = [1e-3; 1e-4; 1e-5];
    valid = isstruct(value) && all(isfield(value, required)) && ...
        istable(value.table) && ...
        all(ismember(requiredColumns, value.table.Properties.VariableNames)) && ...
        height(value.table) == 6*numel(targets) && ...
        isequal(value.fixedLambdas(:), lambdas) && ...
        isequal(sort(unique(string(value.table.Model))), sort(models)) && ...
        all(isfinite(value.table.IdentificationNMSEdB)) && ...
        all(isfinite(value.table.FullSignalNMSEdB)) && ...
        isequaln(value.supports, linear.supports) && ...
        isequaln(value.paths, linear.paths) && ...
        value.metadata.dompInvocationCount == 0 && ...
        value.metadata.pnnnTrainingCount == 0;
    if ~valid
        return;
    end
    for model = models.'
        principal = linear.complexTable;
        if model == "PN-IQ PN-DOMP"
            principal = linear.pnTable;
        end
        for lambda = lambdas.'
            for target = targets
                row = string(value.table.Model) == model & ...
                    value.table.TargetRealParameters == target & ...
                    value.table.FixedLambda == lambda;
                principalRow = principal.TargetRealParameters == target;
                valid = valid && nnz(row) == 1 && nnz(principalRow) == 1 && ...
                    value.table.ActualRealParameters(row) == ...
                    principal.ActualRealParameters(principalRow) && ...
                    value.table.FLOPsPerSample(row) == ...
                    principal.FLOPsPerSample(principalRow);
            end
        end
    end
    referenceTarget = 20;
    if ~ismember(referenceTarget, targets)
        referenceTarget = targets(1);
    end
    referenceRow = string(value.table.Model) == "Complex GMP-DOMP" & ...
        value.table.TargetRealParameters == referenceTarget & ...
        value.table.FixedLambda == 1e-5;
    referenceIndex = find(targets == referenceTarget, 1);
    valid = valid && nnz(referenceRow) == 1 && ...
        string(value.reference.model) == "Complex GMP-DOMP" && ...
        value.reference.targetRealParameters == referenceTarget && ...
        value.reference.fixedLambda == 1e-5 && ...
        isequal(double(value.reference.support(:)), ...
        double(linear.supports.complex{referenceIndex}(:))) && ...
        value.reference.actualRealParameters == ...
        value.table.ActualRealParameters(referenceRow) && ...
        value.reference.flopsPerSample == ...
        value.table.FLOPsPerSample(referenceRow) && ...
        value.reference.identificationNMSEdB == ...
        value.table.IdentificationNMSEdB(referenceRow) && ...
        value.reference.fullSignalNMSEdB == ...
        value.table.FullSignalNMSEdB(referenceRow) && ...
        numel(value.reference.identificationPrediction) == ...
        numel(split.identificationIndices) && ...
        numel(value.reference.fullSignalPrediction) == ...
        numel(split.fullSignalIndices);
catch
    valid = false;
end
end

function valid = validDenseCheckpoint(value)
required = {'denseFit','signature','fineTuneEpochs', ...
    'fineTuneBudgetSource','runtimeConfig'};
try
    valid = isstruct(value) && all(isfield(value, required)) && ...
        isscalar(value.fineTuneEpochs) && isfinite(value.fineTuneEpochs) && ...
        value.fineTuneEpochs >= 0 && ...
        isequaln(buildNetworkSignature(value.denseFit), value.signature);
catch
    valid = false;
end
end

function point = normalizeArtifactFile(point, expected, base, extension)
validRow = isstruct(point) && isfield(point, 'row') && ...
    istable(point.row) && height(point.row) == 1 && ...
    ismember('ArtifactFile', point.row.Properties.VariableNames);
if ~validRow
    error('run_parameter_sweep:InvalidArtifactFile', ...
        'A one-row point table containing ArtifactFile is required.');
end
actual = point.row.ArtifactFile;
current = isstring(actual) && isscalar(actual) && actual == expected;
legacy = isstring(actual) && isequal(size(actual), [1 2]) && ...
    actual(1) == base && actual(2) == extension;
if ~(current || legacy)
    error('run_parameter_sweep:InvalidArtifactFile', ...
        'ArtifactFile does not match the current or exact legacy format.');
end
point.row.ArtifactFile = expected;
end

function valid = validPNNNCheckpoint(point, target, artifactName, ...
    denseSource, split)
required = {'target','row','mask','pruningStats', ...
    'maskIntegrityAfterPruning','maskIntegrityAfterFineTune', ...
    'identificationPrediction','fullSignalPrediction','denseSourceSignature'};
try
    requiredColumns = {'Model','TargetRealParameters', ...
        'ActualRealParameters','ActiveWeights','ActiveBiases', ...
        'InternalValidationNMSEdB','ArtifactFile'};
    valid = isstruct(point) && all(isfield(point, required)) && ...
        isscalar(point.target) && point.target == target && ...
        istable(point.row) && height(point.row) == 1 && ...
        all(ismember(requiredColumns, point.row.Properties.VariableNames)) && ...
        string(point.row.Model) == "Sparse PNNN N12" && ...
        point.row.TargetRealParameters == target && ...
        point.row.ActualRealParameters == target && ...
        point.row.ActiveWeights + point.row.ActiveBiases == target && ...
        isstring(point.row.ArtifactFile) && ...
        isscalar(point.row.ArtifactFile) && ...
        point.row.ArtifactFile == artifactName && ...
        isnan(point.row.InternalValidationNMSEdB) && ...
        isequaln(point.denseSourceSignature, denseSource.signature) && ...
        isscalar(point.maskIntegrityAfterPruning.ok) && ...
        point.maskIntegrityAfterPruning.ok && ...
        isscalar(point.maskIntegrityAfterFineTune.ok) && ...
        point.maskIntegrityAfterFineTune.ok && ...
        numel(point.identificationPrediction) == ...
        numel(split.identificationIndices) && ...
        numel(point.fullSignalPrediction) == ...
        numel(split.fullSignalIndices) && ...
        all(isfinite(point.identificationPrediction)) && ...
        all(isfinite(point.fullSignalPrediction));
catch
    valid = false;
end
end

function value = formatTargets(targets)
if numel(targets) >= 2 && all(diff(targets) == targets(2) - targets(1))
    value = sprintf('%d:%d:%d', targets(1), ...
        targets(2) - targets(1), targets(end));
else
    value = strjoin(string(targets), ', ');
end
end

function writeTableAtomically(value, directory, filename)
finalFile = fullfile(directory, filename);
temporaryFile = [tempname(directory) '.csv'];
cleanup = onCleanup(@() deleteIfPresent(temporaryFile));
writetable(value, temporaryFile);
[moved, message] = movefile(temporaryFile, finalFile, 'f');
if ~moved
    error('run_parameter_sweep:CSVMoveFailed', ...
        'Could not install %s: %s', filename, message);
end
clear cleanup;
end

function plotSweepFigure(results, fixed, xVariable, xLabel, filename, ...
    includeFixed)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100 100 900 600]);
cleanup = onCleanup(@() close(figureHandle));
hold on;
models = ["Complex GMP DOMP sweep", ...
    "Independent PN-IQ PN-DOMP sweep", "Sparse PNNN N12"];
labels = ["Complex GMP-DOMP", "PN-IQ PN-DOMP", "Sparse PNNN N12"];
mainLines = gobjects(3, 1);
for index = 1:3
    rows = string(results.Model) == models(index);
    x = results.(xVariable)(rows);
    y = results.FullSignalNMSEdB(rows);
    [x, order] = sort(x);
    mainLines(index) = plot(x, y(order), '-o', ...
        'LineWidth', 1 + includeFixed, 'DisplayName', labels(index));
end
if includeFixed
    fixedModels = ["Complex GMP-DOMP", "PN-IQ PN-DOMP"];
    lambdas = [1e-3, 1e-4, 1e-5];
    styles = ["--", ":", "-."];
    for modelIndex = 1:2
        for lambdaIndex = 1:3
            rows = string(fixed.Model) == fixedModels(modelIndex) & ...
                fixed.FixedLambda == lambdas(lambdaIndex);
            x = fixed.(xVariable)(rows);
            y = fixed.FullSignalNMSEdB(rows);
            [x, order] = sort(x);
            plot(x, y(order), 'LineStyle', styles(lambdaIndex), ...
                'Color', mainLines(modelIndex).Color, 'LineWidth', 1, ...
                'DisplayName', fixedModels(modelIndex) + ", lambda=" + ...
                compose('%g', lambdas(lambdaIndex)));
        end
    end
end
grid on;
xlabel(xLabel);
ylabel('Full-signal NMSE (dB)');
legend('Location', 'southoutside', 'Orientation', 'horizontal', ...
    'NumColumns', 3, 'Interpreter', 'none');
exportgraphics(figureHandle, filename, 'Resolution', 160, ...
    'BackgroundColor', 'white');
clear cleanup;
end

function deleteIfPresent(filename)
if isfile(filename)
    delete(filename);
end
end
