function result = run_parameter_sweep(parameterGrid)
% run_parameter_sweep - Run or safely resume the signed complexity sweep.
% Linear families are one atomic unit; each sparse PNNN target is independent.
% Full-signal rows are used only after selection and identification fitting.

%% Configure the signed sweep
projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
for folder = ["complexity","domp","metrics","pn_gmp_comparison", ...
        "pnnn","pnnn/pruning","splits","sweep"]
    addpath(fullfile(projectRoot, 'toolbox', folder));
end
cfg = getFairDOMPComparisonConfig(projectRoot);
cfg.sweep.enabled = true;
if nargin >= 1 && ~isempty(parameterGrid)
    cfg.sweep.parameterGrid = unique(double(parameterGrid(:).'));
end
validateattributes(cfg.sweep.parameterGrid, {'numeric'}, ...
    {'vector','integer','positive','finite'});
if any(mod(cfg.sweep.parameterGrid, 2))
    error('run_parameter_sweep:OddTarget', ...
        'Every sweep target must contain an even number of real parameters.');
end

%% Prepare data and the common split
measurement = load(cfg.measurementFile, 'x', 'y');
if ~all(isfield(measurement, {'x','y'}))
    error('run_parameter_sweep:InvalidMeasurement', ...
        'The configured measurement must contain x and y.');
end
[x, y] = selectXYByMapping(measurement.x, measurement.y, cfg.mappingMode);
x = x(:);
y = y(:);
cfg.experimentSignature = buildExperimentSignature(x, y, cfg);
if cfg.pnnn.removeDC
    x = x - mean(x);
    y = y - mean(y);
end
split = buildCommonComparisonSplit(x, y, cfg);
sweepIdentity = buildSweepIdentity(cfg);
resultDirectory = resolveResultDirectory(cfg, sweepIdentity);
if ~isfolder(resultDirectory)
    mkdir(resultDirectory);
end
fprintf('\n=== Signed parameter-complexity sweep ===\n%s\n', resultDirectory);

%% Run or reuse the atomic linear family
[linear, reusable] = updateSweepCheckpoint(resultDirectory, "linear", [], ...
    sweepIdentity, cfg.experimentSignature);
if ~reusable || ~validLinearArtifact(linear, cfg, split)
    linear = runLinearComplexitySweep(x, y, split, cfg);
    updateSweepCheckpoint(resultDirectory, "linear", [], ...
        sweepIdentity, cfg.experimentSignature, linear);
end

%% Prepare or reuse one N12 dense source
[denseSource, reusable] = updateSweepCheckpoint(resultDirectory, "dense", [], ...
    sweepIdentity, cfg.experimentSignature);
if ~reusable || ~validDenseSource(denseSource, cfg)
    denseStudy = runPNNNComparisonStudy(x, y, split, cfg, ...
        cfg.sweep.historicalReferenceParameters, "sweep_n12");
    denseSource = struct('denseFit', denseStudy.n12DenseFit, ...
        'signature', buildNetworkSignature(denseStudy.n12DenseFit), ...
        'bestDenseEpoch', denseStudy.selection.n12Dense.bestDenseEpoch, ...
        'fineTuneEpochs', denseStudy.selection.n12Sparse.bestFineTuneEpoch, ...
        'fineTuneBudgetSource', ...
            "historical parameter-matched 344 selection", ...
        'historicalTarget', cfg.sweep.historicalReferenceParameters, ...
        'runtimeConfig', denseStudy.runtimeConfig);
    updateSweepCheckpoint(resultDirectory, "dense", [], ...
        sweepIdentity, cfg.experimentSignature, denseSource);
    features = denseStudy.features;
    neuralTargets = denseStudy.targets;
    rotation = denseStudy.rotation;
else
    [features, neuralTargets, rotation] = buildPhaseNormDataset( ...
        x, y, cfg.pnnn.M, cfg.pnnn.orders, cfg.pnnn.featMode);
    features = features.';
    neuralTargets = neuralTargets.';
    rotation = rotation(:);
end

%% Run or reuse independent sparse PNNN targets
pnnnRows = emptyResultTable(cfg);
pnnnFiles = strings(numel(cfg.sweep.parameterGrid), 1);
for index = 1:numel(cfg.sweep.parameterGrid)
    target = cfg.sweep.parameterGrid(index);
    [point, reusable, filename] = updateSweepCheckpoint( ...
        resultDirectory, "pnnn", target, sweepIdentity, ...
        cfg.experimentSignature);
    [~, base, extension] = fileparts(filename);
    artifactName = string([base extension]);
    if ~reusable || ~validPNNNPoint( ...
            point, target, artifactName, denseSource, split)
        point = runPNNNSparseSweep(denseSource, target, features, ...
            neuralTargets, rotation, y, split, cfg);
        point.row.ArtifactFile = artifactName;
        updateSweepCheckpoint(resultDirectory, "pnnn", target, ...
            sweepIdentity, cfg.experimentSignature, point);
    end
    pnnnRows(index, :) = point.row;
    pnnnFiles(index) = artifactName;
end

%% Package the canonical table without duplicating predictions
results = [linear.complexTable; linear.pnTable; ...
    linear.historicalTable; pnnnRows];
summary = struct('results', results, ...
    'metadata', struct('fullSignalIsIndependentHoldout', false, ...
        'fullSignalUsedOnlyForEvaluation', true, ...
        'resultDirectory', string(resultDirectory)), ...
    'sweepIdentity', sweepIdentity, ...
    'experimentSignature', cfg.experimentSignature, ...
    'artifactFiles', ["linear_sweep.mat"; "sweep_dense_source.mat"; pnnnFiles], ...
    'linearSupports', linear.supports, ...
    'pnComparison344', linear.comparison344, ...
    'rows344', results(results.ActualRealParameters == ...
        cfg.sweep.historicalReferenceParameters, :));
updateSweepCheckpoint(resultDirectory, "summary", [], sweepIdentity, ...
    cfg.experimentSignature, summary);
writeCanonicalOutputs(results, resultDirectory, linear.historicalTable);
result = summary;
result.resultDirectory = string(resultDirectory);
disp(results(:, {'Model','SweepRole','ActualRealParameters', ...
    'SelectedLambda','FullSignalNMSEdB','FLOPsPerSample'}));
end

function identity = buildSweepIdentity(cfg)
maximumPopulation = max(cfg.sweep.parameterGrid)/2;
if cfg.sweep.includeHistoricalPNIQReference
    maximumPopulation = max(maximumPopulation, cfg.gmp.maxPopulation);
end
identity = struct('schemaVersion', cfg.sweep.schemaVersion, ...
    'experimentDigest', cfg.experimentSignature.digest, ...
    'parameterGrid', cfg.sweep.parameterGrid, 'lambdaGrid', cfg.lambdaGrid, ...
    'fixedRidgeLambda', cfg.fixedRidgeLambda, ...
    'gmpOrders', [cfg.gmp.Qpmax cfg.gmp.Qnmax cfg.gmp.Pmax], ...
    'maximumPopulation', maximumPopulation, ...
    'dompOptions', cfg.gmp.dompOptions, 'predictionBlock', cfg.gmp.blockSize, ...
    'pnCandidateBlock', cfg.sweep.candidateBlockSize, ...
    'historicalPNIQ', cfg.sweep.includeHistoricalPNIQReference, ...
    'historicalTarget', cfg.sweep.historicalReferenceParameters, ...
    'pnnn', cfg.pnnn, 'training', cfg.training, 'pruning', cfg.pruning, ...
    'resultColumns', {cfg.sweep.resultSchema.names});
identity.digest = hashText(jsonencode(identity));
end

function directory = resolveResultDirectory(cfg, identity)
name = "sweep_" + extractBefore(string(identity.digest), 13);
if ~cfg.sweep.resume
    name = name + "_" + string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
end
directory = fullfile(cfg.sweep.resultsRoot, name);
end

function valid = validLinearArtifact(value, cfg, split)
required = {'complexTable','pnTable','historicalTable','supports', ...
    'paths','lambdas','predictions','metadata'};
try
    valid = isstruct(value) && all(isfield(value, required)) && ...
        isequal(value.complexTable.TargetRealParameters.', ...
            cfg.sweep.parameterGrid) && ...
        isequal(value.pnTable.TargetRealParameters.', ...
            cfg.sweep.parameterGrid) && ...
        size(value.predictions.complexFull, 1) == ...
            numel(split.fullSignalIndices) && ...
        size(value.predictions.pnFull, 1) == ...
            numel(split.fullSignalIndices) && ...
        ~value.metadata.fullSignalUsedForSelection && ...
        ~value.metadata.fullSignalUsedForFitting;
catch
    valid = false;
end
end

function valid = validDenseSource(value, cfg)
required = {'denseFit','signature','fineTuneEpochs', ...
    'fineTuneBudgetSource','historicalTarget','runtimeConfig'};
try
    valid = isstruct(value) && all(isfield(value, required)) && ...
        value.historicalTarget == cfg.sweep.historicalReferenceParameters;
    if valid
        valid = isequaln(buildNetworkSignature(value.denseFit), value.signature);
    end
catch
    valid = false;
end
end

function valid = validPNNNPoint( ...
    point, target, artifactName, denseSource, split)
required = {'target','row','mask','pruningStats', ...
    'maskIntegrityAfterPruning','maskIntegrityAfterFineTune', ...
    'identificationPrediction','fullSignalPrediction','denseSourceSignature'};
try
    valid = isstruct(point) && all(isfield(point, required)) && ...
        point.target == target && height(point.row) == 1 && ...
        point.row.ActualRealParameters == target && ...
        point.row.ArtifactFile == artifactName && ...
        isnan(point.row.InternalValidationNMSEdB) && ...
        isequaln(point.denseSourceSignature, denseSource.signature) && ...
        point.maskIntegrityAfterPruning.ok && ...
        point.maskIntegrityAfterFineTune.ok && ...
        numel(point.identificationPrediction) == ...
            numel(split.identificationIndices) && ...
        numel(point.fullSignalPrediction) == ...
            numel(split.fullSignalIndices) && ...
        all(isfinite(point.identificationPrediction)) && ...
        all(isfinite(point.fullSignalPrediction));
catch
    valid = false;
end
end

function writeCanonicalOutputs(results, directory, historical)
csvFile = fullfile(directory, 'complexity_sweep.csv');
temporaryCSV = fullfile(directory, 'complexity_sweep.tmp.csv');
writetable(results, temporaryCSV);
movefile(temporaryCSV, csvFile, 'f');
figureHandle = figure('Visible', 'off', 'Color', 'w');
hold on;
families = ["Complex GMP DOMP sweep", ...
    "Independent PN-IQ PN-DOMP sweep", "Sparse PNNN N12"];
for family = families
    rows = results.Model == family & results.SweepRole == "Sweep point";
    plot(results.ActualRealParameters(rows), results.FullSignalNMSEdB(rows), ...
        '-o', 'DisplayName', family);
end
if ~isempty(historical)
    plot(historical.ActualRealParameters, historical.FullSignalNMSEdB, ...
        'kp', 'MarkerSize', 11, 'MarkerFaceColor', 'y', ...
        'LineStyle', 'none', 'DisplayName', ...
        'Historical PN-IQ full, complex-DOMP-derived');
end
grid on;
xlabel('Active real parameters');
ylabel('Full-signal NMSE (dB)');
legend('Location', 'best', 'Interpreter', 'none');
exportgraphics(figureHandle, fullfile(directory, ...
    'comparison_nmse_parameters_sweep.png'), 'Resolution', 160);
close(figureHandle);
end

function value = emptyResultTable(cfg)
schema = cfg.sweep.resultSchema;
value = table('Size', [0 numel(schema.names)], ...
    'VariableTypes', schema.types, 'VariableNames', schema.names);
end

function digest = hashText(value)
engine = javaMethod('getInstance', ...
    'java.security.MessageDigest', 'SHA-256');
engine.update(typecast(uint8(unicode2native(char(value), 'UTF-8')), 'int8'));
bytes = typecast(int8(engine.digest()), 'uint8');
digest = string(lower(reshape(dec2hex(bytes, 2).', 1, [])));
end
