% Script: run_fixed_ridge_1e5_comparison
% Refit the frozen GMP-derived linear models with LS and fixed ridge 1e-5.
% DOMP supports, identification rows, PNNN results, and inference costs stay fixed.

clearvars;
clc;

project_root = fileparts(mfilename('fullpath'));
if isempty(project_root)
    project_root = pwd;
end
addpath(fullfile(project_root, 'config'));
addpath(fullfile(project_root, 'toolbox', 'metrics'));
addpath(fullfile(project_root, 'toolbox', 'pn_gmp_comparison'));

RIDGE_LAMBDA = 1e-5;
EXPECTED_IDENTIFICATION_SAMPLES = 19661;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE_RUN = '20260714_102201';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

source_directory = fullfile(project_root, 'results', ...
    'full_signal_domp_comparison', SOURCE_RUN);
required_files = {'comparison_config.mat', 'comparison_results.mat', ...
    'complexity_flops.csv', 'domp_supports.mat', 'split_indices.mat'};
for file_index = 1:numel(required_files)
    if ~isfile(fullfile(source_directory, required_files{file_index}))
        error('run_fixed_ridge_1e5_comparison:MissingFrozenArtifact', ...
            'Missing frozen artifact: %s', required_files{file_index});
    end
end

timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
result_directory = fullfile(project_root, 'results', ...
    'fixed_ridge_1e5_comparison', timestamp);
if ~isfolder(result_directory)
    mkdir(result_directory);
end

config_data = load(fullfile(source_directory, 'comparison_config.mat'), 'cfg');
split_data = load(fullfile(source_directory, 'split_indices.mat'), ...
    'identification_indices', 'full_signal_indices');
support_data = load(fullfile(source_directory, 'domp_supports.mat'), 'supports');
reference_data = load(fullfile(source_directory, ...
    'comparison_results.mat'), 'comparison_results');
complexity_table = readtable(fullfile(source_directory, ...
    'complexity_flops.csv'));
cfg = config_data.cfg;
supports = support_data.supports;
reference_results = reference_data.comparison_results;
identification_indices = double(split_data.identification_indices(:));
full_signal_indices = double(split_data.full_signal_indices(:));

if numel(identification_indices) ~= EXPECTED_IDENTIFICATION_SAMPLES || ...
        ~isequal(full_signal_indices, (1:cfg.expectedSignalLength).')
    error('run_fixed_ridge_1e5_comparison:ChangedSampleProtocol', ...
        'The frozen identification/full-signal protocol has changed.');
end
if numel(supports.supportDOMP) ~= 100 || ...
        numel(supports.supportParameterMatchedDOMP) ~= 179 || ...
        numel(supports.reducedFeatureSupportDOMP) ~= 100
    error('run_fixed_ridge_1e5_comparison:ChangedFrozenSupports', ...
        'Frozen support sizes must remain 100, 179, and 100.');
end

measurement_file = fullfile(project_root, 'measurements', ...
    [cfg.measurementName '.mat']);
measurement = load(measurement_file, 'x', 'y');
[x_raw, y_raw] = selectXYByMapping( ...
    measurement.x, measurement.y, cfg.mappingMode);
x_raw = x_raw(:);
y_raw = y_raw(:);
if cfg.pnnn.removeDC
    x = x_raw - mean(x_raw);
    y = y_raw - mean(y_raw);
else
    x = x_raw;
    y = y_raw;
end
if numel(x) ~= cfg.expectedSignalLength || numel(y) ~= numel(x) || ...
        any(~isfinite(x)) || any(~isfinite(y))
    error('run_fixed_ridge_1e5_comparison:InvalidMeasurement', ...
        'The configured modeled-block X/Y measurement is invalid.');
end

fprintf('\n=== Frozen-support LS and fixed ridge 1e-5 comparison ===\n');
fprintf('Source run: %s\n', source_directory);
fprintf('Identification samples: %d\n', numel(identification_indices));
fprintf('Full-signal samples: %d\n', numel(full_signal_indices));
fprintf('No DOMP selection or PNNN training is executed.\n\n');

gmp_manager = GMP_createRegressorManager(x, y, cfg.gmp);
population_indices = (1:numel(gmp_manager.regPopulation)).';
support_base = double(supports.supportDOMP(:));
support_matched = double(supports.supportParameterMatchedDOMP(:));
reduced_feature_support = double(supports.reducedFeatureSupportDOMP(:));

U_identification = buildGMPRegressorRows( ...
    x, identification_indices, gmp_manager, population_indices);
y_identification = y(identification_indices);
target_full_signal = y(full_signal_indices);

complex_base = fitComplexGMPGrid(U_identification, y_identification, ...
    support_base, [0, RIDGE_LAMBDA]);
complex_matched = fitComplexGMPGrid(U_identification, y_identification, ...
    support_matched, [0, RIDGE_LAMBDA]);

phase_rotation = computePhaseNormGMPRotation(x, identification_indices);
U_phase_normalized = phase_rotation .* U_identification;
y_phase_normalized = phase_rotation .* y_identification;
coupled_ridge_cfg = struct( ...
    'supportMode', 'reuse_complex_support', ...
    'supportComplex', support_base, ...
    'lambda', RIDGE_LAMBDA, ...
    'normUComplex', complex_base.normU);
coupled_ridge = fitPhaseNormGMPReal( ...
    U_phase_normalized, y_phase_normalized, coupled_ridge_cfg);
coupled_ls = mapComplexCoefficientsToCoupled( ...
    support_base, complex_base.coefficients(:, 1), ...
    numel(population_indices), complex_base.normU, 0);

[pn_raw_identification, pn_details] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, identification_indices, gmp_manager, support_base);
[pn_features, pn_reduction] = removeStructurallyZeroQFeatures( ...
    pn_raw_identification, pn_details.featureMetadata, 1e-12);
if size(pn_features, 2) ~= 179
    error('run_fixed_ridge_1e5_comparison:ChangedPNFeatureCount', ...
        'Independent PN-IQ must retain exactly 179 real features.');
end
pn_ls = fitIndependentIQGMP(pn_features, y_phase_normalized, ...
    0, pn_reduction, "Independent PN-IQ full");
pn_ridge = fitIndependentFixedRidge(pn_features, y_phase_normalized, ...
    RIDGE_LAMBDA, pn_reduction, "Independent PN-IQ full");

[no_pn_raw_identification, no_pn_details] = ...
    buildUnnormalizedIQRegressors( ...
    x, identification_indices, gmp_manager, support_base);
[no_pn_features, no_pn_reduction] = reduceStructuralFeatures( ...
    no_pn_raw_identification, no_pn_details.featureMetadata, 1e-12);
if size(no_pn_features, 2) ~= 197
    error('run_fixed_ridge_1e5_comparison:ChangedNoPNFeatureCount', ...
        'Independent I/Q without PN must retain exactly 197 real features.');
end
no_pn_ls = fitIndependentIQGMP(no_pn_features, y_identification, ...
    0, no_pn_reduction, "Independent I/Q without PN");
no_pn_ridge = fitIndependentFixedRidge(no_pn_features, ...
    y_identification, RIDGE_LAMBDA, no_pn_reduction, ...
    "Independent I/Q without PN");

pn_reduced_reduction = buildSelectedReduction( ...
    pn_reduction, reduced_feature_support);
pn_reduced_features = pn_features(:, reduced_feature_support);
pn_reduced_ls = fitIndependentIQGMP(pn_reduced_features, ...
    y_phase_normalized, 0, pn_reduced_reduction, ...
    "Independent PN-IQ reduced DOMP");
pn_reduced_ridge = fitIndependentFixedRidge(pn_reduced_features, ...
    y_phase_normalized, RIDGE_LAMBDA, pn_reduced_reduction, ...
    "Independent PN-IQ reduced DOMP");

% Identification predictions use the same matrices that define all norms.
identification_ls = struct();
identification_ridge = struct();
identification_ls.complexGMP = U_identification(:, support_base) * ...
    complex_base.coefficients(:, 1);
identification_ridge.complexGMP = U_identification(:, support_base) * ...
    complex_base.coefficients(:, 2);
identification_ls.coupledPNIQ = coupledMatrixPrediction( ...
    U_phase_normalized(:, support_base), coupled_ls.hReal, phase_rotation);
identification_ridge.coupledPNIQ = coupledMatrixPrediction( ...
    U_phase_normalized(:, support_base), coupled_ridge.hReal, phase_rotation);
identification_ls.independentPNIQ = independentMatrixPrediction( ...
    pn_features, pn_ls, phase_rotation);
identification_ridge.independentPNIQ = independentMatrixPrediction( ...
    pn_features, pn_ridge, phase_rotation);
identification_ls.complexParameterMatched = ...
    U_identification(:, support_matched) * complex_matched.coefficients(:, 1);
identification_ridge.complexParameterMatched = ...
    U_identification(:, support_matched) * complex_matched.coefficients(:, 2);
identification_ls.independentNoPN = independentMatrixPrediction( ...
    no_pn_features, no_pn_ls, ones(numel(identification_indices), 1));
identification_ridge.independentNoPN = independentMatrixPrediction( ...
    no_pn_features, no_pn_ridge, ones(numel(identification_indices), 1));
identification_ls.independentPNIQReduced = independentMatrixPrediction( ...
    pn_reduced_features, pn_reduced_ls, phase_rotation);
identification_ridge.independentPNIQReduced = independentMatrixPrediction( ...
    pn_reduced_features, pn_reduced_ridge, phase_rotation);

assertEquivalent(identification_ridge.complexGMP, ...
    identification_ridge.coupledPNIQ, y_identification, ...
    'ridge identification');
verifyFrozenLS(reference_results, identification_ls, y_identification);

% Only ridge predictions are newly evaluated over the full signal.
full_signal_ridge = struct();
full_signal_ridge.complexGMP = GMP_blockPredict( ...
    x, gmp_manager, support_base, complex_base.coefficients(:, 2), ...
    cfg.gmp.blockSize, full_signal_indices);
full_signal_ridge.coupledPNIQ = predictPhaseNormGMPReal( ...
    x, full_signal_indices, gmp_manager, coupled_ridge, cfg.gmp.blockSize);
full_signal_ridge.independentPNIQ = predictIndependentIQGMP( ...
    x, full_signal_indices, gmp_manager, support_base, pn_ridge, ...
    cfg.gmp.blockSize);
full_signal_ridge.complexParameterMatched = GMP_blockPredict( ...
    x, gmp_manager, support_matched, complex_matched.coefficients(:, 2), ...
    cfg.gmp.blockSize, full_signal_indices);
full_signal_ridge.independentNoPN = predictIndependentIQNoPN( ...
    x, full_signal_indices, gmp_manager, support_base, no_pn_ridge, ...
    cfg.gmp.blockSize);
full_signal_ridge.independentPNIQReduced = predictIndependentIQGMP( ...
    x, full_signal_indices, gmp_manager, support_base, pn_reduced_ridge, ...
    cfg.gmp.blockSize);
assertEquivalent(full_signal_ridge.complexGMP, ...
    full_signal_ridge.coupledPNIQ, target_full_signal, ...
    'ridge full signal');

model_names = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; ...
    "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; ...
    "Independent PN-IQ reduced DOMP"];
identification_ls_cells = structToOrderedCell(identification_ls);
identification_ridge_cells = structToOrderedCell(identification_ridge);
full_signal_ridge_cells = structToOrderedCell(full_signal_ridge);
ls_coefficient_norms = [ ...
    norm(complex_base.coefficients(:, 1)); ...
    norm(coupled_ls.hReal); ...
    norm([pn_ls.coefficientsI; pn_ls.coefficientsQ]); ...
    norm(complex_matched.coefficients(:, 1)); ...
    norm([no_pn_ls.coefficientsI; no_pn_ls.coefficientsQ]); ...
    norm([pn_reduced_ls.coefficientsI; pn_reduced_ls.coefficientsQ])];
ridge_coefficient_norms = [ ...
    norm(complex_base.coefficients(:, 2)); ...
    norm(coupled_ridge.hReal); ...
    norm([pn_ridge.coefficientsI; pn_ridge.coefficientsQ]); ...
    norm(complex_matched.coefficients(:, 2)); ...
    norm([no_pn_ridge.coefficientsI; no_pn_ridge.coefficientsQ]); ...
    norm([pn_reduced_ridge.coefficientsI; pn_reduced_ridge.coefficientsQ])];

n_models = numel(model_names);
real_parameters = zeros(n_models, 1);
frozen_support_size = zeros(n_models, 1);
ls_identification_nmse_db = zeros(n_models, 1);
ls_full_signal_nmse_db = zeros(n_models, 1);
ridge_identification_nmse_db = zeros(n_models, 1);
ridge_full_signal_nmse_db = zeros(n_models, 1);
flops_per_sample = zeros(n_models, 1);
additional_operations = strings(n_models, 1);
for model_index = 1:n_models
    reference_row = reference_results.Model == model_names(model_index);
    cost_row = complexity_table.Model == model_names(model_index);
    if nnz(reference_row) ~= 1 || nnz(cost_row) ~= 1
        error('run_fixed_ridge_1e5_comparison:MissingReferenceRow', ...
            'Missing unique frozen row for %s.', model_names(model_index));
    end
    real_parameters(model_index) = ...
        reference_results.NumRealParameters(reference_row);
    frozen_support_size(model_index) = ...
        reference_results.DOMPSupportSize(reference_row);
    ls_identification_nmse_db(model_index) = ...
        reference_results.IdentificationNMSEdB(reference_row);
    ls_full_signal_nmse_db(model_index) = ...
        reference_results.FullSignalNMSEdB(reference_row);
    ridge_identification_nmse_db(model_index) = nmseComplexDb( ...
        y_identification, identification_ridge_cells{model_index});
    ridge_full_signal_nmse_db(model_index) = nmseComplexDb( ...
        target_full_signal, full_signal_ridge_cells{model_index});
    flops_per_sample(model_index) = ...
        complexity_table.FLOPsPerSample(cost_row);
    additional_operations(model_index) = ...
        describeAdditionalOperations(complexity_table(cost_row, :));
end

linear_ls_ridge_results = table(model_names, real_parameters, ...
    frozen_support_size, repmat(numel(identification_indices), n_models, 1), ...
    repmat(numel(full_signal_indices), n_models, 1), ...
    ls_identification_nmse_db, ls_full_signal_nmse_db, ...
    ridge_identification_nmse_db, ridge_full_signal_nmse_db, ...
    ls_coefficient_norms, ridge_coefficient_norms, ...
    repmat(RIDGE_LAMBDA, n_models, 1), flops_per_sample, ...
    additional_operations, ...
    'VariableNames', {'Model','RealParameters','FrozenSupportSize', ...
    'IdentificationSamples','FullSignalSamples', ...
    'LSIdentificationNMSEdB','LSFullSignalNMSEdB', ...
    'Ridge1e5IdentificationNMSEdB','Ridge1e5FullSignalNMSEdB', ...
    'LSCoefficientL2','Ridge1e5CoefficientL2','RidgeLambda', ...
    'FLOPsPerSample','AdditionalOperations'});

ridge_metadata = struct();
ridge_metadata.lambda = RIDGE_LAMBDA;
ridge_metadata.lambdaSelection = 'fixed; no validation or cross-validation';
ridge_metadata.sourceRun = SOURCE_RUN;
ridge_metadata.identificationSamples = numel(identification_indices);
ridge_metadata.fullSignalSamples = numel(full_signal_indices);
ridge_metadata.supportsLoadedWithoutSelection = true;
ridge_metadata.columnNormDomain = 'identification only';
ridge_metadata.coefficientsStoredInOriginalRegressorScale = true;
ridge_metadata.inferenceNormalizationFLOPsAdded = 0;
ridge_metadata.interceptPresent = false;
ridge_metadata.complexCoupledIdentificationRelativeError = relativeError( ...
    identification_ridge.complexGMP, identification_ridge.coupledPNIQ);
ridge_metadata.complexCoupledFullSignalRelativeError = relativeError( ...
    full_signal_ridge.complexGMP, full_signal_ridge.coupledPNIQ);

fits = struct();
fits.complexBase = complex_base;
fits.coupledLS = coupled_ls;
fits.coupledRidge1e5 = coupled_ridge;
fits.independentPNIQLS = pn_ls;
fits.independentPNIQRidge1e5 = pn_ridge;
fits.complexParameterMatched = complex_matched;
fits.independentNoPNLS = no_pn_ls;
fits.independentNoPNRidge1e5 = no_pn_ridge;
fits.independentPNIQReducedLS = pn_reduced_ls;
fits.independentPNIQReducedRidge1e5 = pn_reduced_ridge;

writetable(linear_ls_ridge_results, fullfile(result_directory, ...
    'linear_ls_ridge_results.csv'));
save(fullfile(result_directory, 'linear_ls_ridge_results.mat'), ...
    'linear_ls_ridge_results', 'ridge_metadata');
save(fullfile(result_directory, 'fixed_ridge_coefficients.mat'), ...
    'fits', 'supports', 'identification_indices', 'ridge_metadata', '-v7.3');
save(fullfile(result_directory, 'ridge_full_signal_predictions.mat'), ...
    'target_full_signal', 'full_signal_indices', 'full_signal_ridge', ...
    'identification_indices', 'identification_ridge', ...
    'ridge_metadata', '-v7.3');

fprintf('\n');
disp(linear_ls_ridge_results(:, {'Model','RealParameters', ...
    'LSFullSignalNMSEdB','Ridge1e5FullSignalNMSEdB', ...
    'LSCoefficientL2','Ridge1e5CoefficientL2'}));
fprintf('Complex/coupled ridge relative error (full): %.3e\n', ...
    ridge_metadata.complexCoupledFullSignalRelativeError);
fprintf('Results: %s\n', result_directory);

function fit = fitIndependentFixedRidge( ...
    features, target, lambda, reduction, model_name)
% Fit both real outputs in one ridge solve using identification-only norms.
feature_norms = sqrt(sum(features.^2, 1)).';
if any(~isfinite(feature_norms)) || any(feature_norms <= 0)
    error('run_fixed_ridge_1e5_comparison:InvalidFeatureNorms', ...
        'Every retained feature must have a positive finite norm.');
end
features_normalized = features ./ feature_norms.';
target_matrix = [real(target(:)), imag(target(:))];
gram = features_normalized.' * features_normalized;
rhs = features_normalized.' * target_matrix;
coefficients_normalized = ...
    (gram + lambda*eye(size(gram))) \ rhs;
coefficients = coefficients_normalized ./ feature_norms;
fit = struct();
fit.modelName = char(model_name);
fit.lambda = lambda;
fit.solver = 'ridge 1e-5';
fit.coefficientsI = coefficients(:, 1);
fit.coefficientsQ = coefficients(:, 2);
fit.coefficientsINormalized = coefficients_normalized(:, 1);
fit.coefficientsQNormalized = coefficients_normalized(:, 2);
fit.featureNorms = feature_norms;
fit.gramNormalized = gram;
fit.gramConditionNumber = cond(gram);
fit.effectiveRealFeatures = size(features, 2);
fit.realParameters = 2*size(features, 2);
fit.coefficientMemoryBytes = 8*fit.realParameters;
fit.reduction = reduction;
end

function fit = mapComplexCoefficientsToCoupled( ...
    support, coefficients, population_size, norm_u, lambda)
% Map one complex coefficient vector to the exact coupled real form.
fit = struct();
fit.supportComplex = support(:);
fit.supportReal = [support(:); population_size + support(:)];
fit.hReal = [real(coefficients(:)); imag(coefficients(:))];
fit.hComplexRecovered = coefficients(:);
fit.normUComplex = norm_u(:);
fit.lambda = lambda;
fit.nComplexTotal = population_size;
fit.nActiveComplex = numel(support);
fit.nActiveReal = 2*numel(support);
end

function reduction = buildSelectedReduction(base_reduction, local_support)
% Preserve the frozen reduced-feature support without running selection.
local_support = double(local_support(:));
reduction = base_reduction;
reduction.keptIndices = base_reduction.keptIndices(local_support);
reduction.effectiveFeatureCount = numel(local_support);
reduction.groupSupportFeatures = local_support;
reduction.selectionMethod = 'frozen DOMP support';
end

function prediction = independentMatrixPrediction(features, fit, rotation)
prediction_phase_normalized = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
prediction = conj(rotation(:)) .* prediction_phase_normalized;
end

function prediction = coupledMatrixPrediction(U_phase, h_real, rotation)
n_rows = size(U_phase, 1);
U_real = [real(U_phase), -imag(U_phase); ...
    imag(U_phase), real(U_phase)];
prediction_real = U_real*h_real;
prediction_phase_normalized = prediction_real(1:n_rows) + ...
    1j*prediction_real(n_rows+1:end);
prediction = conj(rotation(:)) .* prediction_phase_normalized;
end

function values = structToOrderedCell(predictions)
values = {predictions.complexGMP; predictions.coupledPNIQ; ...
    predictions.independentPNIQ; predictions.complexParameterMatched; ...
    predictions.independentNoPN; predictions.independentPNIQReduced};
end

function verifyFrozenLS(reference_results, predictions, target)
model_names = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; ...
    "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; ...
    "Independent PN-IQ reduced DOMP"];
values = structToOrderedCell(predictions);
for index = 1:numel(model_names)
    row = reference_results.Model == model_names(index);
    reproduced = nmseComplexDb(target, values{index});
    frozen = reference_results.IdentificationNMSEdB(row);
    if abs(reproduced - frozen) > 1e-9
        error('run_fixed_ridge_1e5_comparison:LSReferenceChanged', ...
            'Reproduced LS differs for %s by %.3e dB.', ...
            model_names(index), abs(reproduced-frozen));
    end
end
end

function assertEquivalent(reference, candidate, target, domain)
prediction_error = relativeError(reference, candidate);
nmse_difference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if prediction_error >= 1e-10 || nmse_difference >= 1e-9
    error('run_fixed_ridge_1e5_comparison:CoupledEquivalenceFailed', ...
        ['Complex/coupled ridge equivalence failed on %s: ' ...
        'relative %.3e, NMSE difference %.3e dB.'], ...
        domain, prediction_error, nmse_difference);
end
end

function value = relativeError(reference, candidate)
value = norm(candidate-reference)/max(norm(reference), realmin);
end

function description = describeAdditionalOperations(row)
parts = strings(0, 1);
if row.NumAbsPerSample > 0
    parts(end+1) = sprintf('%d complex magnitudes', row.NumAbsPerSample);
end
if row.NumRealDivisionsPerSample > 0
    parts(end+1) = sprintf('%d divisions', row.NumRealDivisionsPerSample);
end
if row.NumELUPerSample > 0
    parts(end+1) = sprintf('%d ELU', row.NumELUPerSample);
end
if isempty(parts)
    description = "none";
else
    description = strjoin(parts, ', ');
end
end
