% Compare the natural fixed-ridge reference with the canonical linear sweep.
% The test reads existing signed artifacts and performs no DOMP or PNNN work.
% Complex GMP target 20 at lambda 1e-5 must reproduce the principal route.

clearvars;
projectRoot = fileparts(fileparts(mfilename('fullpath')));
resultsRoot = fullfile(projectRoot, 'results', 'parameter_sweep');
entries = dir(fullfile(resultsRoot, 'sweep_*'));
entries = entries([entries.isdir]);
[~, order] = sort([entries.datenum], 'descend');
artifactDirectory = "";
for index = order
    candidate = fullfile(entries(index).folder, entries(index).name);
    if isfile(fullfile(candidate, 'linear_sweep.mat')) && ...
            isfile(fullfile(candidate, 'fixed_lambda_linear_sweep.mat'))
        artifactDirectory = string(candidate);
        break;
    end
end
assert(strlength(artifactDirectory) > 0, ...
    'No complete signed parameter-sweep artifacts were found.');

linearArtifact = load(fullfile(artifactDirectory, ...
    'linear_sweep.mat'), 'checkpointArtifact');
fixedArtifact = load(fullfile(artifactDirectory, ...
    'fixed_lambda_linear_sweep.mat'), 'checkpointArtifact');
linear = linearArtifact.checkpointArtifact.payload;
fixed = fixedArtifact.checkpointArtifact.payload;

mainRows = linear.complexTable.TargetRealParameters == 20 & ...
    linear.complexTable.SelectedLambda == 1e-5;
fixedRows = string(fixed.table.Model) == "Complex GMP-DOMP" & ...
    fixed.table.TargetRealParameters == 20 & ...
    fixed.table.FixedLambda == 1e-5;
assert(nnz(mainRows) == 1 && nnz(fixedRows) == 1);
mainIndex = find(mainRows);
reference = fixed.reference;

supportEqual = isequal(linear.supports.complex{mainIndex}(:), ...
    reference.support(:));
parametersEqual = linear.complexTable.ActualRealParameters(mainRows) == ...
    fixed.table.ActualRealParameters(fixedRows) && ...
    reference.actualRealParameters == ...
    fixed.table.ActualRealParameters(fixedRows);
flopsEqual = linear.complexTable.FLOPsPerSample(mainRows) == ...
    fixed.table.FLOPsPerSample(fixedRows) && ...
    reference.flopsPerSample == fixed.table.FLOPsPerSample(fixedRows);
identificationNMSEDifference = abs( ...
    linear.complexTable.IdentificationNMSEdB(mainRows) - ...
    fixed.table.IdentificationNMSEdB(fixedRows));
fullSignalNMSEDifference = abs( ...
    linear.complexTable.FullSignalNMSEdB(mainRows) - ...
    fixed.table.FullSignalNMSEdB(fixedRows));
identificationPredictionError = relativeError( ...
    reference.identificationPrediction, ...
    linear.predictions.complexIdentification(:, mainIndex));
fullSignalPredictionError = relativeError(reference.fullSignalPrediction, ...
    linear.predictions.complexFull(:, mainIndex));

assert(reference.model == "Complex GMP-DOMP");
assert(reference.targetRealParameters == 20 && ...
    reference.fixedLambda == 1e-5);
assert(supportEqual && parametersEqual && flopsEqual);
assert(identificationNMSEDifference <= 1e-9);
assert(fullSignalNMSEDifference <= 1e-9);
assert(identificationPredictionError <= 1e-10);
assert(fullSignalPredictionError <= 1e-10);

fprintf('FIXED-LAMBDA EQUIVALENCE TEST: PASS\n');
fprintf('Identification NMSE difference: %.17g dB\n', ...
    identificationNMSEDifference);
fprintf('Full-signal NMSE difference: %.17g dB\n', ...
    fullSignalNMSEDifference);
fprintf('Identification prediction relative error: %.17g\n', ...
    identificationPredictionError);
fprintf('Full-signal prediction relative error: %.17g\n', ...
    fullSignalPredictionError);
fprintf('Support equal: %d; parameters equal: %d; FLOPs equal: %d\n', ...
    supportEqual, parametersEqual, flopsEqual);

function value = relativeError(actual, reference)
value = norm(actual(:) - reference(:))/max(norm(reference(:)), realmin);
end
