function signature = buildExperimentSignature(x, y, cfg)
% buildExperimentSignature - Hash measurement data and reuse-critical settings.
% The signature protects PNNN hyperparameter reuse from captures or model
% configurations that happen to produce identical split indices.

identity = configurationIdentity(cfg);

configurationText = jsonencode(identity);

xHash = hashNumericArray(x);
yHash = hashNumericArray(y);

configurationHash = hashText(configurationText);

digest = hashText(strjoin(["PNNN experiment signature v3", ...
    string(xHash), string(yHash), string(configurationHash)], "|"));

signature = struct( ...
    'schemaVersion', 3, ...
    'digest', string(digest), ...
    'xHash', string(xHash), ...
    'yHash', string(yHash));
end

function identity = configurationIdentity(cfg)
identity = struct( ...
    'mappingMode', string(cfg.mappingMode), ...
    'removeDC', logical(cfg.pnnn.removeDC), ...
    'identificationFraction', double(cfg.identificationFraction), ...
    'identificationSeed', double(cfg.identificationSeed), ...
    'internalTrainFraction', double(cfg.internalTrainFraction), ...
    'internalSplitSeed', double(cfg.internalSplitSeed), ...
    'amplitudeBinCount', double(cfg.amplitudeBinCount), ...
    'pnnnMemoryDepth', double(cfg.pnnn.M), ...
    'pnnnOrders', double(cfg.pnnn.orders(:).'), ...
    'pnnnFeatureMode', string(cfg.pnnn.featMode), ...
    'n12HiddenNeurons', double(cfg.pnnn.sparseBaseHiddenNeurons), ...
    'nnSeed', double(cfg.pnnn.nnSeed), ...
    'miniBatchSize', double(cfg.training.miniBatchSize), ...
    'optimizer', string(cfg.training.optimizer), ...
    'initialLearnRate', double(cfg.training.initialLearnRate), ...
    'learnRateSchedule', string(cfg.training.learnRateSchedule), ...
    'learnRateDropFactor', double(cfg.training.learnRateDropFactor), ...
    'shuffle', string(cfg.training.shuffle), ...
    'historicalTrainFraction', ...
        double(cfg.training.historicalTrainFraction), ...
    'historicalMaxEpochs', double(cfg.training.historicalMaxEpochs), ...
    'historicalLearnRateDropPeriod', ...
        double(cfg.training.historicalLearnRateDropPeriod), ...
    'historicalValidationPatience', ...
        double(cfg.training.historicalValidationPatience), ...
    'historicalFineTuneEpochs', ...
        double(cfg.pruning.historicalFineTuneEpochs), ...
    'fineTuneInitialLearnRate', ...
        double(cfg.pruning.fineTuneInitialLearnRate), ...
    'fineTuneSeedOffset', double(cfg.pruning.fineTuneSeedOffset));
end

function digestText = hashNumericArray(values)
digest = javaMethod('getInstance', 'java.security.MessageDigest', 'SHA-256');
updateDigest(digest, unicode2native(class(values), 'UTF-8'));
updateDigest(digest, numericBytes(uint64(size(values))));
updateDigest(digest, uint8(~isreal(values)));
updateDigest(digest, numericBytes(real(values(:))));

if ~isreal(values)
    updateDigest(digest, numericBytes(imag(values(:))));
end

digestText = finishDigest(digest);
end

function digestText = hashText(value)
digest = javaMethod('getInstance', 'java.security.MessageDigest', 'SHA-256');
updateDigest(digest, unicode2native(char(string(value)), 'UTF-8'));
digestText = finishDigest(digest);
end

function bytes = numericBytes(values)
[~, ~, endian] = computer;

if endian == 'B'
    values = swapbytes(values);
end
bytes = typecast(values(:), 'uint8');
end

function updateDigest(digest, bytes)
bytes = uint8(bytes(:));
digest.update(typecast(bytes, 'int8'));
end

function digestText = finishDigest(digest)
signedBytes = int8(digest.digest());
bytes = typecast(signedBytes(:), 'uint8');
digestText = lower(reshape(dec2hex(bytes, 2).', 1, []));
end
