function signature = buildExperimentSignature(x, y, cfg)
% buildExperimentSignature - Hash measurement data and reuse-critical settings.
% The signature protects PNNN hyperparameter reuse from captures or model
% configurations that happen to produce identical split indices.

validateInputs(x, y, cfg);
identity = configurationIdentity(cfg, numel(x), numel(y));
configurationText = jsonencode(identity);
xHash = hashNumericArray(x);
yHash = hashNumericArray(y);
configurationHash = hashText(configurationText);
digest = hashText(strjoin(["PNNN experiment signature v2", ...
    string(xHash), string(yHash), string(configurationHash)], "|"));

signature = struct( ...
    'schemaVersion', 2, ...
    'algorithm', "SHA-256", ...
    'digest', string(digest), ...
    'xHash', string(xHash), ...
    'yHash', string(yHash), ...
    'configurationHash', string(configurationHash), ...
    'configuration', identity);
end

function identity = configurationIdentity(cfg, xLength, yLength)
identity = struct( ...
    'measurementName', string(cfg.measurementName), ...
    'mappingMode', string(cfg.mappingMode), ...
    'xLength', double(xLength), ...
    'yLength', double(yLength), ...
    'removeDC', logical(cfg.pnnn.removeDC), ...
    'identificationFraction', double(cfg.identificationFraction), ...
    'identificationSeed', double(cfg.identificationSeed), ...
    'internalTrainFraction', double(cfg.internalTrainFraction), ...
    'internalSplitSeed', double(cfg.internalSplitSeed), ...
    'amplitudeBinCount', double(cfg.amplitudeBinCount), ...
    'pnnnMemoryDepth', double(cfg.pnnn.M), ...
    'pnnnOrders', double(cfg.pnnn.orders(:).'), ...
    'pnnnFeatureMode', string(cfg.pnnn.featMode), ...
    'pnnnActivation', string(cfg.pnnn.actType), ...
    'h4HiddenNeurons', double(cfg.pnnn.denseControlHiddenNeurons), ...
    'n12HiddenNeurons', double(cfg.pnnn.sparseBaseHiddenNeurons), ...
    'nnSeeds', double(cfg.pnnn.nnSeeds(:).'), ...
    'miniBatchSize', double(cfg.training.miniBatchSize), ...
    'optimizer', string(cfg.training.optimizer), ...
    'initialLearnRate', double(cfg.training.initialLearnRate), ...
    'learnRateSchedule', string(cfg.training.learnRateSchedule), ...
    'learnRateDropPeriod', double(cfg.training.learnRateDropPeriod), ...
    'learnRateDropFactor', double(cfg.training.learnRateDropFactor), ...
    'validationPatience', double(cfg.training.validationPatience), ...
    'shuffle', string(cfg.training.shuffle), ...
    'historicalTrainFraction', ...
        double(cfg.training.historicalTrainFraction), ...
    'historicalMaxEpochs', double(cfg.training.historicalMaxEpochs), ...
    'historicalLearnRateDropPeriod', ...
        double(cfg.training.historicalLearnRateDropPeriod), ...
    'historicalValidationPatience', ...
        double(cfg.training.historicalValidationPatience), ...
    'pruningTargetMode', string(cfg.pruning.targetMode), ...
    'pruningScope', string(cfg.pruning.scope), ...
    'pruningStructureMode', string(cfg.pruning.structureMode), ...
    'pruningIncludeBiases', logical(cfg.pruning.includeBiases), ...
    'pruningStructuredRanking', string(cfg.pruning.structuredRanking), ...
    'pruningStructuredTargetPolicy', ...
        string(cfg.pruning.structuredTargetPolicy), ...
    'pruningHybridExactTarget', logical(cfg.pruning.hybridExactTarget), ...
    'fineTuneEnabled', logical(cfg.pruning.fineTuneEnabled), ...
    'fineTuneEpochs', double(cfg.pruning.fineTuneEpochs), ...
    'historicalFineTuneEpochs', ...
        double(cfg.pruning.historicalFineTuneEpochs), ...
    'fineTuneInitialLearnRate', ...
        double(cfg.pruning.fineTuneInitialLearnRate), ...
    'fineTuneLearnRateDropPeriod', ...
        double(cfg.pruning.fineTuneLearnRateDropPeriod), ...
    'fineTuneSeedOffset', double(cfg.pruning.fineTuneSeedOffset), ...
    'pruningFreezePruned', logical(cfg.pruning.freezePruned));
end

function digestText = hashNumericArray(values)
digest = javaMethod('getInstance', ...
    'java.security.MessageDigest', 'SHA-256');
updateDigest(digest, unicode2native(class(values), 'UTF-8'));
updateDigest(digest, numericBytes(uint64(size(values))));
updateDigest(digest, uint8(~isreal(values)));
updateDigest(digest, numericBytes(real(values(:))));
if ~isreal(values)
    updateDigest(digest, numericBytes(imag(values(:))));
end
digestText = finishDigest(digest);
end

function digestText = hashText(value)
digest = javaMethod('getInstance', ...
    'java.security.MessageDigest', 'SHA-256');
updateDigest(digest, unicode2native(char(string(value)), 'UTF-8'));
digestText = finishDigest(digest);
end

function bytes = numericBytes(values)
[~, ~, endian] = computer;
if endian == 'B'
    values = swapbytes(values);
end
bytes = typecast(values(:), 'uint8');
end

function updateDigest(digest, bytes)
bytes = uint8(bytes(:));
digest.update(typecast(bytes, 'int8'));
end

function digestText = finishDigest(digest)
signedBytes = int8(digest.digest());
bytes = typecast(signedBytes(:), 'uint8');
digestText = lower(reshape(dec2hex(bytes, 2).', 1, []));
end

function validateInputs(x, y, cfg)
requiredTop = {'measurementName','mappingMode','identificationFraction', ...
    'identificationSeed','internalTrainFraction','internalSplitSeed', ...
    'amplitudeBinCount', ...
    'pnnn','training','pruning'};
requiredPNNN = {'M','orders','featMode','actType','removeDC', ...
    'denseControlHiddenNeurons','sparseBaseHiddenNeurons','nnSeeds'};
requiredTraining = {'miniBatchSize','optimizer','initialLearnRate', ...
    'learnRateSchedule','learnRateDropPeriod','learnRateDropFactor', ...
    'validationPatience','shuffle','historicalTrainFraction', ...
    'historicalMaxEpochs','historicalLearnRateDropPeriod', ...
    'historicalValidationPatience'};
requiredPruning = {'targetMode','scope','structureMode','includeBiases', ...
    'structuredRanking','structuredTargetPolicy','hybridExactTarget', ...
    'fineTuneEnabled','fineTuneEpochs','historicalFineTuneEpochs', ...
    'fineTuneInitialLearnRate','fineTuneLearnRateDropPeriod', ...
    'fineTuneSeedOffset','freezePruned'};
if ~isnumeric(x) || ~isnumeric(y) || isempty(x) || isempty(y) || ...
        any(~isfinite(x), 'all') || any(~isfinite(y), 'all') || ...
        ~isstruct(cfg) || ~all(isfield(cfg, requiredTop)) || ...
        ~all(isfield(cfg.pnnn, requiredPNNN)) || ...
        ~all(isfield(cfg.training, requiredTraining)) || ...
        ~all(isfield(cfg.pruning, requiredPruning))
    error('buildExperimentSignature:InvalidInput', ...
        'Finite signals and the complete reuse-critical configuration are required.');
end
end
