function points = fit_sparse_pnnn_target(denseSource, requestedTargets, ...
    features, targets, rotation, y, split, cfg)
% fit_sparse_pnnn_target - Fit independent sparse N12 points.
% Every target starts from the same immutable dense source; biases stay
% protected and the shared fine-tuning budget is reused without reselection.

requestedTargets = double(requestedTargets(:));

referenceSignature = denseSource.signature;
if ~isequaln(buildNetworkSignature(denseSource.denseFit), referenceSignature)
    error('fit_sparse_pnnn_target:DenseSourceChanged', ...
        'Every sparse target must start from the same immutable dense source.');
end

template = struct('target', [], 'row', table(), 'mask', {{}}, ...
    'pruningStats', struct(), 'maskIntegrityAfterPruning', struct(), ...
    'maskIntegrityAfterFineTune', struct(), ...
    'identificationPrediction', complex([]), ...
    'fullSignalPrediction', complex([]), ...
    'denseSourceSignature', struct(), 'elapsedTimeSeconds', NaN);
points = repmat(template, numel(requestedTargets), 1);
schema = cfg.sweep.resultSchema;

%% Prune, refit, predict, and count each independent target
% refitFairPNNNSparse contains the mathematical pruning and frozen-mask update.
for targetIndex = 1:numel(requestedTargets)
    target = requestedTargets(targetIndex);
    timer = tic;
    fit = refitFairPNNNSparse(denseSource.denseFit, features, targets, ...
        rotation, y, split.identificationIndices, split.fullSignalIndices, ...
        target, cfg.pnnn.nnSeeds(1), denseSource.fineTuneEpochs, ...
        denseSource.runtimeConfig);
    if ~isequaln(buildNetworkSignature(denseSource.denseFit), referenceSignature)
        error('fit_sparse_pnnn_target:DenseSourceChanged', ...
            'A sparse fit modified the immutable dense source.');
    end

    flops = countSparsePNNNFLOPs("Sparse PNNN N12", ...
        size(features, 2), cfg.pnnn.sparseBaseHiddenNeurons, ...
        cfg.pnnn.M, cfg.pnnn.orders, fit.activeWeights, fit.activeBiases);
    elapsed = toc(timer);
    values = {"Sparse PNNN N12", "Sweep point", target, ...
        double(fit.actualActiveParams), "Not applicable", NaN, NaN, ...
        double(fit.identificationNMSEdB), double(fit.fullSignalNMSEdB), ...
        double(flops.FLOPsPerSample), double(fit.activeWeights), ...
        double(fit.activeBiases), double(fit.weightSparsityPercent), ...
        string(referenceSignature.digest), NaN, NaN, NaN, ...
        double(fit.bestFineTuneEpoch), ...
        string(denseSource.fineTuneBudgetSource), ...
        double(fit.maskIntegrityAfterPruning.ok), ...
        double(fit.maskIntegrityAfterFineTune.ok), elapsed, ""};

    points(targetIndex).target = target;
    points(targetIndex).row = ...
        cell2table(values, 'VariableNames', schema.names);
    points(targetIndex).mask = fit.pruningState.masks;
    points(targetIndex).pruningStats = fit.pruningStats;
    points(targetIndex).maskIntegrityAfterPruning = ...
        fit.maskIntegrityAfterPruning;
    points(targetIndex).maskIntegrityAfterFineTune = ...
        fit.maskIntegrityAfterFineTune;
    points(targetIndex).identificationPrediction = ...
        fit.identificationPrediction;
    points(targetIndex).fullSignalPrediction = fit.fullSignalPrediction;
    points(targetIndex).denseSourceSignature = referenceSignature;
    points(targetIndex).elapsedTimeSeconds = elapsed;
end
end
