function points = fit_sparse_pnnn_target(denseSource, requestedTargets, ...
    features, targets, rotation, y, split, cfg)
% fit_sparse_pnnn_target - Prune one immutable N12 dense source per target.
% Targets are independent, biases remain protected, and one shared
% fine-tuning budget is reused without target-specific validation claims.

validateInputs(denseSource, requestedTargets, features, targets, ...
    rotation, y, split, cfg);
referenceSignature = denseSource.signature;
assertDenseSignature(denseSource.denseFit, referenceSignature);
requestedTargets = double(requestedTargets(:));
points = repmat(emptyPoint(), numel(requestedTargets), 1);
for index = 1:numel(requestedTargets)
    target = requestedTargets(index);
    timer = tic;
    fit = refitFairPNNNSparse(denseSource.denseFit, features, targets, ...
        rotation, y, split.identificationIndices, split.fullSignalIndices, ...
        target, cfg.pnnn.nnSeeds(1), denseSource.fineTuneEpochs, ...
        denseSource.runtimeConfig);
    assertDenseSignature(denseSource.denseFit, referenceSignature);
    flops = countSparsePNNNFLOPs("Sparse PNNN N12", ...
        size(features, 2), cfg.pnnn.sparseBaseHiddenNeurons, ...
        cfg.pnnn.M, cfg.pnnn.orders, fit.activeWeights, fit.activeBiases);
    elapsed = toc(timer);
    points(index) = packagePoint(fit, flops, target, elapsed, ...
        referenceSignature, denseSource.fineTuneBudgetSource, cfg);
end
end

function point = packagePoint(fit, flops, target, elapsed, ...
    denseSignature, budgetSource, cfg)
schema = cfg.sweep.resultSchema;
values = {"Sparse PNNN N12", "Sweep point", target, ...
    double(fit.actualActiveParams), "Not applicable", NaN, NaN, ...
    double(fit.identificationNMSEdB), double(fit.fullSignalNMSEdB), ...
    double(flops.FLOPsPerSample), double(fit.activeWeights), ...
    double(fit.activeBiases), double(fit.weightSparsityPercent), ...
    string(denseSignature.digest), NaN, NaN, NaN, ...
    double(fit.bestFineTuneEpoch), string(budgetSource), ...
    double(fit.maskIntegrityAfterPruning.ok), ...
    double(fit.maskIntegrityAfterFineTune.ok), elapsed, ""};
point = emptyPoint();
point.target = target;
point.row = cell2table(values, 'VariableNames', schema.names);
point.mask = fit.pruningState.masks;
point.pruningStats = fit.pruningStats;
point.maskIntegrityAfterPruning = fit.maskIntegrityAfterPruning;
point.maskIntegrityAfterFineTune = fit.maskIntegrityAfterFineTune;
point.identificationPrediction = fit.identificationPrediction;
point.fullSignalPrediction = fit.fullSignalPrediction;
point.denseSourceSignature = denseSignature;
point.elapsedTimeSeconds = elapsed;
end

function point = emptyPoint()
point = struct('target', [], 'row', table(), 'mask', {{}}, ...
    'pruningStats', struct(), 'maskIntegrityAfterPruning', struct(), ...
    'maskIntegrityAfterFineTune', struct(), ...
    'identificationPrediction', complex([]), ...
    'fullSignalPrediction', complex([]), ...
    'denseSourceSignature', struct(), 'elapsedTimeSeconds', NaN);
end

function assertDenseSignature(denseFit, expected)
actual = buildNetworkSignature(denseFit);
if ~isequaln(actual, expected)
    error('fit_sparse_pnnn_target:DenseSourceChanged', ...
        'Every sparse target must start from the same immutable dense source.');
end
end

function validateInputs(denseSource, requestedTargets, features, targets, ...
    rotation, y, split, cfg)
requiredDense = {'denseFit','signature','fineTuneEpochs', ...
    'fineTuneBudgetSource','runtimeConfig'};
requiredSplit = {'identificationIndices','fullSignalIndices'};
n = size(features, 1);
if ~isstruct(denseSource) || ~all(isfield(denseSource, requiredDense)) || ...
        ~isnumeric(features) || ~isreal(features) || isempty(features) || ...
        any(~isfinite(features), 'all') || size(targets, 1) ~= n || ...
        size(targets, 2) ~= 2 || ~isreal(targets) || ...
        any(~isfinite(targets), 'all') || numel(rotation) ~= n || ...
        numel(y) ~= n || any(~isfinite(rotation)) || any(~isfinite(y)) || ...
        ~isstruct(split) || ~all(isfield(split, requiredSplit))
    error('fit_sparse_pnnn_target:InvalidInput', ...
        'A dense source, aligned finite arrays, and the shared split are required.');
end
validateattributes(requestedTargets, {'numeric'}, ...
    {'vector','integer','positive','finite'});
if isempty(requestedTargets) || ...
        numel(unique(requestedTargets)) ~= numel(requestedTargets) || ...
        ~isfield(cfg, 'sweep') || ...
        ~isfield(cfg.sweep, 'resultSchema')
    error('fit_sparse_pnnn_target:InvalidTargets', ...
        'At least one target and the canonical result schema are required.');
end
end
