function fit = fitFairPNNNDenseValidation( ...
    features, targets, phaseRotation, y, trainingRows, validationRows, ...
    fitPoolRows, hiddenNeurons, nnSeed, cfg)
% fitFairPNNNDenseValidation - Train one dense PNNN on TRAIN and VAL.
% Normalization is derived only from TRAIN and the returned network is the
% best VAL checkpoint. TEST rows are not accepted by this function.

validateInputs(features, targets, phaseRotation, y, trainingRows, ...
    validationRows, fitPoolRows, hiddenNeurons, nnSeed, cfg);
timer = tic;
input_dimension = size(features, 2);

normalization = computePNNNNormalization( ...
    features(trainingRows, :), targets(trainingRows, :));
features_training = normalizeFeatures(features(trainingRows, :), ...
    normalization);
features_validation = normalizeFeatures(features(validationRows, :), ...
    normalization);
targets_training = normalizeTargets(targets(trainingRows, :), ...
    normalization);
targets_validation = normalizeTargets(targets(validationRows, :), ...
    normalization);

iterations_per_epoch = max(1, floor(numel(trainingRows) / ...
    cfg.miniBatchSize));
rng(nnSeed, 'twister');
layers = buildFairPNNNLayers(input_dimension, hiddenNeurons);
options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=cfg.maxEpochs, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="best-validation-loss", ...
    ValidationData={features_validation, targets_validation}, ...
    ValidationFrequency=iterations_per_epoch, ...
    ValidationPatience=cfg.validationPatience, ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots=cfg.trainingPlots, ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=iterations_per_epoch);
[network, training_info] = trainnet(features_training, targets_training, ...
    layers, "mse", options);

training_summary = summarizeTrainingInfo( ...
    training_info, iterations_per_epoch, cfg.maxEpochs);
parameter_count = countPNNNParameters(input_dimension, hiddenNeurons);
learnable_count = summarizeTrainableParameters(network, false);
if learnable_count.totalTrainableParams ~= parameter_count.realParameters
    error('fitFairPNNNDenseValidation:ParameterCountMismatch', ...
        'The initialized network does not match H*(D+3)+2.');
end

fit = struct();
fit.network = network;
fit.normalization = normalization;
fit.hiddenNeurons = double(hiddenNeurons);
fit.nnSeed = double(nnSeed);
fit.parameterCount = parameter_count;
fit.targetActiveParams = NaN;
fit.actualActiveParams = parameter_count.realParameters;
fit.activeWeights = parameter_count.realWeights;
fit.activeBiases = parameter_count.realBiases;
fit.weightSparsityPercent = 0;
fit.iterationsPerEpoch = iterations_per_epoch;
fit.denseTrainingUpdates = training_summary.trainingIterations;
fit.fineTuneUpdates = 0;
fit.bestDenseEpoch = training_summary.bestEpoch;
fit.bestFineTuneEpoch = NaN;
fit.bestEpoch = training_summary.bestEpoch;
fit.trainNMSEdB = predictNMSE(network, features, phaseRotation, y, ...
    trainingRows, normalization);
fit.validationNMSEdB = predictNMSE(network, features, phaseRotation, y, ...
    validationRows, normalization);
fit.fitPoolNMSEdB = predictNMSE(network, features, phaseRotation, y, ...
    fitPoolRows, normalization);
fit.trainingInfoSummary = training_summary;
fit.selectionContract = struct( ...
    'trainingRows', numel(trainingRows), ...
    'validationRows', numel(validationRows), ...
    'fitPoolRows', numel(fitPoolRows), ...
    'testRowsUsed', false, ...
    'normalizationDomain', "TRAIN", ...
    'checkpointDomain', "VAL");
fit.trainingTimeSeconds = toc(timer);
end

function value = predictNMSE(network, features, rotation, y, rows, stats)
features_normalized = normalizeFeatures(features(rows, :), stats);
prediction = predictPhaseNorm(network, features_normalized, stats, ...
    rotation(rows));
value = nmseComplexDb(y(rows), prediction);
end

function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end

function summary = summarizeTrainingInfo(info, iterationsPerEpoch, maxEpochs)
if ~(isprop(info, 'TrainingHistory') || ...
        (isstruct(info) && isfield(info, 'TrainingHistory'))) || ...
        ~(isprop(info, 'ValidationHistory') || ...
        (isstruct(info) && isfield(info, 'ValidationHistory')))
    error('fitFairPNNNDenseValidation:MissingTrainingHistory', ...
        'trainnet did not return training and validation histories.');
end
training_history = info.TrainingHistory;
validation_history = info.ValidationHistory;
if isempty(training_history) || isempty(validation_history)
    error('fitFairPNNNDenseValidation:EmptyTrainingHistory', ...
        'trainnet returned an empty training history.');
end
training_iterations = double(training_history.Iteration(end));
validation_loss = double(validation_history.Loss);
validation_iteration = double(validation_history.Iteration);
eligible = isfinite(validation_loss) & isfinite(validation_iteration);
if ~any(eligible)
    error('fitFairPNNNDenseValidation:InvalidValidationHistory', ...
        'Validation history contains no finite loss.');
end
eligible_indices = find(eligible);
[best_validation_loss, local_index] = min(validation_loss(eligible));
best_iteration = validation_iteration(eligible_indices(local_index));

summary = struct();
summary.trainingIterations = training_iterations;
summary.finalTrainingLoss = double(training_history.Loss(end));
summary.bestValidationLoss = best_validation_loss;
summary.bestIteration = best_iteration;
summary.bestEpoch = min(maxEpochs, max(1, ...
    ceil(best_iteration/iterationsPerEpoch)));
end

function validateInputs(features, targets, rotation, y, trainingRows, ...
    validationRows, fitPoolRows, hiddenNeurons, nnSeed, cfg)
n = size(features, 1);
if ~isnumeric(features) || ~isreal(features) || isempty(features) || ...
        any(~isfinite(features), 'all') || size(targets, 1) ~= n || ...
        size(targets, 2) ~= 2 || ~isreal(targets) || ...
        any(~isfinite(targets), 'all') || numel(rotation) ~= n || ...
        numel(y) ~= n || any(~isfinite(rotation)) || any(~isfinite(y))
    error('fitFairPNNNDenseValidation:InvalidData', ...
        'Features, targets, rotations, and complex targets are invalid.');
end
validateattributes(hiddenNeurons, {'numeric'}, ...
    {'scalar','integer','positive','finite'});
validateattributes(nnSeed, {'numeric'}, ...
    {'scalar','integer','nonnegative','finite'});
row_sets = {trainingRows, validationRows, fitPoolRows};
for index = 1:numel(row_sets)
    rows = row_sets{index};
    validateattributes(rows, {'numeric'}, ...
        {'vector','integer','positive','finite','<=',n});
end
if ~isempty(intersect(trainingRows, validationRows)) || ...
        ~isequal(sort([trainingRows(:); validationRows(:)]), ...
        sort(fitPoolRows(:)))
    error('fitFairPNNNDenseValidation:InvalidSelectionRows', ...
        'TRAIN and VAL must be disjoint and their union must be FIT_POOL.');
end
required_cfg = {'optimizer','maxEpochs','miniBatchSize', ...
    'initialLearnRate','learnRateSchedule','learnRateDropPeriod', ...
    'learnRateDropFactor','validationPatience','shuffle', ...
    'executionEnvironment','trainingPlots','verbose', ...
    'inputDataFormats','targetDataFormats'};
if ~isstruct(cfg) || ~all(isfield(cfg, required_cfg))
    error('fitFairPNNNDenseValidation:IncompleteConfiguration', ...
        'The dense training configuration is incomplete.');
end
end
