function fit = fitFairPNNNTwoStage( ...
    features, targets, phaseRotation, y, split, hiddenNeurons, nnSeed, cfg)
% fitFairPNNNTwoStage - Train PNNN with TRAIN/VAL epoch selection and refit.
% A fresh network and FIT_POOL-only normalization are used for the exact
% best-epoch final fit; TEST is predicted only after that fit is complete.

validateInputs(features, targets, phaseRotation, y, split, ...
    hiddenNeurons, nnSeed);
timer = tic;
input_dimension = size(features, 2);

train_rows = split.TRAIN;
validation_rows = split.VAL;
fit_pool_rows = split.FIT_POOL;
test_rows = split.TEST;

selection_stats = computePNNNNormalization( ...
    features(train_rows, :), targets(train_rows, :));
features_train = normalizeFeatures(features(train_rows, :), selection_stats);
features_validation = normalizeFeatures( ...
    features(validation_rows, :), selection_stats);
targets_train = normalizeTargets(targets(train_rows, :), selection_stats);
targets_validation = normalizeTargets( ...
    targets(validation_rows, :), selection_stats);

rng(nnSeed, 'twister');
selection_layers = buildFairPNNNLayers(input_dimension, hiddenNeurons);
iterations_per_epoch = max(1, floor(numel(train_rows) / ...
    cfg.miniBatchSize));
selection_options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=cfg.maxEpochs, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="best-validation-loss", ...
    ValidationData={features_validation, targets_validation}, ...
    ValidationFrequency=iterations_per_epoch, ...
    ValidationPatience=cfg.validationPatience, ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots=cfg.trainingPlots, ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=iterations_per_epoch);
[selection_network, selection_info] = trainnet( ...
    features_train, targets_train, selection_layers, "mse", ...
    selection_options);
best_epoch = extractBestEpoch(selection_info, iterations_per_epoch, ...
    cfg.maxEpochs);

yhat_train = predictPhaseNorm(selection_network, features_train, ...
    selection_stats, phaseRotation(train_rows));
yhat_validation = predictPhaseNorm(selection_network, ...
    features_validation, selection_stats, phaseRotation(validation_rows));
train_nmse = checkedNMSE(y(train_rows), yhat_train);
validation_nmse = checkedNMSE(y(validation_rows), yhat_validation);

final_stats = computePNNNNormalization( ...
    features(fit_pool_rows, :), targets(fit_pool_rows, :));
features_fit_pool = normalizeFeatures( ...
    features(fit_pool_rows, :), final_stats);
targets_fit_pool = normalizeTargets(targets(fit_pool_rows, :), final_stats);
features_test = normalizeFeatures(features(test_rows, :), final_stats);

rng(nnSeed, 'twister');
final_layers = buildFairPNNNLayers(input_dimension, hiddenNeurons);
final_options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=best_epoch, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="last-iteration", ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots=cfg.trainingPlots, ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=max(1, floor(numel(fit_pool_rows) / ...
        cfg.miniBatchSize)));
[final_network, final_info] = trainnet( ...
    features_fit_pool, targets_fit_pool, final_layers, "mse", ...
    final_options);

yhat_fit_pool = predictPhaseNorm(final_network, features_fit_pool, ...
    final_stats, phaseRotation(fit_pool_rows));
yhat_test = predictPhaseNorm(final_network, features_test, ...
    final_stats, phaseRotation(test_rows));
fit_pool_nmse = checkedNMSE(y(fit_pool_rows), yhat_fit_pool);
test_nmse = checkedNMSE(y(test_rows), yhat_test);

parameter_count = countPNNNParameters(input_dimension, hiddenNeurons);
fit = struct();
fit.hiddenNeurons = hiddenNeurons;
fit.nnSeed = nnSeed;
fit.parameterCount = parameter_count;
fit.bestEpoch = best_epoch;
fit.trainNMSEdB = train_nmse;
fit.validationNMSEdB = validation_nmse;
fit.fitPoolNMSEdB = fit_pool_nmse;
fit.testNMSEdB = test_nmse;
fit.testPrediction = yhat_test;
fit.selectionNormalization = selection_stats;
fit.finalNormalization = final_stats;
fit.selectionInfoSummary = summarizeTrainingInfo(selection_info);
fit.finalInfoSummary = summarizeTrainingInfo(final_info);
fit.trainingTimeSeconds = toc(timer);
end

function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end

function epoch = extractBestEpoch(info, iterations_per_epoch, maximum_epochs)
if ~(isprop(info, 'ValidationHistory') || ...
        (isstruct(info) && isfield(info, 'ValidationHistory')))
    error('fitFairPNNNTwoStage:MissingValidationHistory', ...
        'trainnet did not return ValidationHistory.');
end
history = info.ValidationHistory;
loss = double(history.Loss);
iteration = double(history.Iteration);
eligible = isfinite(loss) & isfinite(iteration);
if ~any(eligible)
    error('fitFairPNNNTwoStage:InvalidValidationHistory', ...
        'ValidationHistory contains no finite loss.');
end
eligible_indices = find(eligible);
[~, local_best] = min(loss(eligible));
best_iteration = iteration(eligible_indices(local_best));
epoch = min(maximum_epochs, max(1, ...
    ceil(best_iteration / iterations_per_epoch)));
end

function summary = summarizeTrainingInfo(info)
summary = struct();
if isprop(info, 'TrainingHistory') || ...
        (isstruct(info) && isfield(info, 'TrainingHistory'))
    history = info.TrainingHistory;
    summary.trainingIterations = double(history.Iteration(end));
    summary.finalTrainingLoss = double(history.Loss(end));
else
    summary.trainingIterations = NaN;
    summary.finalTrainingLoss = NaN;
end
if isprop(info, 'ValidationHistory') || ...
        (isstruct(info) && isfield(info, 'ValidationHistory'))
    history = info.ValidationHistory;
    if ~istable(history) || ...
            ~ismember('Loss', history.Properties.VariableNames) || ...
            isempty(history)
        summary.bestValidationLoss = NaN;
    else
        finite_loss = double(history.Loss);
        finite_loss = finite_loss(isfinite(finite_loss));
        if isempty(finite_loss)
            summary.bestValidationLoss = NaN;
        else
            summary.bestValidationLoss = min(finite_loss);
        end
    end
else
    summary.bestValidationLoss = NaN;
end
end

function value = checkedNMSE(target, prediction)
value = nmseComplexDb(target, prediction);
target = double(target(:));
prediction = double(prediction(:));
legacy_value = 20*log10(norm(prediction-target, 2) / ...
    max(norm(target, 2), realmin));
if abs(value-legacy_value) > 1e-10
    error('fitFairPNNNTwoStage:NMSEDefinitionMismatch', ...
        ['The shared and historical complex NMSE formulas disagree by ' ...
         '%.3e dB.'], abs(value-legacy_value));
end
end

function validateInputs(features, targets, rotation, y, split, hidden, seed)
n = size(features, 1);
if ~isreal(features) || any(~isfinite(features), 'all') || ...
        size(targets, 1) ~= n || size(targets, 2) ~= 2 || ...
        ~isreal(targets) || any(~isfinite(targets), 'all') || ...
        numel(rotation) ~= n || numel(y) ~= n || ...
        any(~isfinite(rotation)) || any(~isfinite(y))
    error('fitFairPNNNTwoStage:InvalidData', ...
        'PNNN features, targets, rotations, and complex target are invalid.');
end
validateattributes(hidden, {'numeric'}, ...
    {'scalar','integer','positive','finite'});
validateattributes(seed, {'numeric'}, ...
    {'scalar','integer','nonnegative','finite'});
required = {'TRAIN','VAL','FIT_POOL','TEST'};
if ~isstruct(split) || ~all(isfield(split, required))
    error('fitFairPNNNTwoStage:InvalidSplit', ...
        'The common split is incomplete.');
end
end
