function fit = fitFairPNNNDenseValidation( ...
    features, targets, trainingRows, validationRows, ...
    hiddenNeurons, nnSeed, cfg)
% fitFairPNNNDenseValidation - Select the dense PNNN epoch on validation.

normalization = computePNNNNormalization( ...
    features(trainingRows, :), targets(trainingRows, :));
featuresTraining = normalizeFeatures(features(trainingRows, :), normalization);
featuresValidation = normalizeFeatures( ...
    features(validationRows, :), normalization);
targetsTraining = normalizeTargets(targets(trainingRows, :), normalization);
targetsValidation = normalizeTargets( ...
    targets(validationRows, :), normalization);

iterationsPerEpoch = max(1, ceil(numel(trainingRows) / cfg.miniBatchSize));
rng(nnSeed, 'twister');
layers = buildFairPNNNLayers(size(features, 2), hiddenNeurons);
options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=cfg.maxEpochs, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="best-validation-loss", ...
    ValidationData={featuresValidation, targetsValidation}, ...
    ValidationFrequency=iterationsPerEpoch, ...
    ValidationPatience=cfg.validationPatience, ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots="none", ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=iterationsPerEpoch);
[network, info] = trainnet( ...
    featuresTraining, targetsTraining, layers, "mse", options);

parameterCount = countPNNNParameters(size(features, 2), hiddenNeurons);
counts = summarizeTrainableParameters(network);
if counts.totalWeightParams + counts.totalBiasParams ~= ...
        parameterCount.realParameters
    error('fitFairPNNNDenseValidation:ParameterCountMismatch', ...
        'The initialized network does not match H*(D+3)+2.');
end

fit = struct('network', network, 'normalization', normalization, ...
    'bestDenseEpoch', selectBestEpoch(info, iterationsPerEpoch, cfg.maxEpochs));
end

function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end

function epoch = selectBestEpoch(info, iterationsPerEpoch, maxEpochs)
history = info.ValidationHistory;
loss = double(history.Loss);
iteration = double(history.Iteration);
eligible = isfinite(loss) & isfinite(iteration);
if ~any(eligible)
    error('fitFairPNNNDenseValidation:InvalidValidationHistory', ...
        'Validation history contains no finite loss.');
end
indices = find(eligible);
[~, localIndex] = min(loss(eligible));
epoch = min(maxEpochs, max(1, ...
    ceil(iteration(indices(localIndex))/iterationsPerEpoch)));
end
