function [matches, reason] = isReusablePNNNSelection( ...
    savedSplit, savedConfig, currentSplit, currentSignature, ...
    savedTargetActiveParams, currentTargetActiveParams)
% isReusablePNNNSelection - Validate saved PNNN selection artifacts.
% Reuse requires identical experiment signatures and identical internal
% train, internal validation, and identification row indices.

matches = false;
if nargin < 6
    savedTargetActiveParams = [];
    currentTargetActiveParams = [];
end
reason = "missing required split indices";
savedNames = {'internal_train_indices','internal_validation_indices', ...
    'identification_indices'};
currentNames = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices'};
if ~isstruct(savedSplit) || ~isstruct(currentSplit) || ...
        ~all(isfield(savedSplit, savedNames)) || ...
        ~all(isfield(currentSplit, currentNames))
    return;
end

reason = "missing experiment signature";
if ~isstruct(savedConfig) || ...
        ~isfield(savedConfig, 'experiment_signature') || ...
        ~validSignature(savedConfig.experiment_signature) || ...
        ~validSignature(currentSignature)
    return;
end

reason = "experiment signature mismatch";
if savedConfig.experiment_signature.schemaVersion ~= ...
        currentSignature.schemaVersion || ...
        string(savedConfig.experiment_signature.algorithm) ~= ...
        string(currentSignature.algorithm) || ...
        string(savedConfig.experiment_signature.digest) ~= ...
        string(currentSignature.digest)
    return;
end

reason = "split index mismatch";
for index = 1:numel(savedNames)
    if ~isequal(savedSplit.(savedNames{index})(:), ...
            currentSplit.(currentNames{index})(:))
        return;
    end
end

reason = "sparse target mismatch";
if ~isempty(savedTargetActiveParams) || ~isempty(currentTargetActiveParams)
    if ~isscalar(savedTargetActiveParams) || ...
            ~isscalar(currentTargetActiveParams) || ...
            ~isfinite(savedTargetActiveParams) || ...
            ~isfinite(currentTargetActiveParams) || ...
            double(savedTargetActiveParams) ~= ...
            double(currentTargetActiveParams)
        return;
    end
end

matches = true;
reason = "compatible";
end

function valid = validSignature(signature)
valid = isstruct(signature) && isscalar(signature) && ...
    all(isfield(signature, {'schemaVersion','algorithm','digest'})) && ...
    isscalar(signature.schemaVersion) && ...
    strlength(string(signature.algorithm)) > 0 && ...
    strlength(string(signature.digest)) > 0;
end
