function study = prepare_pnnn_dense_source( ...
    x, y, split, cfg, targetActiveParameters)
% prepare_pnnn_dense_source - Select and refit the shared dense N12 PNNN.
% Internal validation selects the dense and fine-tuning epochs once.
% The final dense source uses every identification sample.

%% Build the phase-normalized neural dataset
% These features are shared by dense selection, final refit, and all targets.
[features, neuralTargets, phaseRotation] = buildPhaseNormDataset( ...
    x, y, cfg.pnnn.M, cfg.pnnn.orders, cfg.pnnn.featMode);
features = features.';
neuralTargets = neuralTargets.';
phaseRotation = phaseRotation(:);
inputDimension = size(features, 2);
hiddenNeurons = cfg.pnnn.sparseBaseHiddenNeurons;
seed = cfg.pnnn.nnSeeds(1);

%% Scale the established training budget to the current split
budget = scalePNNNTrainingBudget(numel(x), ...
    numel(split.internalTrainIndices), cfg.training, cfg.pruning);
runtimeConfig = cfg;
runtimeConfig.training.maxEpochs = budget.denseMaxEpochs;
runtimeConfig.training.learnRateDropPeriod = ...
    budget.denseLearnRateDropPeriod;
runtimeConfig.training.validationPatience = budget.denseValidationPatience;
runtimeConfig.pruning.targetActiveTrainableParams = targetActiveParameters;
runtimeConfig.pruning.fineTuneEpochs = budget.fineTuneEpochs;
runtimeConfig.pruning.fineTuneLearnRateDropPeriod = ...
    budget.fineTuneLearnRateDropPeriod;

%% Select the dense and fine-tuning epochs on internal validation
denseValidationFit = fitFairPNNNDenseValidation( ...
    features, neuralTargets, phaseRotation, y, ...
    split.internalTrainIndices, split.internalValidationIndices, ...
    split.identificationIndices, hiddenNeurons, seed, ...
    runtimeConfig.training);
sparseValidationFit = pruneAndFineTuneFairPNNN( ...
    denseValidationFit, features, neuralTargets, phaseRotation, y, ...
    split.internalTrainIndices, split.internalValidationIndices, ...
    split.identificationIndices, targetActiveParameters, seed, ...
    runtimeConfig);
selection = struct('reused', false, 'source', "new internal selection", ...
    'n12Dense', selectedSummary(denseValidationFit), ...
    'n12Sparse', selectedSummary(sparseValidationFit));
fprintf('Selected epochs N12/fine-tune: %d / %d\n', ...
    selection.n12Dense.bestDenseEpoch, ...
    selection.n12Sparse.bestFineTuneEpoch);

%% Refit one immutable dense N12 source on identification
fprintf('Final N12 dense refit on all identification rows...\n');
denseFit = refitFairPNNNDense(features, neuralTargets, phaseRotation, y, ...
    split.identificationIndices, split.fullSignalIndices, hiddenNeurons, ...
    seed, selection.n12Dense.bestDenseEpoch, runtimeConfig.training);

study = struct('selection', selection, 'budget', budget, ...
    'runtimeConfig', runtimeConfig, 'inputDimension', inputDimension, ...
    'features', features, 'targets', neuralTargets, ...
    'rotation', phaseRotation, 'n12DenseFit', denseFit);
end

function summary = selectedSummary(fit)
summary = struct('bestDenseEpoch', fit.bestDenseEpoch, ...
    'bestFineTuneEpoch', fit.bestFineTuneEpoch, ...
    'internalTrainNMSEdB', fit.trainNMSEdB, ...
    'internalValidationNMSEdB', fit.validationNMSEdB);
if isnan(summary.bestFineTuneEpoch)
    summary.bestFineTuneEpoch = 0;
end
end
