function [denseSource, features, neuralTargets, phaseRotation] = ...
    prepare_pnnn_dense_source( ...
    x, y, split, cfg, targetActiveParameters)
% prepare_pnnn_dense_source - Select and refit the shared dense N12 PNNN.
% Internal validation selects the dense and fine-tuning epochs once.

[features, neuralTargets, phaseRotation] = buildPhaseNormDataset( ...
    x, y, cfg.pnnn.M, cfg.pnnn.orders, cfg.pnnn.featMode);

features = features.';
neuralTargets = neuralTargets.';
phaseRotation = phaseRotation(:);
hiddenNeurons = cfg.pnnn.sparseBaseHiddenNeurons;
seed = cfg.pnnn.nnSeed;

budget = scalePNNNTrainingBudget( ...
    numel(x), numel(split.internalTrainIndices), ...
    cfg.training, cfg.pruning);
runtimeConfig = struct('training', cfg.training, 'pruning', cfg.pruning);
runtimeConfig.training.maxEpochs = budget.denseMaxEpochs;
runtimeConfig.training.learnRateDropPeriod = ...
    budget.denseLearnRateDropPeriod;
runtimeConfig.training.validationPatience = budget.denseValidationPatience;
runtimeConfig.pruning.fineTuneEpochs = budget.fineTuneEpochs;
runtimeConfig.pruning.fineTuneLearnRateDropPeriod = ...
    budget.fineTuneLearnRateDropPeriod;

denseValidationFit = fitFairPNNNDenseValidation( ...
    features, neuralTargets, split.internalTrainIndices, ...
    split.internalValidationIndices, hiddenNeurons, seed, ...
    runtimeConfig.training);
bestFineTuneEpoch = pruneAndFineTuneFairPNNN( ...
    denseValidationFit, features, neuralTargets, ...
    split.internalTrainIndices, split.internalValidationIndices, ...
    targetActiveParameters, seed, runtimeConfig);

fprintf('Selected epochs N12/fine-tune: %d / %d\n', ...
    denseValidationFit.bestDenseEpoch, bestFineTuneEpoch);

fprintf('Final N12 dense refit on all identification rows...\n');
denseFit = refitFairPNNNDense(features, neuralTargets, ...
    split.identificationIndices, hiddenNeurons, seed, ...
    denseValidationFit.bestDenseEpoch, runtimeConfig.training);

sparseRuntimeConfig = struct( ...
    'training', struct( ...
        'miniBatchSize', runtimeConfig.training.miniBatchSize, ...
        'learnRateDropFactor', ...
            runtimeConfig.training.learnRateDropFactor), ...
    'pruning', struct( ...
        'fineTuneInitialLearnRate', ...
            runtimeConfig.pruning.fineTuneInitialLearnRate, ...
        'fineTuneLearnRateDropPeriod', ...
            runtimeConfig.pruning.fineTuneLearnRateDropPeriod, ...
        'fineTuneSeedOffset', ...
            runtimeConfig.pruning.fineTuneSeedOffset));

denseSource = struct('denseFit', denseFit, ...
    'digest', buildNetworkSignature(denseFit), ...
    'bestDenseEpoch', denseValidationFit.bestDenseEpoch, ...
    'fineTuneEpochs', bestFineTuneEpoch, ...
    'runtimeConfig', sparseRuntimeConfig);
end
