function fit = refitFairPNNNSparse(denseFit, features, targets, ...
    phaseRotation, y, identificationRows, fullSignalRows, ...
    targetActiveParameters, nnSeed, selectedFineTuneEpochs, cfg)
% refitFairPNNNSparse - Prune and refit one final identification PNNN.

masks = createMagnitudePruningMasks( ...
    denseFit.network, targetActiveParameters);
network = applyLearnableMasks(denseFit.network, masks);
checkPruningMaskIntegrity(network, masks);

normalization = denseFit.normalization;
featuresIdentification = normalizeFeatures( ...
    features(identificationRows, :), normalization);
targetsIdentification = normalizeTargets( ...
    targets(identificationRows, :), normalization);
cfg.pruning.fineTuneEpochs = double(selectedFineTuneEpochs);
rng(nnSeed + double(cfg.pruning.fineTuneSeedOffset), 'twister');
network = fineTunePrunedNetwork(network, featuresIdentification, ...
    targetsIdentification, [], [], cfg, masks);
checkPruningMaskIntegrity(network, masks);

counts = summarizeTrainableParameters(network, masks);
if counts.activeWeightParams + counts.activeBiasParams ~= ...
        targetActiveParameters
    error('refitFairPNNNSparse:TargetMismatch', ...
        'Final pruning did not produce the requested parameter count.');
end
if counts.activeBiasParams ~= counts.totalBiasParams
    error('refitFairPNNNSparse:BiasProtectionFailure', ...
        'Every final bias must remain active and protected.');
end

identificationPrediction = predictPhaseNorm(network, ...
    featuresIdentification, normalization, phaseRotation(identificationRows));
featuresFull = normalizeFeatures(features(fullSignalRows, :), normalization);
fullPrediction = predictPhaseNorm( ...
    network, featuresFull, normalization, phaseRotation(fullSignalRows));

fit = struct( ...
    'activeWeights', counts.activeWeightParams, ...
    'activeBiases', counts.activeBiasParams, ...
    'identificationNMSEdB', ...
        nmseComplexDb(y(identificationRows), identificationPrediction), ...
    'fullSignalNMSEdB', nmseComplexDb(y(fullSignalRows), fullPrediction), ...
    'masks', {masks}, ...
    'fullSignalPrediction', fullPrediction);
end

function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end
