function fit = refitFairPNNNDense(features, targets, identificationRows, ...
    hiddenNeurons, nnSeed, selectedEpochs, cfg)
% refitFairPNNNDense - Refit the selected PNNN on identification rows.

normalization = computePNNNNormalization( ...
    features(identificationRows, :), targets(identificationRows, :));
featuresIdentification = normalizeFeatures( ...
    features(identificationRows, :), normalization);
targetsIdentification = normalizeTargets( ...
    targets(identificationRows, :), normalization);

rng(nnSeed, 'twister');
layers = buildFairPNNNLayers(size(features, 2), hiddenNeurons);
iterationsPerEpoch = max(1, ...
    ceil(numel(identificationRows) / cfg.miniBatchSize));
options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=selectedEpochs, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="last-iteration", ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots="none", ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=iterationsPerEpoch);
network = trainnet( ...
    featuresIdentification, targetsIdentification, layers, "mse", options);

parameterCount = countPNNNParameters(size(features, 2), hiddenNeurons);
counts = summarizeTrainableParameters(network);
if counts.totalWeightParams + counts.totalBiasParams ~= ...
        parameterCount.realParameters
    error('refitFairPNNNDense:ParameterCountMismatch', ...
        'The final network does not match H*(D+3)+2.');
end

fit = struct('network', network, 'normalization', normalization);
end

function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end
