function fit = refitFairPNNNDense(features, targets, phaseRotation, y, ...
    identificationRows, fullSignalRows, hiddenNeurons, nnSeed, ...
    selectedEpochs, cfg)
% refitFairPNNNDense - Refit a selected PNNN on all identification rows.
% The network is reinitialized with the configured seed, normalized only
% from identification data, and trained for the selected fixed epoch count.

validateInputs(features, targets, phaseRotation, y, ...
    identificationRows, fullSignalRows, hiddenNeurons, nnSeed, ...
    selectedEpochs, cfg);

timer = tic;

input_dimension = size(features, 2);

normalization = computePNNNNormalization( ...
    features(identificationRows, :), targets(identificationRows, :));
features_identification = normalizeFeatures( ...
    features(identificationRows, :), normalization);
targets_identification = normalizeTargets( ...
    targets(identificationRows, :), normalization);
features_full_signal = normalizeFeatures( ...
    features(fullSignalRows, :), normalization);

rng(nnSeed, 'twister');

layers = buildFairPNNNLayers(input_dimension, hiddenNeurons);

iterations_per_epoch = max(1, ceil(numel(identificationRows) / cfg.miniBatchSize));

options = trainingOptions(cfg.optimizer, ...
    MaxEpochs=selectedEpochs, ...
    MiniBatchSize=cfg.miniBatchSize, ...
    InitialLearnRate=cfg.initialLearnRate, ...
    LearnRateSchedule=cfg.learnRateSchedule, ...
    LearnRateDropPeriod=cfg.learnRateDropPeriod, ...
    LearnRateDropFactor=cfg.learnRateDropFactor, ...
    Shuffle=cfg.shuffle, ...
    OutputNetwork="last-iteration", ...
    InputDataFormats=cfg.inputDataFormats, ...
    TargetDataFormats=cfg.targetDataFormats, ...
    ExecutionEnvironment=cfg.executionEnvironment, ...
    Plots=cfg.trainingPlots, ...
    Verbose=cfg.verbose, ...
    VerboseFrequency=iterations_per_epoch);

[network, training_info] = trainnet(features_identification, ...
    targets_identification, layers, "mse", options);

identification_prediction = predictPhaseNorm(network, ...
    features_identification, normalization, ...
    phaseRotation(identificationRows));

full_signal_prediction = predictPhaseNorm(network, ...
    features_full_signal, normalization, phaseRotation(fullSignalRows));
parameter_count = countPNNNParameters(input_dimension, hiddenNeurons);
learnable_count = summarizeTrainableParameters(network, false);
if learnable_count.totalTrainableParams ~= parameter_count.realParameters
    error('refitFairPNNNDense:ParameterCountMismatch', ...
        'The final network does not match H*(D+3)+2.');
end

fit = struct();
fit.network = network;
fit.normalization = normalization;
fit.hiddenNeurons = double(hiddenNeurons);
fit.nnSeed = double(nnSeed);
fit.parameterCount = parameter_count;
fit.targetActiveParams = NaN;
fit.actualActiveParams = parameter_count.realParameters;
fit.activeWeights = parameter_count.realWeights;
fit.activeBiases = parameter_count.realBiases;
fit.weightSparsityPercent = 0;
fit.iterationsPerEpoch = iterations_per_epoch;
fit.denseTrainingUpdates = finalTrainingIterations(training_info, selectedEpochs*iterations_per_epoch);
fit.fineTuneUpdates = 0;
fit.bestDenseEpoch = double(selectedEpochs);
fit.bestFineTuneEpoch = 0;
fit.identificationPrediction = identification_prediction;
fit.fullSignalPrediction = full_signal_prediction;
fit.identificationNMSEdB = nmseComplexDb(y(identificationRows), identification_prediction);
fit.fullSignalNMSEdB = nmseComplexDb(y(fullSignalRows), full_signal_prediction);
fit.finalTrainingInfo = training_info;
fit.finalFitSamples = numel(identificationRows);
fit.fullSignalSamples = numel(fullSignalRows);
fit.normalizationSamples = numel(identificationRows);
fit.finalContract = struct( ...
    'fitDomain', "identificationIndices", ...
    'normalizationDomain', "identificationIndices", ...
    'selectionDomainUsed', false, ...
    'fullSignalUsedForTraining', false, ...
    'fixedEpochs', double(selectedEpochs));
fit.trainingTimeSeconds = toc(timer);
end




function values = normalizeFeatures(values, stats)
values = (values - stats.muX) ./ stats.sigmaX;
end

function values = normalizeTargets(values, stats)
values = (values - stats.muY) ./ stats.sigmaY;
end

function iterations = finalTrainingIterations(info, fallback)
iterations = double(fallback);
if isprop(info, 'TrainingHistory') || ...
        (isstruct(info) && isfield(info, 'TrainingHistory'))
    history = info.TrainingHistory;
    if ~isempty(history)
        iterations = double(history.Iteration(end));
    end
end
end

function validateInputs(features, targets, rotation, y, ...
    identificationRows, fullSignalRows, hidden, seed, epochs, cfg)

n = size(features, 1);
if ~isnumeric(features) || ~isreal(features) || isempty(features) || ...
        any(~isfinite(features), 'all') || size(targets, 1) ~= n || ...
        size(targets, 2) ~= 2 || ~isreal(targets) || ...
        any(~isfinite(targets), 'all') || numel(rotation) ~= n || ...
        numel(y) ~= n || any(~isfinite(rotation)) || any(~isfinite(y))
    error('refitFairPNNNDense:InvalidData', ...
        'Features, targets, rotations, and target must be finite.');
end
validateattributes(identificationRows, {'numeric'}, ...
    {'vector','integer','positive','finite','<=',n});
validateattributes(fullSignalRows, {'numeric'}, ...
    {'vector','integer','positive','finite','<=',n});
validateattributes(hidden, {'numeric'}, ...
    {'scalar','integer','positive','finite'});
validateattributes(seed, {'numeric'}, ...
    {'scalar','integer','nonnegative','finite'});
validateattributes(epochs, {'numeric'}, ...
    {'scalar','integer','positive','finite'});
if ~all(ismember(identificationRows, fullSignalRows)) || ...
        numel(unique(identificationRows)) ~= numel(identificationRows) || ...
        ~isequal(fullSignalRows(:), (1:n).')
    error('refitFairPNNNDense:InvalidRows', ...
        'Identification must be unique and contained in the full signal.');
end
required_cfg = {'optimizer','miniBatchSize','initialLearnRate', ...
    'learnRateSchedule','learnRateDropPeriod','learnRateDropFactor', ...
    'shuffle','executionEnvironment','trainingPlots','verbose', ...
    'inputDataFormats','targetDataFormats'};
if ~isstruct(cfg) || ~all(isfield(cfg, required_cfg))
    error('refitFairPNNNDense:IncompleteConfiguration', ...
        'The fixed-epoch training configuration is incomplete.');
end
end
