function budget = scalePNNNTrainingBudget( ...
    totalSamples, trainingSamples, trainingCfg, pruningCfg)
% scalePNNNTrainingBudget - Match the historical PNNN update budget.
% Dense training and pruning fine-tuning are scaled from the configured
% historical sample count so a smaller TRAIN set does not reduce updates.

batch_size = double(trainingCfg.miniBatchSize);
historical_training_samples = floor( ...
    double(trainingCfg.historicalTrainFraction)*double(totalSamples));
historical_dense_iterations_per_epoch = max(1, floor( ...
    historical_training_samples/batch_size));
current_dense_iterations_per_epoch = max(1, floor( ...
    double(trainingSamples)/batch_size));

historical_dense_updates = historical_dense_iterations_per_epoch * ...
    double(trainingCfg.historicalMaxEpochs);
historical_drop_updates = historical_dense_iterations_per_epoch * ...
    double(trainingCfg.historicalLearnRateDropPeriod);
historical_patience_updates = historical_dense_iterations_per_epoch * ...
    double(trainingCfg.historicalValidationPatience);

dense_max_epochs = ceil(historical_dense_updates / ...
    current_dense_iterations_per_epoch);
dense_drop_period = ceil(historical_drop_updates / ...
    current_dense_iterations_per_epoch);
dense_validation_patience = ceil(historical_patience_updates / ...
    current_dense_iterations_per_epoch);

historical_fine_tune_iterations_per_epoch = max(1, ceil( ...
    historical_training_samples/batch_size));
current_fine_tune_iterations_per_epoch = max(1, ceil( ...
    double(trainingSamples)/batch_size));
historical_fine_tune_updates = ...
    historical_fine_tune_iterations_per_epoch * ...
    double(pruningCfg.historicalFineTuneEpochs);
fine_tune_epochs = ceil(historical_fine_tune_updates / ...
    current_fine_tune_iterations_per_epoch);
fine_tune_drop_period = ceil(historical_drop_updates / ...
    current_fine_tune_iterations_per_epoch);

budget = struct();
budget.denseMaxEpochs = dense_max_epochs;
budget.denseLearnRateDropPeriod = dense_drop_period;
budget.denseValidationPatience = dense_validation_patience;
budget.fineTuneEpochs = fine_tune_epochs;
budget.fineTuneLearnRateDropPeriod = fine_tune_drop_period;
end
