function flops = countModelFLOPs(model_counts, convention)
% countModelFLOPs - Convert explicit inference operation counts to FLOPs.
% Complex operations use the documented 6/2 weights; special operations
% are reported separately and never assigned an implicit FLOP equivalent.

if nargin < 2 || isempty(convention)
    convention = getFLOPConvention();
end
validateConvention(convention);
if ~istable(model_counts) || isempty(model_counts)
    error('countModelFLOPs:InvalidCounts', ...
        'model_counts must be a non-empty table.');
end

if ismember('FeatureGenerationMultiplications', ...
        model_counts.Properties.VariableNames)
    specifications = fromAnalyticalOperationTable(model_counts);
else
    specifications = validateCanonicalSpecifications(model_counts);
end

real_add_weight = convention.FLOPs( ...
    convention.Operation == "real addition or subtraction");
real_multiply_weight = convention.FLOPs( ...
    convention.Operation == "real multiplication");
complex_add_weight = convention.FLOPs( ...
    convention.Operation == "complex addition or subtraction");
complex_multiply_weight = convention.FLOPs( ...
    convention.Operation == "complex multiplication");

CoreFLOPsPerSample = ...
    specifications.RealMultiplicationsPerSample*real_multiply_weight + ...
    specifications.RealAdditionsPerSample*real_add_weight + ...
    specifications.ComplexMultiplicationsPerSample*complex_multiply_weight + ...
    specifications.ComplexAdditionsPerSample*complex_add_weight;
FLOPsPerSample = CoreFLOPsPerSample;
EstimatedTotalFLOPsPerSample = NaN(height(specifications), 1);
NumSpecialOpsPerSample = ...
    specifications.NumActivationEvaluationsPerSample + ...
    specifications.NumExpWorstCasePerSample + ...
    specifications.NumSqrtPerSample + ...
    specifications.NumRealDivisionsPerSample + ...
    specifications.NumAbsPerSample;
TotalCoreFLOPsPerSample = CoreFLOPsPerSample;

flops = addvars(specifications, FLOPsPerSample, CoreFLOPsPerSample, ...
    TotalCoreFLOPsPerSample, EstimatedTotalFLOPsPerSample, ...
    NumSpecialOpsPerSample, 'After', ...
    'ComplexAdditionsPerSample');

numeric_names = {'NumRealParameters','RealMultiplicationsPerSample', ...
    'RealAdditionsPerSample','ComplexMultiplicationsPerSample', ...
    'ComplexAdditionsPerSample','CoreFLOPsPerSample', ...
    'FLOPsPerSample', ...
    'NumActivationEvaluationsPerSample','NumExpWorstCasePerSample', ...
    'NumSqrtPerSample','NumRealDivisionsPerSample', ...
    'NumAbsPerSample','NumRealWeights','NumRealBiases', ...
    'DenseLayerCoreFLOPs','OutputLayerCoreFLOPs'};
for index = 1:numel(numeric_names)
    values = flops.(numeric_names{index});
    if any(~isfinite(values)) || any(values < 0) || ...
            any(values ~= floor(values))
        error('countModelFLOPs:InvalidIntegerCount', ...
            '%s must contain non-negative finite integers.', ...
            numeric_names{index});
    end
end

end

function specifications = fromAnalyticalOperationTable(counts)
required = {'Model','RealParameters', ...
    'FeatureGenerationMultiplications','FeatureGenerationAdditions', ...
    'CoefficientMultiplications','CoefficientProductAdditions', ...
    'AccumulationAdditions','PhaseNormalizationMultiplications', ...
    'PhaseNormalizationAdditions','PhaseRestorationMultiplications', ...
    'PhaseRestorationAdditions','Divisions','SquareRoots', ...
    'TotalRealMultiplicationsPerSample','TotalRealAdditionsPerSample'};
if ~all(ismember(required, counts.Properties.VariableNames))
    error('countModelFLOPs:InvalidAnalyticalTable', ...
        'The analytical operation table is missing required columns.');
end

n_models = height(counts);
Model = string(counts.Model);
NumRealParameters = counts.RealParameters;
RealMultiplicationsPerSample = counts.TotalRealMultiplicationsPerSample;
RealAdditionsPerSample = counts.TotalRealAdditionsPerSample;
ComplexMultiplicationsPerSample = zeros(n_models, 1);
ComplexAdditionsPerSample = zeros(n_models, 1);

complex_rows = Model == "Complex GMP";
if any(complex_rows)
    coefficient_real_multiplications = ...
        counts.CoefficientMultiplications(complex_rows);
    coefficient_product_additions = ...
        counts.CoefficientProductAdditions(complex_rows);
    accumulation_real_additions = ...
        counts.AccumulationAdditions(complex_rows);
    if any(mod(coefficient_real_multiplications, 4) ~= 0) || ...
            any(mod(coefficient_product_additions, 2) ~= 0) || ...
            any(mod(accumulation_real_additions, 2) ~= 0)
        error('countModelFLOPs:InvalidComplexExpansion', ...
            'Expanded complex arithmetic is not divisible by 4M/2A.');
    end
    ComplexMultiplicationsPerSample(complex_rows) = ...
        coefficient_real_multiplications/4;
    ComplexAdditionsPerSample(complex_rows) = ...
        accumulation_real_additions/2;
    RealMultiplicationsPerSample(complex_rows) = ...
        RealMultiplicationsPerSample(complex_rows) - ...
        coefficient_real_multiplications;
    RealAdditionsPerSample(complex_rows) = ...
        RealAdditionsPerSample(complex_rows) - ...
        coefficient_product_additions - accumulation_real_additions;
end

NumActivationEvaluationsPerSample = zeros(n_models, 1);
NumExpWorstCasePerSample = zeros(n_models, 1);
NumSqrtPerSample = counts.SquareRoots;
NumRealDivisionsPerSample = counts.Divisions;
NumAbsPerSample = counts.SquareRoots;
PhaseNormalizationIncluded = contains(Model, "PN-IQ-GMP");
PhaseRestorationIncluded = PhaseNormalizationIncluded;
ComplexityScope = repmat("inference per output sample", n_models, 1);
NumRealWeights = NumRealParameters;
NumRealBiases = zeros(n_models, 1);
DenseLayerCoreFLOPs = zeros(n_models, 1);
OutputLayerCoreFLOPs = zeros(n_models, 1);

specifications = table(Model, NumRealParameters, ...
    RealMultiplicationsPerSample, RealAdditionsPerSample, ...
    ComplexMultiplicationsPerSample, ComplexAdditionsPerSample, ...
    NumActivationEvaluationsPerSample, NumExpWorstCasePerSample, ...
    NumSqrtPerSample, ...
    NumRealDivisionsPerSample, NumAbsPerSample, ...
    PhaseNormalizationIncluded, PhaseRestorationIncluded, ...
    ComplexityScope, NumRealWeights, NumRealBiases, ...
    DenseLayerCoreFLOPs, OutputLayerCoreFLOPs);
end

function specifications = validateCanonicalSpecifications(specifications)
required = {'Model','NumRealParameters', ...
    'RealMultiplicationsPerSample','RealAdditionsPerSample', ...
    'ComplexMultiplicationsPerSample','ComplexAdditionsPerSample', ...
    'NumActivationEvaluationsPerSample','NumExpWorstCasePerSample', ...
    'NumSqrtPerSample', ...
    'NumRealDivisionsPerSample','NumAbsPerSample', ...
    'PhaseNormalizationIncluded','PhaseRestorationIncluded', ...
    'ComplexityScope','NumRealWeights','NumRealBiases', ...
    'DenseLayerCoreFLOPs','OutputLayerCoreFLOPs'};
if ~all(ismember(required, specifications.Properties.VariableNames))
    error('countModelFLOPs:InvalidCanonicalTable', ...
        'The canonical model specification is missing required columns.');
end
specifications = specifications(:, required);
specifications.Model = string(specifications.Model);
specifications.ComplexityScope = string(specifications.ComplexityScope);
if any(specifications.ComplexityScope ~= "inference per output sample")
    error('countModelFLOPs:InvalidScope', ...
        'ComplexityScope must be inference per output sample.');
end
end

function validateConvention(convention)
required_operations = [ ...
    "real addition or subtraction"; "real multiplication"; ...
    "real MAC"; "complex addition or subtraction"; ...
    "complex multiplication"; "complex MAC"; ...
    "real bias addition"];
if ~istable(convention) || ...
        ~all(ismember({'Operation','FLOPs'}, ...
        convention.Properties.VariableNames)) || ...
        ~isequal(string(convention.Operation), required_operations) || ...
        ~isequal(convention.FLOPs, [1; 1; 2; 2; 6; 8; 1])
    error('countModelFLOPs:InvalidConvention', ...
        'The supplied FLOP convention does not match the fixed contract.');
end
end
