function convention = getFLOPConvention()
% getFLOPConvention - Return the fixed arithmetic FLOP convention.
% Only additions and multiplications receive FLOP weights; nonlinear and
% division-related operations remain separate unweighted counts.

Operation = [ ...
    "real addition or subtraction"; ...
    "real multiplication"; ...
    "real MAC"; ...
    "complex addition or subtraction"; ...
    "complex multiplication"; ...
    "complex MAC"; ...
    "real bias addition"];
FLOPs = [1; 1; 2; 2; 6; 8; 1];
Definition = [ ...
    "one real arithmetic addition"; ...
    "one real arithmetic multiplication"; ...
    "one real multiplication plus one accumulation"; ...
    "two real additions"; ...
    "four real multiplications plus two real additions"; ...
    "one complex multiplication plus one complex addition"; ...
    "one real addition"];
IncludedInCoreFLOPs = true(size(FLOPs));
convention = table(Operation, FLOPs, Definition, IncludedInCoreFLOPs);
end
