function spectrum = computeSelectedPointSpectra( ...
    target, predictions, sampleRateHz, fixedPredictions)
% computeSelectedPointSpectra - Compute one shared centered Welch spectrum.
% Target, nine predictions, and their errors use identical Welch settings.
% Every PSD is expressed relative to the target full-signal spectral peak.

target = target(:);
if ~isnumeric(predictions) || size(predictions, 1) ~= numel(target) || ...
        size(predictions, 2) ~= 3 || isempty(target) || ...
        any(~isfinite(target)) || any(~isfinite(predictions), 'all')
    error('computeSelectedPointSpectra:InvalidSignals', ...
        'Target and three finite aligned prediction columns are required.');
end
if ~isscalar(sampleRateHz) || ~isfinite(sampleRateHz) || sampleRateHz <= 0
    error('computeSelectedPointSpectra:InvalidSampleRate', ...
        'sampleRateHz must be a positive finite scalar.');
end
if ~isnumeric(fixedPredictions) || ...
        size(fixedPredictions, 1) ~= numel(target) || ...
        size(fixedPredictions, 2) ~= 6 || ...
        any(~isfinite(fixedPredictions), 'all')
    error('computeSelectedPointSpectra:InvalidFixedSignals', ...
        'Six finite aligned fixed-lambda prediction columns are required.');
end

errors = target - predictions;
fixedErrors = target - fixedPredictions;
signals = [target, predictions, fixedPredictions, errors, fixedErrors];
windowLength = min(4096, numel(target));
overlapLength = floor(windowLength/2);
nfft = max(4096, 2^nextpow2(windowLength));
window = hann(windowLength, 'periodic');
[psdLinear, frequencyHz] = pwelch(signals, window, overlapLength, ...
    nfft, sampleRateHz, 'centered', 'psd');
referencePSD = max(psdLinear(:, 1));
if ~isfinite(referencePSD) || referencePSD <= 0
    error('computeSelectedPointSpectra:InvalidReference', ...
        'The target must have positive finite spectral power.');
end
numericalFloor = max(referencePSD*1e-15, realmin);
psdDb = 10*log10(max(psdLinear, numericalFloor)/referencePSD);

spectrum = struct( ...
    'frequencyMHz', frequencyHz/1e6, ...
    'outputPSDdB', psdDb(:, 1:4), ...
    'fixedOutputPSDdB', psdDb(:, 5:10), ...
    'errorPSDdB', psdDb(:, 11:13), ...
    'fixedErrorPSDdB', psdDb(:, 14:19), ...
    'errors', errors, ...
    'fixedErrors', fixedErrors, ...
    'psdLinear', psdLinear, ...
    'referencePSD', referencePSD, ...
    'numericalFloor', numericalFloor, ...
    'config', struct('sampleRateHz', double(sampleRateHz), ...
        'method', "Centered bilateral Welch PSD", ...
        'window', "Periodic Hann", ...
        'windowLength', windowLength, ...
        'overlapLength', overlapLength, ...
        'nfft', nfft, ...
        'normalizationReference', ...
            "Maximum target full-signal PSD", ...
        'numericalFloorRelativeToReferenceDb', -150, ...
        'errorDefinition', "targetFullSignal - prediction"));
end
