function files = exportSelectedSpectrumFigures(spectrum, directory, ...
    fixedLambdas, exportOptions)
% exportSelectedSpectrumFigures - Export the four selected-budget spectra.
% The Welch arrays are accepted as already-computed data and are not changed.

if nargin < 4 || isempty(exportOptions)
    exportOptions = struct();
end
if ~isfolder(directory)
    mkdir(directory);
end
frequencyMHz = spectrum.frequencyMHz;
targetPSD = spectrum.outputPSDdB(:, 1);
files = struct();
files.output = exportMainSpectrum(frequencyMHz, ...
    spectrum.outputPSDdB, ["Target full signal", ...
    "Complex GMP-DOMP", "PN-IQ PN-DOMP", "Sparse PNNN N12"], ...
    fullfile(directory, 'selected_output_spectrum'), exportOptions);
files.error = exportMainSpectrum(frequencyMHz, ...
    [targetPSD, spectrum.errorPSDdB], ["Target full signal", ...
    "Complex GMP-DOMP error", "PN-IQ PN-DOMP error", ...
    "Sparse PNNN N12 error"], ...
    fullfile(directory, 'selected_error_spectrum'), exportOptions);
files.ridgeOutput = exportRidgeSpectrum(frequencyMHz, ...
    {[targetPSD, spectrum.outputPSDdB(:, 2), ...
        spectrum.fixedOutputPSDdB(:, 1:3)], ...
    [targetPSD, spectrum.outputPSDdB(:, 3), ...
        spectrum.fixedOutputPSDdB(:, 4:6)]}, fixedLambdas, ...
    fullfile(directory, 'selected_ridge_output_spectrum'), ...
    exportOptions);
files.ridgeError = exportRidgeSpectrum(frequencyMHz, ...
    {[targetPSD, spectrum.errorPSDdB(:, 1), ...
        spectrum.fixedErrorPSDdB(:, 1:3)], ...
    [targetPSD, spectrum.errorPSDdB(:, 2), ...
        spectrum.fixedErrorPSDdB(:, 4:6)]}, fixedLambdas, ...
    fullfile(directory, 'selected_ridge_error_spectrum'), ...
    exportOptions);
end

function files = exportMainSpectrum(frequencyMHz, values, labels, ...
    baseFilename, exportOptions)
style = getIEEEPaperStyle();
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Units', 'inches', 'Position', [1 1 7.0 4.2]);
cleanup = onCleanup(@() close(figureHandle));
axesHandle = axes(figureHandle);
hold(axesHandle, 'on');
target = plot(axesHandle, frequencyMHz, values(:, 1), ...
    'Color', style.targetGray, 'LineStyle', '-', ...
    'LineWidth', style.targetLineWidth, 'DisplayName', labels(1));
familyLines = gobjects(3, 1);
for index = 1:3
    familyLines(index) = plot(axesHandle, frequencyMHz, values(:, index + 1), ...
        'Color', style.mainColors(index, :), ...
        'LineStyle', style.mainLineStyles{index}, ...
        'Marker', style.mainMarkers{index}, ...
        'MarkerIndices', spectrumMarkerIndices(numel(frequencyMHz)), ...
        'MarkerSize', style.markerSize - 1, ...
        'LineWidth', style.mainLineWidth, 'DisplayName', labels(index + 1));
end
formatSpectrumAxes(axesHandle, style);
legend(axesHandle, [target; familyLines], 'Location', 'southoutside', ...
    'Orientation', 'horizontal', 'NumColumns', 4, ...
    'Interpreter', 'none', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 1);
exportOptions.tikzExtraAxisOptions = { ...
    'legend columns=4', ...
    'legend style={at={(0.5,-0.17)},anchor=north}', ...
    sprintf('every axis plot/.append style={mark repeat=%d}', ...
        max(1, floor(numel(frequencyMHz)/14)))};
exportOptions.figureHeight = '4.5in';
files = exportPaperFigure(figureHandle, baseFilename, exportOptions);
clear cleanup;
end

function files = exportRidgeSpectrum(frequencyMHz, panels, fixedLambdas, ...
    baseFilename, exportOptions)
style = getIEEEPaperStyle();
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Units', 'inches', 'Position', [1 1 7.16 5.0]);
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
layout.OuterPosition = [0 0.30 1 0.70];
familyNames = ["Complex GMP-DOMP", "PN-IQ PN-DOMP"];
firstAxes = gobjects(1);
complexLegendLines = gobjects(0, 1);
for panelIndex = 1:2
    axesHandle = nexttile(layout);
    if panelIndex == 1
        firstAxes = axesHandle;
    end
    hold(axesHandle, 'on');
    values = panels{panelIndex};
    targetLine = plot(axesHandle, frequencyMHz, values(:, 1), ...
        'Color', style.targetGray, 'LineStyle', '-', ...
        'LineWidth', style.targetLineWidth, ...
        'DisplayName', 'Target full signal');
    principalLine = plot(axesHandle, frequencyMHz, values(:, 2), ...
        'Color', style.mainColors(panelIndex, :), ...
        'LineStyle', style.mainLineStyles{panelIndex}, ...
        'Marker', style.mainMarkers{panelIndex}, ...
        'MarkerIndices', spectrumMarkerIndices(numel(frequencyMHz)), ...
        'MarkerSize', style.markerSize - 1, ...
        'LineWidth', style.mainLineWidth, ...
        'DisplayName', familyNames(panelIndex) + " principal");
    ridgeLines = gobjects(numel(fixedLambdas), 1);
    for lambdaIndex = 1:numel(fixedLambdas)
        ridgeLines(lambdaIndex) = plot(axesHandle, frequencyMHz, ...
            values(:, lambdaIndex + 2), ...
            'Color', style.mainColors(panelIndex, :), ...
            'LineStyle', style.ridgeLineStyles{lambdaIndex}, ...
            'LineWidth', style.ridgeLineWidth, ...
            'DisplayName', familyNames(panelIndex) + ", \lambda=" + ...
                compose('%g', fixedLambdas(lambdaIndex)));
    end
    formatSpectrumAxes(axesHandle, style);
    panelLabels = ["(a) ", "(b) "];
    title(axesHandle, panelLabels(panelIndex) + familyNames(panelIndex), ...
        'Interpreter', 'none');
    if panelIndex == 1
        complexLegendLines = [targetLine; principalLine; ridgeLines];
    end
end
xLimits = xlim(firstAxes);
yLimits = ylim(firstAxes);
legendX = xLimits(1) - diff(xLimits);
legendY = yLimits(1) - diff(yLimits);
pnLegendLines = gobjects(1 + numel(fixedLambdas), 1);
pnLegendLines(1) = plot(firstAxes, legendX, legendY, ...
    'Color', style.pnOrange, 'LineStyle', style.mainLineStyles{2}, ...
    'Marker', style.mainMarkers{2}, 'MarkerSize', style.markerSize - 1, ...
    'LineWidth', style.mainLineWidth, ...
    'DisplayName', familyNames(2) + " principal");
for lambdaIndex = 1:numel(fixedLambdas)
    pnLegendLines(lambdaIndex + 1) = plot(firstAxes, legendX, legendY, ...
        'Color', style.pnOrange, ...
        'LineStyle', style.ridgeLineStyles{lambdaIndex}, ...
        'LineWidth', style.ridgeLineWidth, ...
        'DisplayName', familyNames(2) + ", \lambda=" + ...
            compose('%g', fixedLambdas(lambdaIndex)));
end
xlim(firstAxes, xLimits);
ylim(firstAxes, yLimits);
allLegendLines = [complexLegendLines; pnLegendLines];
allLegendLabels = string({allLegendLines.DisplayName}).';
legendHandle = legend(firstAxes, allLegendLines, allLegendLabels, ...
    'Orientation', 'horizontal', 'NumColumns', 3, ...
    'Interpreter', 'tex', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 2);
legendHandle.Units = 'normalized';
legendHandle.Position = [0.03 0.01 0.94 0.25];
legendHandle.Units = 'pixels';
axesHandles = findobj(figureHandle, 'Type', 'axes');
for index = 1:numel(axesHandles)
    axesHandles(index).Units = 'pixels';
end
exportOptions.tikzExtraAxisOptions = { ...
    'legend columns=3', ...
    'legend style={at={(1.1,-0.28)},anchor=north}', ...
    sprintf('every axis plot/.append style={mark repeat=%d}', ...
        max(1, floor(numel(frequencyMHz)/14)))};
exportOptions.figureHeight = '5.0in';
files = exportPaperFigure(figureHandle, baseFilename, exportOptions);
clear cleanup;
end

function indices = spectrumMarkerIndices(count)
step = max(1, floor(count/14));
indices = unique([1:step:count, count]);
end

function formatSpectrumAxes(axesHandle, style)
grid(axesHandle, 'on');
box(axesHandle, 'on');
xlabel(axesHandle, 'Frequency (MHz)');
ylabel(axesHandle, 'PSD relative to target peak (dB)');
set(axesHandle, 'FontName', style.fontName, ...
    'FontSize', style.fontSize, 'LineWidth', style.axisLineWidth);
end
