function files = exportPaperFigure(figureHandle, baseFilename, options)
% exportPaperFigure - Export one figure handle to FIG, PNG, TikZ, and PDF.
% The PDF is compiled with LuaLaTeX from the same matlab2tikz output through
% a standalone wrapper. LuaLaTeX avoids pdfTeX's fixed main-memory ceiling
% for dense multi-curve spectra. Intermediates are deleted only after success.

if nargin < 3 || isempty(options)
    options = struct();
end
if ~isgraphics(figureHandle, 'figure')
    error('exportPaperFigure:InvalidFigure', ...
        'figureHandle must refer to one live MATLAB figure.');
end
baseFilename = char(string(baseFilename));
[directory, name, extension] = fileparts(baseFilename);
if isempty(directory)
    directory = pwd;
end
if ~isempty(extension)
    error('exportPaperFigure:BaseFilenameHasExtension', ...
        'baseFilename must not include a file extension.');
end
if ~isfolder(directory)
    mkdir(directory);
end
if ~isfield(options, 'latexmkCommand')
    options.latexmkCommand = 'latexmk';
end
files = struct( ...
    'fig', string(fullfile(directory, name + ".fig")), ...
    'png', string(fullfile(directory, name + ".png")), ...
    'tikz', string(fullfile(directory, name + ".tikz")), ...
    'pdf', string(fullfile(directory, name + ".pdf")), ...
    'standaloneTex', string(fullfile(directory, name + "_standalone.tex")), ...
    'standalonePdf', string(fullfile(directory, name + "_standalone.pdf")));

set(figureHandle, 'Color', 'w', 'InvertHardcopy', 'off');
originalVisible = figureHandle.Visible;
figureHandle.Visible = 'on';
savefig(figureHandle, char(files.fig));
figureHandle.Visible = originalVisible;
exportgraphics(figureHandle, char(files.png), 'Resolution', 300, ...
    'BackgroundColor', 'white');

if exist('matlab2tikz', 'file') ~= 2
    error('exportPaperFigure:MissingMatlab2tikz', ...
        ['matlab2tikz is not on the MATLAB path. Initialize the submodule ' ...
        'and add third_party/matlab2tikz/src.']);
end
matlab2tikzArguments = {char(files.tikz), ...
    'figurehandle', figureHandle, ...
    'width', '0.68\figurewidth', 'height', '0.7\figureheight', ...
    'standalone', false, 'showInfo', false};
tikzAxisOptions = {'width=0.68\figurewidth', ...
    'height=0.7\figureheight'};
if isfield(options, 'tikzExtraAxisOptions')
    tikzAxisOptions = [tikzAxisOptions, options.tikzExtraAxisOptions];
end
matlab2tikzArguments = [matlab2tikzArguments, ...
    {'extraAxisOptions', tikzAxisOptions}];
matlab2tikz(matlab2tikzArguments{:});

wrapperBase = name + "_standalone";
writeStandaloneWrapper(char(files.standaloneTex), name + ".tikz");
latexmkCommand = char(string(options.latexmkCommand));
try
    latexmk = resolveLatexmkCommand(latexmkCommand);
catch exception
    warning('exportPaperFigure:LatexmkUnavailable', ...
        'Standalone PDF was not compiled: %s', exception.message);
    return;
end
command = sprintf(['%s -lualatex -cd -interaction=nonstopmode ' ...
    '-halt-on-error "%s"'], latexmk.commandPrefix, files.standaloneTex);
[status, commandOutput] = system(command);
wrapperLog = fullfile(directory, wrapperBase + ".log");
if status ~= 0 || ~isfile(files.standalonePdf)
    error('exportPaperFigure:LatexCompileFailed', ...
        ['latexmk could not compile the standalone paper figure. ' ...
        'Intermediates were preserved; inspect %s. Output: %s'], ...
        wrapperLog, strtrim(commandOutput));
end

[copied, message] = copyfile(files.standalonePdf, files.pdf, 'f');
if ~copied
    error('exportPaperFigure:PDFMoveFailed', ...
        'The standalone PDF could not be copied to the standard PDF: %s', ...
        message);
end
cleanupSuccessfulCompile(directory, wrapperBase);
end

function writeStandaloneWrapper(filename, tikzFilename)
lines = [ ...
    "\PassOptionsToClass{lettersize,journal}{IEEEtran}"; ...
    "\documentclass["; ...
    "    tikz,"; ...
    "    class=IEEEtran,"; ...
    "    border=0pt"; ...
    "]{standalone}"; ...
    "\usepackage{pgfplots}"; ...
    "\usepackage{amsmath}"; ...
    "\usetikzlibrary{plotmarks}"; ...
    "\usepgfplotslibrary{groupplots}"; ...
    "\pgfplotsset{compat=1.18}"; ...
    "\newlength{\figurewidth}"; ...
    "\newlength{\figureheight}"; ...
    "\setlength{\figurewidth}{\columnwidth}"; ...
    "\setlength{\figureheight}{\columnwidth}"; ...
    "\begin{document}"; ...
    "\input{" + replace(string(tikzFilename), "\", "/") + "}"; ...
    "\end{document}"];
writelines(lines, filename);
end

function cleanupSuccessfulCompile(directory, wrapperBase)
extensions = [".aux", ".fdb_latexmk", ".fls", ".log"];
for extension = extensions
    filename = fullfile(directory, wrapperBase + extension);
    if isfile(filename)
        delete(filename);
    end
end
end
