function style = getIEEEPaperStyle()
% getIEEEPaperStyle - Return the sole palette and line grammar for figures.

style = struct( ...
    'targetGray', [117 120 123]/255, ...
    'gmpBlue', [0 98 155]/255, ...
    'pnOrange', [232 119 34]/255, ...
    'pnnnGreen', [0 132 61]/255, ...
    'selectedRed', [186 12 47]/255, ...
    'fontName', 'Times New Roman', ...
    'fontSize', 10, ...
    'axisLineWidth', 0.9, ...
    'mainLineWidth', 1.6, ...
    'targetLineWidth', 1.9, ...
    'ridgeLineWidth', 1.25, ...
    'markerSize', 5);
style.mainColors = [style.gmpBlue; style.pnOrange; style.pnnnGreen];
style.mainLineStyles = {'-', '--', '-.'};
style.mainMarkers = {'o', 's', '^'};
style.ridgeLineStyles = {':', '--', '-.'};
end
