function sweep = run_linear_sweep(x, y, split, cfg)
% run_linear_sweep - Fit the Complex GMP and independent PN-IQ curves.
% Each family selects one maximum DOMP path on internal train and one on
% identification; every parameter target is an exact prefix of those paths.

x = x(:);
y = y(:);
requiredSplit = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices','fullSignalIndices'};
if numel(x) ~= numel(y) || isempty(x) || any(~isfinite(x)) || ...
        any(~isfinite(y)) || ~all(isfield(split, requiredSplit))
    error('run_linear_sweep:InvalidInput', ...
        'Finite aligned signals and the complete shared split are required.');
end

targets = double(cfg.sweep.parameterGrid(:).');
if isempty(targets) || any(targets <= 0) || any(mod(targets, 2)) || ...
        ~isequal(targets, unique(targets, 'sorted'))
    error('run_linear_sweep:InvalidGrid', ...
        'Linear targets must be sorted unique positive even integers.');
end
featureCounts = targets/2;
maximumFeatures = max(featureCounts);
rows = struct('train', split.internalTrainIndices(:), ...
    'validation', split.internalValidationIndices(:), ...
    'identification', split.identificationIndices(:), ...
    'fullSignal', split.fullSignalIndices(:));

dompInvocationCount = struct('complexInternalTrain', 0, ...
    'complexIdentification', 0, 'pnInternalTrain', 0, ...
    'pnIdentification', 0);
matrixPassCount = struct('complexInternalTrain', 0, ...
    'complexInternalValidation', 0, 'pnInternalTrain', 0, ...
    'pnInternalValidation', 0, 'complexIdentification', 0, ...
    'pnIdentification', 0, 'complexFullSignal', 0, ...
    'pnFullSignal', 0);

%% Build the shared GMP population
% The same population supplies the two families and every parameter target.
manager = GMP_createRegressorManager(x, y, cfg.gmp);
population = (1:numel(manager.regPopulation)).';
if maximumFeatures > numel(population)
    error('run_linear_sweep:InsufficientPopulation', ...
        'The GMP population cannot represent the largest target.');
end

%% Complex GMP: internal DOMP path and lambda selection
% Full-signal rows are absent from both support and lambda selection.
fprintf('[Linear] Building Complex GMP internal matrices...\n');
complexTrain = buildGMPRegressorRows(x, rows.train, manager, population);
complexValidation = buildGMPRegressorRows( ...
    x, rows.validation, manager, population);
matrixPassCount.complexInternalTrain = 1;
matrixPassCount.complexInternalValidation = 1;
trainTarget = y(rows.train);
validationTarget = y(rows.validation);

fprintf('[Linear] Computing one Complex GMP DOMP path on internal train...\n');
[complexTrainPath, ~] = selectDOMPSupport(complexTrain, trainTarget, ...
    maximumFeatures, cfg.gmp.dompOptions);
complexTrainPath = complexTrainPath(:);
dompInvocationCount.complexInternalTrain = 1;
if numel(complexTrainPath) < maximumFeatures
    error('run_linear_sweep:EarlyDOMPTermination', ...
        'Complex internal DOMP selected %d of %d required regressors.', ...
        numel(complexTrainPath), maximumFeatures);
end

complexLambdas = zeros(size(featureCounts));
complexValidationNMSE = zeros(size(featureCounts));
for targetIndex = 1:numel(targets)
    support = complexTrainPath(1:featureCounts(targetIndex));
    fits = fitComplexGMPGrid( ...
        complexTrain, trainTarget, support, cfg.lambdaGrid);
    candidateNMSE = zeros(numel(cfg.lambdaGrid), 1);
    for lambdaIndex = 1:numel(cfg.lambdaGrid)
        prediction = complexValidation(:, support) * ...
            fits.coefficients(:, lambdaIndex);
        candidateNMSE(lambdaIndex) = ...
            nmseComplexDb(validationTarget, prediction);
    end
    [complexValidationNMSE(targetIndex), selected] = min(candidateNMSE);
    complexLambdas(targetIndex) = cfg.lambdaGrid(selected);
end

%% PN-IQ: phase-normalized features and internal PN-DOMP path
% For every evaluated row, r=conj(x)/abs(x), with r=1 when x is zero.
fprintf('[Linear] Building PN-IQ internal matrices...\n');
[probe, probeDetails] = buildPhaseNormalizedIQRegressors( ...
    x, rows.train(1), manager, population);
featureMetadataRaw = probeDetails.featureMetadata;
structuralZero = logical(featureMetadataRaw.StructuralZero(:));
if any(structuralZero & string(featureMetadataRaw.Component) ~= "Q") || ...
        any(abs(probe(:, structuralZero)) > 1e-12, 'all')
    error('run_linear_sweep:StructuralReduction', ...
        'Only declared, numerically zero Q features may be removed.');
end
keptFeatureIndices = find(~structuralZero);
featureMetadata = featureMetadataRaw(keptFeatureIndices, :);
rawFeatureCount = width(probe);
effectiveFeatureCount = numel(keptFeatureIndices);
if effectiveFeatureCount < maximumFeatures
    error('run_linear_sweep:InsufficientPNFeatures', ...
        'The retained PN population is smaller than the largest prefix.');
end

reduction = struct('rawFeatureCount', rawFeatureCount, ...
    'effectiveFeatureCount', effectiveFeatureCount, ...
    'keptIndices', keptFeatureIndices, ...
    'zeroIndices', find(structuralZero), ...
    'duplicateIndices', zeros(0, 1), ...
    'oppositeIndices', zeros(0, 1), ...
    'rawToKept', zeros(rawFeatureCount, 1), ...
    'rawSign', ones(rawFeatureCount, 1), ...
    'structurallyZeroRemoved', nnz(structuralZero), ...
    'structuralDuplicatesRemoved', 0, ...
    'structuralOppositesRemoved', 0, ...
    'featureMetadata', featureMetadataRaw, 'tolerance', 1e-12);
reduction.rawToKept(keptFeatureIndices) = (1:effectiveFeatureCount).';

pnTrain = zeros(numel(rows.train), effectiveFeatureCount);
for first = 1:cfg.sweep.candidateBlockSize:numel(rows.train)
    local = first:min(first + cfg.sweep.candidateBlockSize - 1, ...
        numel(rows.train));
    raw = buildPhaseNormalizedIQRegressors( ...
        x, rows.train(local), manager, population);
    pnTrain(local, :) = raw(:, keptFeatureIndices);
end
pnValidation = zeros(numel(rows.validation), effectiveFeatureCount);
for first = 1:cfg.sweep.candidateBlockSize:numel(rows.validation)
    local = first:min(first + cfg.sweep.candidateBlockSize - 1, ...
        numel(rows.validation));
    raw = buildPhaseNormalizedIQRegressors( ...
        x, rows.validation(local), manager, population);
    pnValidation(local, :) = raw(:, keptFeatureIndices);
end
matrixPassCount.pnInternalTrain = 1;
matrixPassCount.pnInternalValidation = 1;

trainRotation = complex(ones(numel(rows.train), 1));
trainInput = x(rows.train);
nonzero = abs(trainInput) ~= 0;
trainRotation(nonzero) = conj(trainInput(nonzero)) ./ abs(trainInput(nonzero));
validationRotation = complex(ones(numel(rows.validation), 1));
validationInput = x(rows.validation);
nonzero = abs(validationInput) ~= 0;
validationRotation(nonzero) = ...
    conj(validationInput(nonzero)) ./ abs(validationInput(nonzero));
pnTrainTarget = trainRotation .* trainTarget;

fprintf('[Linear] Computing one PN-IQ PN-DOMP path on internal train...\n');
[pnTrainPath, ~] = selectDOMPSupport(pnTrain, pnTrainTarget, ...
    maximumFeatures, cfg.gmp.dompOptions);
pnTrainPath = pnTrainPath(:);
dompInvocationCount.pnInternalTrain = 1;
if numel(pnTrainPath) < maximumFeatures
    error('run_linear_sweep:EarlyDOMPTermination', ...
        'PN internal DOMP selected %d of %d required features.', ...
        numel(pnTrainPath), maximumFeatures);
end

pnLambdas = zeros(size(featureCounts));
pnValidationNMSE = zeros(size(featureCounts));
for targetIndex = 1:numel(targets)
    support = pnTrainPath(1:featureCounts(targetIndex));
    candidateNMSE = zeros(numel(cfg.lambdaGrid), 1);
    for lambdaIndex = 1:numel(cfg.lambdaGrid)
        fit = fitIndependentIQGMP(pnTrain(:, support), pnTrainTarget, ...
            cfg.lambdaGrid(lambdaIndex), reduction, "PN-DOMP sweep");
        predictionNormalized = pnValidation(:, support) * fit.coefficientsI + ...
            1j * (pnValidation(:, support) * fit.coefficientsQ);
        prediction = conj(validationRotation) .* predictionNormalized;
        candidateNMSE(lambdaIndex) = ...
            nmseComplexDb(validationTarget, prediction);
    end
    [pnValidationNMSE(targetIndex), selected] = min(candidateNMSE);
    pnLambdas(targetIndex) = cfg.lambdaGrid(selected);
end
clear complexTrain complexValidation pnTrain pnValidation

%% Complex GMP: final identification fits and full-signal prediction
% One identification path supplies every fitted prefix.
identificationTarget = y(rows.identification);
fullSignalTarget = y(rows.fullSignal);
fprintf('[Linear] Building the Complex GMP identification matrix...\n');
complexIdentification = buildGMPRegressorRows( ...
    x, rows.identification, manager, population);
matrixPassCount.complexIdentification = 1;
fprintf('[Linear] Computing one Complex GMP DOMP path on identification...\n');
[complexIdentificationPath, ~] = selectDOMPSupport( ...
    complexIdentification, identificationTarget, maximumFeatures, ...
    cfg.gmp.dompOptions);
complexIdentificationPath = complexIdentificationPath(:);
dompInvocationCount.complexIdentification = 1;
if numel(complexIdentificationPath) < maximumFeatures
    error('run_linear_sweep:EarlyDOMPTermination', ...
        'Complex identification DOMP selected %d of %d required regressors.', ...
        numel(complexIdentificationPath), maximumFeatures);
end

complexCoefficients = complex(zeros(maximumFeatures, numel(targets)));
for targetIndex = 1:numel(targets)
    count = featureCounts(targetIndex);
    support = complexIdentificationPath(1:count);
    fit = fitComplexGMPGrid(complexIdentification, ...
        identificationTarget, support, complexLambdas(targetIndex));
    complexCoefficients(1:count, targetIndex) = fit.coefficients;
end
complexIdentificationPredictions = complexIdentification(:, ...
    complexIdentificationPath(1:maximumFeatures)) * complexCoefficients;

fprintf('[Linear] Evaluating %d targets on the full signal...\n', ...
    numel(targets));
complexFullPredictions = complex(zeros(numel(rows.fullSignal), numel(targets)));
complexFullBuildCount = 0;
for first = 1:cfg.gmp.blockSize:numel(rows.fullSignal)
    local = first:min(first + cfg.gmp.blockSize - 1, numel(rows.fullSignal));
    U = buildGMPRegressorRows(x, rows.fullSignal(local), manager, ...
        complexIdentificationPath(1:maximumFeatures));
    complexFullPredictions(local, :) = U * complexCoefficients;
    complexFullBuildCount = complexFullBuildCount + 1;
end
matrixPassCount.complexFullSignal = 1;

%% PN-IQ: final PN-DOMP fits and restored full-signal prediction
% I and Q are fitted independently; conj(r) restores the original phase.
fprintf('[Linear] Building the PN-IQ identification matrix...\n');
pnIdentification = zeros(numel(rows.identification), effectiveFeatureCount);
for first = 1:cfg.sweep.candidateBlockSize:numel(rows.identification)
    local = first:min(first + cfg.sweep.candidateBlockSize - 1, ...
        numel(rows.identification));
    raw = buildPhaseNormalizedIQRegressors( ...
        x, rows.identification(local), manager, population);
    pnIdentification(local, :) = raw(:, keptFeatureIndices);
end
matrixPassCount.pnIdentification = 1;

identificationRotation = complex(ones(numel(rows.identification), 1));
identificationInput = x(rows.identification);
nonzero = abs(identificationInput) ~= 0;
identificationRotation(nonzero) = ...
    conj(identificationInput(nonzero)) ./ abs(identificationInput(nonzero));
pnIdentificationTarget = identificationRotation .* identificationTarget;

fprintf('[Linear] Computing one PN-IQ PN-DOMP path on identification...\n');
[pnIdentificationPath, ~] = selectDOMPSupport( ...
    pnIdentification, pnIdentificationTarget, maximumFeatures, ...
    cfg.gmp.dompOptions);
pnIdentificationPath = pnIdentificationPath(:);
dompInvocationCount.pnIdentification = 1;
if numel(pnIdentificationPath) < maximumFeatures
    error('run_linear_sweep:EarlyDOMPTermination', ...
        'PN identification DOMP selected %d of %d required features.', ...
        numel(pnIdentificationPath), maximumFeatures);
end

pnCoefficientsI = zeros(maximumFeatures, numel(targets));
pnCoefficientsQ = zeros(maximumFeatures, numel(targets));
for targetIndex = 1:numel(targets)
    count = featureCounts(targetIndex);
    support = pnIdentificationPath(1:count);
    fit = fitIndependentIQGMP(pnIdentification(:, support), ...
        pnIdentificationTarget, pnLambdas(targetIndex), reduction, ...
        "Independent PN-IQ PN-DOMP sweep");
    pnCoefficientsI(1:count, targetIndex) = fit.coefficientsI;
    pnCoefficientsQ(1:count, targetIndex) = fit.coefficientsQ;
end
selectedIdentificationFeatures = pnIdentification(:, ...
    pnIdentificationPath(1:maximumFeatures));
pnIdentificationNormalized = ...
    selectedIdentificationFeatures * pnCoefficientsI + ...
    1j * (selectedIdentificationFeatures * pnCoefficientsQ);
pnIdentificationPredictions = ...
    conj(identificationRotation) .* pnIdentificationNormalized;

selectedMetadata = featureMetadata( ...
    pnIdentificationPath(1:maximumFeatures), :);
pnComplexSupport = unique(selectedMetadata.SourceRegressorIndex, 'stable');
[found, selectedColumns] = ismember( ...
    selectedMetadata.SourceRegressorIndex, pnComplexSupport);
if any(~found)
    error('run_linear_sweep:PNFeatureMapping', ...
        'The PN feature path cannot be mapped to its complex regressors.');
end
isQ = string(selectedMetadata.Component) == "Q";
selectedColumns(isQ) = selectedColumns(isQ) + numel(pnComplexSupport);

pnFullPredictions = complex(zeros(numel(rows.fullSignal), numel(targets)));
pnFullBuildCount = 0;
for first = 1:cfg.gmp.blockSize:numel(rows.fullSignal)
    local = first:min(first + cfg.gmp.blockSize - 1, numel(rows.fullSignal));
    raw = buildPhaseNormalizedIQRegressors( ...
        x, rows.fullSignal(local), manager, pnComplexSupport);
    selectedFeatures = raw(:, selectedColumns);
    predictionNormalized = selectedFeatures * pnCoefficientsI + ...
        1j * (selectedFeatures * pnCoefficientsQ);

    blockInput = x(rows.fullSignal(local));
    blockRotation = complex(ones(numel(local), 1));
    nonzero = abs(blockInput) ~= 0;
    blockRotation(nonzero) = ...
        conj(blockInput(nonzero)) ./ abs(blockInput(nonzero));
    pnFullPredictions(local, :) = ...
        conj(blockRotation) .* predictionNormalized;
    pnFullBuildCount = pnFullBuildCount + 1;
end
matrixPassCount.pnFullSignal = 1;

%% Package supports, metrics, parameters, and FLOPs
% Result rows contain summaries; predictions and supports remain plain arrays.
schema = cfg.sweep.resultSchema;
complexTable = table('Size', [0 numel(schema.names)], ...
    'VariableTypes', schema.types, 'VariableNames', schema.names);
pnTable = complexTable;
complexSupports = cell(numel(targets), 1);
pnFeatureSupports = cell(numel(targets), 1);
pnComplexSupports = cell(numel(targets), 1);
for targetIndex = 1:numel(targets)
    complexSupport = complexIdentificationPath(1:featureCounts(targetIndex));
    complexSupports{targetIndex} = complexSupport;
    operations = countModelOperations(manager.regPopulation, complexSupport);
    complexCost = countModelFLOPs(operations(1, :), getFLOPConvention());
    if complexCost.NumRealParameters ~= targets(targetIndex)
        error('run_linear_sweep:ParameterCostMismatch', ...
            'Complex GMP cost and requested parameter count differ.');
    end
    values = {"Complex GMP DOMP sweep", "Sweep point", ...
        targets(targetIndex), double(complexCost.NumRealParameters), ...
        "Validation-selected Ridge", complexLambdas(targetIndex), ...
        complexValidationNMSE(targetIndex), ...
        nmseComplexDb(identificationTarget, ...
        complexIdentificationPredictions(:, targetIndex)), ...
        nmseComplexDb(fullSignalTarget, complexFullPredictions(:, targetIndex)), ...
        double(complexCost.FLOPsPerSample), targets(targetIndex), 0, NaN, ...
        "Not applicable", NaN, NaN, featureCounts(targetIndex), NaN, ...
        "Not applicable", NaN, NaN, NaN, "linear_sweep.mat"};
    complexTable(targetIndex, :) = ...
        cell2table(values, 'VariableNames', schema.names);

    pnFeatures = pnIdentificationPath(1:featureCounts(targetIndex));
    pnMetadata = featureMetadata(pnFeatures, :);
    supportComplex = unique(pnMetadata.SourceRegressorIndex, 'stable');
    pnFeatureSupports{targetIndex} = pnFeatures;
    pnComplexSupports{targetIndex} = supportComplex;
    pnReduction = struct('effectiveFeatureCount', featureCounts(targetIndex));
    operations = countModelOperations( ...
        manager.regPopulation, supportComplex, pnReduction);
    pnCost = countModelFLOPs(operations(4, :), getFLOPConvention());
    if pnCost.NumRealParameters ~= targets(targetIndex)
        error('run_linear_sweep:ParameterCostMismatch', ...
            'PN-IQ cost and requested parameter count differ.');
    end
    values = {"Independent PN-IQ PN-DOMP sweep", "Sweep point", ...
        targets(targetIndex), double(pnCost.NumRealParameters), ...
        "Validation-selected Ridge", pnLambdas(targetIndex), ...
        pnValidationNMSE(targetIndex), ...
        nmseComplexDb(identificationTarget, ...
        pnIdentificationPredictions(:, targetIndex)), ...
        nmseComplexDb(fullSignalTarget, pnFullPredictions(:, targetIndex)), ...
        double(pnCost.FLOPsPerSample), targets(targetIndex), 0, NaN, ...
        "Not applicable", rawFeatureCount, effectiveFeatureCount, ...
        featureCounts(targetIndex), NaN, "Not applicable", NaN, NaN, ...
        NaN, "linear_sweep.mat"};
    pnTable(targetIndex, :) = ...
        cell2table(values, 'VariableNames', schema.names);
end

sweep.complexTable = complexTable;
sweep.pnTable = pnTable;
sweep.supports = struct('complex', {complexSupports}, ...
    'pnFeatures', {pnFeatureSupports}, 'pnComplex', {pnComplexSupports});
sweep.paths = struct('complexTrain', complexTrainPath, ...
    'complexIdentification', complexIdentificationPath, ...
    'pnTrain', pnTrainPath, 'pnIdentification', pnIdentificationPath);
sweep.lambdas = struct('complex', complexLambdas, 'pn', pnLambdas);
sweep.predictions = struct( ...
    'complexIdentification', complexIdentificationPredictions, ...
    'complexFull', complexFullPredictions, ...
    'pnIdentification', pnIdentificationPredictions, ...
    'pnFull', pnFullPredictions);
sweep.featureMetadata = featureMetadata;
sweep.metadata = struct('candidateFeatures', rawFeatureCount, ...
    'retainedFeatures', effectiveFeatureCount, ...
    'dompInvocationCount', dompInvocationCount, ...
    'matrixPassCount', matrixPassCount, ...
    'fullSignalRegressorBuildCount', struct( ...
    'complex', complexFullBuildCount, 'pn', pnFullBuildCount), ...
    'fullSignalExpectedBlocks', ...
    ceil(numel(rows.fullSignal)/cfg.gmp.blockSize), ...
    'fullSignalUsedForSelection', false, ...
    'fullSignalUsedForFitting', false);
end
