function sweep = run_linear_sweep(x, y, split, cfg)
% run_linear_sweep - Coordinate the two linear model sweeps.
% Complex GMP and independent PN-IQ share one GMP population and split;
% each model owns its DOMP paths, fits, predictions, metrics, and costs.

x = x(:);
y = y(:);
manager = GMP_createRegressorManager(x, y, cfg.gmp);
population = (1:numel(manager.regPopulation)).';

%% Fit the two scientific model families
complexModel = fit_complex_gmp_domp(x, y, split, cfg, manager, population);
pnModel = fit_independent_pniq_domp(x, y, split, cfg, manager, population);




%% Package the shared linear artifact
sweep.complexTable = complexModel.table;
sweep.pnTable = pnModel.table;
sweep.supports = struct('complex', {complexModel.supports}, ...
    'pnFeatures', {pnModel.supports.features}, ...
    'pnComplex', {pnModel.supports.complex});
sweep.paths = struct('complexTrain', complexModel.paths.train, ...
    'complexIdentification', complexModel.paths.identification, ...
    'pnTrain', pnModel.paths.train, ...
    'pnIdentification', pnModel.paths.identification);
sweep.lambdas = struct('complex', complexModel.lambdas, ...
    'pn', pnModel.lambdas);
sweep.predictions = struct( ...
    'complexIdentification', complexModel.predictions.identification, ...
    'complexFull', complexModel.predictions.full, ...
    'pnIdentification', pnModel.predictions.identification, ...
    'pnFull', pnModel.predictions.full);
sweep.featureMetadata = pnModel.featureMetadata;
sweep.metadata = struct( ...
    'candidateFeatures', pnModel.metadata.candidateFeatures, ...
    'retainedFeatures', pnModel.metadata.retainedFeatures, ...
    'dompInvocationCount', struct( ...
    'complexInternalTrain', complexModel.metadata.dompInternalTrain, ...
    'complexIdentification', complexModel.metadata.dompIdentification, ...
    'pnInternalTrain', pnModel.metadata.dompInternalTrain, ...
    'pnIdentification', pnModel.metadata.dompIdentification), ...
    'matrixPassCount', struct( ...
    'complexInternalTrain', complexModel.metadata.matrixInternalTrain, ...
    'complexInternalValidation', ...
    complexModel.metadata.matrixInternalValidation, ...
    'pnInternalTrain', pnModel.metadata.matrixInternalTrain, ...
    'pnInternalValidation', pnModel.metadata.matrixInternalValidation, ...
    'complexIdentification', complexModel.metadata.matrixIdentification, ...
    'pnIdentification', pnModel.metadata.matrixIdentification, ...
    'complexFullSignal', complexModel.metadata.matrixFullSignal, ...
    'pnFullSignal', pnModel.metadata.matrixFullSignal), ...
    'fullSignalRegressorBuildCount', struct( ...
    'complex', complexModel.metadata.fullSignalBuildCount, ...
    'pn', pnModel.metadata.fullSignalBuildCount), ...
    'fullSignalExpectedBlocks', ...
    ceil(numel(split.fullSignalIndices)/cfg.gmp.blockSize), ...
    'fullSignalUsedForSelection', false, ...
    'fullSignalUsedForFitting', false);
end
