function sweep = run_linear_sweep(x, y, split, cfg)
% run_linear_sweep - Fit nested Complex GMP and genuine PN-DOMP curves.
% One maximum path per family and selection domain supplies every target.
% Shared design matrices and full-signal passes are reused across prefixes.

x = x(:);
y = y(:);
[targets, rows] = validateInputs(x, y, split, cfg);
featureTargets = targets/2;
maximumFeatures = max(featureTargets);
maximumComplexTerms = maximumFeatures;
dompInvocationCount = struct('complexInternalTrain', 0, ...
    'complexIdentification', 0, 'pnInternalTrain', 0, ...
    'pnIdentification', 0);
matrixPassCount = struct('complexInternalTrain', 0, ...
    'complexInternalValidation', 0, 'pnInternalTrain', 0, ...
    'pnInternalValidation', 0, 'complexIdentification', 0, ...
    'pnIdentification', 0, 'complexFullSignal', 0, ...
    'pnFullSignal', 0);

%% Build the shared GMP population and internal designs
% Full-signal rows never enter support or lambda selection.
manager = GMP_createRegressorManager(x, y, cfg.gmp);
population = (1:numel(manager.regPopulation)).';
if maximumComplexTerms > numel(population)
    error('run_linear_sweep:InsufficientPopulation', ...
        'The GMP population cannot represent the largest target.');
end
fprintf('[Linear] Building Complex GMP internal matrices...\n');
trainU = buildGMPRegressorRows(x, rows.train, manager, population);
matrixPassCount.complexInternalTrain = ...
    matrixPassCount.complexInternalTrain + 1;
validationU = buildGMPRegressorRows( ...
    x, rows.validation, manager, population);
matrixPassCount.complexInternalValidation = ...
    matrixPassCount.complexInternalValidation + 1;
trainY = y(rows.train);
validationY = y(rows.validation);

%% Select the two maximum internal paths and validation lambdas
% Each lambda belongs to one fixed prefix selected only on internal train.
fprintf('[Linear] Computing one Complex GMP DOMP path on internal train...\n');
[complexTrainPath, ~] = selectDOMPSupport( ...
    trainU, trainY, maximumComplexTerms, cfg.gmp.dompOptions);
dompInvocationCount.complexInternalTrain = ...
    dompInvocationCount.complexInternalTrain + 1;
requireLength(complexTrainPath, maximumComplexTerms, 'complex internal');
[complexLambdas, complexValidationNMSE] = selectComplexLambdas( ...
    trainU, validationU, trainY, validationY, complexTrainPath, ...
    featureTargets, cfg.lambdaGrid);
fprintf('[Linear] Building PN-IQ internal matrices...\n');
trainPN = buildPNDomain(x, rows.train, manager, population, cfg);
matrixPassCount.pnInternalTrain = matrixPassCount.pnInternalTrain + 1;
validationPN = buildPNDomain( ...
    x, rows.validation, manager, population, cfg);
matrixPassCount.pnInternalValidation = ...
    matrixPassCount.pnInternalValidation + 1;
assertSameReduction(trainPN.reduction, validationPN.reduction);
if trainPN.reduction.effectiveFeatureCount < maximumFeatures
    error('run_linear_sweep:InsufficientPNFeatures', ...
        'The retained PN population is smaller than the largest prefix.');
end
fprintf('[Linear] Computing one PN-IQ PN-DOMP path on internal train...\n');
pnTrainSelection = selectSharedIQFeatures(trainPN.features, ...
    trainPN.rotation.*trainY, maximumFeatures, cfg.gmp.dompOptions);
dompInvocationCount.pnInternalTrain = ...
    dompInvocationCount.pnInternalTrain + 1;
pnTrainPath = pnTrainSelection.supportFeatures;
[pnLambdas, pnValidationNMSE] = selectPNLambdas( ...
    trainPN.features, validationPN.features, trainPN.rotation.*trainY, ...
    validationPN.rotation, validationY, pnTrainPath, featureTargets, ...
    cfg.lambdaGrid);

pnReferenceReduction = trainPN.reduction;
clear trainU validationU trainPN validationPN

%% Refit every exact prefix on identification
% A second maximum path is shared by all final fits of each family.
identificationY = y(rows.identification);
fprintf('[Linear] Building the Complex GMP identification matrix...\n');
identificationU = buildGMPRegressorRows( ...
    x, rows.identification, manager, population);
matrixPassCount.complexIdentification = ...
    matrixPassCount.complexIdentification + 1;
fprintf('[Linear] Computing one Complex GMP DOMP path on identification...\n');
[complexIdentificationPath, ~] = ...
    selectDOMPSupport(identificationU, identificationY, ...
    maximumComplexTerms, cfg.gmp.dompOptions);
dompInvocationCount.complexIdentification = ...
    dompInvocationCount.complexIdentification + 1;
requireLength(complexIdentificationPath, maximumComplexTerms, ...
    'complex identification');
complexCoefficients = fitComplexPrefixes( ...
    identificationU, identificationY, complexIdentificationPath, ...
    featureTargets, complexLambdas);
complexIdentificationPredictions = identificationU(:, ...
    complexIdentificationPath(1:maximumFeatures))*complexCoefficients;
fprintf('[Linear] Evaluating %d targets on the full signal...\n', ...
    numel(targets));
[complexFullPredictions, complexFullBuildCount] = predictComplexGrid( ...
    x, rows.fullSignal, manager, ...
    complexIdentificationPath(1:maximumFeatures), complexCoefficients, ...
    cfg.gmp.blockSize);
matrixPassCount.complexFullSignal = ...
    matrixPassCount.complexFullSignal + 1;

fprintf('[Linear] Building the PN-IQ identification matrix...\n');
identificationPN = buildPNDomain( ...
    x, rows.identification, manager, population, cfg);
matrixPassCount.pnIdentification = matrixPassCount.pnIdentification + 1;
assertSameReduction(pnReferenceReduction, identificationPN.reduction);
fprintf('[Linear] Computing one PN-IQ PN-DOMP path on identification...\n');
pnIdentificationSelection = selectSharedIQFeatures( ...
    identificationPN.features, identificationPN.rotation.*identificationY, ...
    maximumFeatures, cfg.gmp.dompOptions);
dompInvocationCount.pnIdentification = ...
    dompInvocationCount.pnIdentification + 1;
pnIdentificationPath = pnIdentificationSelection.supportFeatures;
[pnCoefficientsI, pnCoefficientsQ] = fitPNPrefixes( ...
    identificationPN.features, identificationPN.rotation.*identificationY, ...
    pnIdentificationPath, featureTargets, pnLambdas);
pnIdentificationPredictions = restorePredictions( ...
    identificationPN.features(:, pnIdentificationPath), ...
    pnCoefficientsI, pnCoefficientsQ, identificationPN.rotation);
[pnFullPredictions, pnFullBuildCount] = predictPNGrid( ...
    x, rows.fullSignal, manager, ...
    identificationPN.metadata, pnIdentificationPath, pnCoefficientsI, ...
    pnCoefficientsQ, cfg.gmp.blockSize);
matrixPassCount.pnFullSignal = matrixPassCount.pnFullSignal + 1;

%% Build one canonical table schema and compact artifacts
% Supports and predictions remain arrays; rows contain only scalar summaries.
complexTable = emptyResultTable(cfg);
pnTable = emptyResultTable(cfg);
complexSupports = cell(numel(targets), 1);
pnFeatureSupports = cell(numel(targets), 1);
pnComplexSupports = cell(numel(targets), 1);
for index = 1:numel(targets)
    complexSupport = complexIdentificationPath(1:featureTargets(index));
    complexSupports{index} = complexSupport;
    cost = modelCost(manager.regPopulation, complexSupport, "complex", ...
        NaN, targets(index));
    complexTable(index, :) = makeRow(cfg, ...
        "Complex GMP DOMP sweep", "Sweep point", targets(index), ...
        complexLambdas(index), complexValidationNMSE(index), ...
        identificationY, y(rows.fullSignal), ...
        complexIdentificationPredictions(:, index), ...
        complexFullPredictions(:, index), cost, ...
        [NaN NaN featureTargets(index)]);

    pnFeatures = pnIdentificationPath(1:featureTargets(index));
    pnMetadata = identificationPN.metadata(pnFeatures, :);
    pnComplexSupport = unique(pnMetadata.SourceRegressorIndex, 'stable');
    pnFeatureSupports{index} = pnFeatures;
    pnComplexSupports{index} = pnComplexSupport;
    cost = modelCost(manager.regPopulation, pnComplexSupport, "pn", ...
        featureTargets(index), targets(index));
    pnTable(index, :) = makeRow(cfg, ...
        "Independent PN-IQ PN-DOMP sweep", "Sweep point", ...
        targets(index), pnLambdas(index), pnValidationNMSE(index), ...
        identificationY, y(rows.fullSignal), ...
        pnIdentificationPredictions(:, index), ...
        pnFullPredictions(:, index), cost, ...
        [identificationPN.reduction.rawFeatureCount, ...
        identificationPN.reduction.effectiveFeatureCount, ...
        featureTargets(index)]);
end

sweep.complexTable = complexTable;
sweep.pnTable = pnTable;
sweep.supports = struct('complex', {complexSupports}, ...
    'pnFeatures', {pnFeatureSupports}, 'pnComplex', {pnComplexSupports});
sweep.paths = struct('complexTrain', complexTrainPath, ...
    'complexIdentification', complexIdentificationPath, ...
    'pnTrain', pnTrainPath, 'pnIdentification', pnIdentificationPath);
sweep.lambdas = struct('complex', complexLambdas, 'pn', pnLambdas);
sweep.predictions = struct('complexIdentification', ...
    complexIdentificationPredictions, 'complexFull', complexFullPredictions, ...
    'pnIdentification', pnIdentificationPredictions, ...
    'pnFull', pnFullPredictions);
sweep.featureMetadata = identificationPN.metadata;
sweep.metadata = struct('candidateFeatures', ...
    identificationPN.reduction.rawFeatureCount, 'retainedFeatures', ...
    identificationPN.reduction.effectiveFeatureCount, ...
    'dompInvocationCount', dompInvocationCount, ...
    'matrixPassCount', matrixPassCount, ...
    'fullSignalRegressorBuildCount', struct( ...
    'complex', complexFullBuildCount, 'pn', pnFullBuildCount), ...
    'fullSignalExpectedBlocks', ceil(numel(rows.fullSignal)/cfg.gmp.blockSize), ...
    'fullSignalUsedForSelection', false, ...
    'fullSignalUsedForFitting', false);
end
function [targets, rows] = validateInputs(x, y, split, cfg)
required = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices','fullSignalIndices'};
if numel(x) ~= numel(y) || isempty(x) || any(~isfinite(x)) || ...
        any(~isfinite(y)) || ~all(isfield(split, required))
    error('run_linear_sweep:InvalidInput', ...
        'Finite aligned signals and the complete shared split are required.');
end
targets = double(cfg.sweep.parameterGrid(:).');
if isempty(targets) || any(targets <= 0) || any(mod(targets, 2)) || ...
        ~isequal(targets, unique(targets, 'sorted'))
    error('run_linear_sweep:InvalidGrid', ...
        'Linear targets must be sorted unique positive even integers.');
end
rows = struct('train', split.internalTrainIndices(:), ...
    'validation', split.internalValidationIndices(:), ...
    'identification', split.identificationIndices(:), ...
    'fullSignal', split.fullSignalIndices(:));
end
function domain = buildPNDomain(x, rows, manager, population, cfg)
[probe, details] = buildPhaseNormalizedIQRegressors( ...
    x, rows(1), manager, population);
[~, reduction] = removeStructurallyZeroQFeatures( ...
    probe, details.featureMetadata, 1e-12);
features = zeros(numel(rows), reduction.effectiveFeatureCount);
for first = 1:cfg.sweep.candidateBlockSize:numel(rows)
    local = first:min(first + cfg.sweep.candidateBlockSize - 1, numel(rows));
    raw = buildPhaseNormalizedIQRegressors(x, rows(local), manager, population);
    features(local, :) = raw(:, reduction.keptIndices);
end
domain = struct('features', features, ...
    'rotation', computePhaseNormGMPRotation(x, rows), ...
    'reduction', reduction, ...
    'metadata', reduction.featureMetadata(reduction.keptIndices, :));
end
function [lambdas, nmse] = selectComplexLambdas( ...
    trainU, validationU, trainY, validationY, path, counts, grid)
lambdas = zeros(size(counts));
nmse = zeros(size(counts));
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitComplexGMPGrid(trainU, trainY, support, grid);
    values = arrayfun(@(candidate) nmseComplexDb(validationY, ...
        validationU(:, support)*fit.coefficients(:, candidate)), 1:numel(grid));
    [nmse(index), selected] = min(values);
    lambdas(index) = grid(selected);
end
end
function [lambdas, nmse] = selectPNLambdas(trainF, validationF, ...
    trainTarget, validationRotation, validationY, path, counts, grid)
lambdas = zeros(size(counts));
nmse = zeros(size(counts));
for index = 1:numel(counts)
    support = path(1:counts(index));
    values = zeros(numel(grid), 1);
    for candidate = 1:numel(grid)
        fit = fitIndependentIQGMP(trainF(:, support), trainTarget, ...
            grid(candidate), struct(), "PN-DOMP sweep");
        values(candidate) = nmseComplexDb(validationY, restorePredictions( ...
            validationF(:, support), fit.coefficientsI, ...
            fit.coefficientsQ, validationRotation));
    end
    [nmse(index), selected] = min(values);
    lambdas(index) = grid(selected);
end
end
function coefficients = fitComplexPrefixes(U, target, path, counts, lambdas)
coefficients = complex(zeros(max(counts), numel(counts)));
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitComplexGMPGrid(U, target, support, lambdas(index));
    coefficients(1:counts(index), index) = fit.coefficients;
end
end
function [coefficientsI, coefficientsQ] = fitPNPrefixes( ...
    features, target, path, counts, lambdas)
coefficientsI = zeros(max(counts), numel(counts));
coefficientsQ = coefficientsI;
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitIndependentIQGMP(features(:, support), target, ...
        lambdas(index), struct(), "Independent PN-IQ PN-DOMP sweep");
    coefficientsI(1:counts(index), index) = fit.coefficientsI;
    coefficientsQ(1:counts(index), index) = fit.coefficientsQ;
end
end
function [predictions, buildCount] = predictComplexGrid( ...
    x, rows, manager, support, coefficients, blockSize)
predictions = complex(zeros(numel(rows), size(coefficients, 2)));
buildCount = 0;
for first = 1:blockSize:numel(rows)
    local = first:min(first + blockSize - 1, numel(rows));
    U = buildGMPRegressorRows(x, rows(local), manager, support);
    buildCount = buildCount + 1;
    predictions(local, :) = U*coefficients;
end
end
function [predictions, buildCount] = predictPNGrid( ...
    x, rows, manager, metadata, path, coefficientsI, coefficientsQ, blockSize)
selected = metadata(path, :);
supportComplex = unique(selected.SourceRegressorIndex, 'stable');
[~, columns] = ismember(selected.SourceRegressorIndex, supportComplex);
isQ = string(selected.Component) == "Q";
columns(isQ) = columns(isQ) + numel(supportComplex);
predictions = complex(zeros(numel(rows), size(coefficientsI, 2)));
buildCount = 0;
for first = 1:blockSize:numel(rows)
    local = first:min(first + blockSize - 1, numel(rows));
    [raw, details] = buildPhaseNormalizedIQRegressors( ...
        x, rows(local), manager, supportComplex);
    buildCount = buildCount + 1;
    normalized = raw(:, columns)*coefficientsI + ...
        1j*(raw(:, columns)*coefficientsQ);
    predictions(local, :) = conj(details.phaseRotation).*normalized;
end
end
function prediction = restorePredictions(features, coefficientsI, coefficientsQ, rotation)
prediction = conj(rotation).*(features*coefficientsI + 1j*(features*coefficientsQ));
end
function cost = modelCost(population, support, type, features, parameters)
if type == "complex"
    operations = countModelOperations(population, support);
    row = 1;
else
    reduction = struct('effectiveFeatureCount', features);
    operations = countModelOperations(population, support, reduction);
    row = 4;
end
cost = countModelFLOPs(operations(row, :), getFLOPConvention());
if cost.NumRealParameters ~= parameters
    error('run_linear_sweep:ParameterCostMismatch', ...
        'Analytical cost and requested parameter count differ.');
end
end
function row = makeRow(cfg, model, role, target, lambda, validationNMSE, ...
    identificationY, fullY, identificationPrediction, fullPrediction, ...
    cost, featureCounts)
schema = cfg.sweep.resultSchema;
values = {string(model), string(role), double(target), ...
    double(cost.NumRealParameters), "Validation-selected Ridge", ...
    double(lambda), double(validationNMSE), ...
    nmseComplexDb(identificationY, identificationPrediction), ...
    nmseComplexDb(fullY, fullPrediction), double(cost.FLOPsPerSample), ...
    double(target), 0, NaN, "Not applicable", double(featureCounts(1)), ...
    double(featureCounts(2)), double(featureCounts(3)), ...
    NaN, "Not applicable", NaN, NaN, ...
    NaN, "linear_sweep.mat"};
row = cell2table(values, 'VariableNames', schema.names);
end
function requireLength(path, expected, label)
if numel(path) < expected
    error('run_linear_sweep:EarlyDOMPTermination', ...
        '%s selected %d of %d required entries.', label, numel(path), expected);
end
end
function assertSameReduction(a, b)
if ~isequal(a.keptIndices, b.keptIndices) || ...
        a.effectiveFeatureCount ~= b.effectiveFeatureCount
    error('run_linear_sweep:ReductionMismatch', ...
        'The structural PN-IQ reduction changed between domains.');
end
end
function value = emptyResultTable(cfg)
schema = cfg.sweep.resultSchema;
value = table('Size', [0 numel(schema.names)], ...
    'VariableTypes', schema.types, 'VariableNames', schema.names);
end
