function sweep = runLinearComplexitySweep(x, y, split, cfg)
% runLinearComplexitySweep - Fit nested Complex GMP and genuine PN-DOMP curves.
% One maximum path per selection domain supplies every prefix. The historical
% 344-parameter PN-IQ point remains separate from the genuine PN-DOMP path.

x = x(:);
y = y(:);
[targets, rows] = validateInputs(x, y, split, cfg);
featureTargets = targets/2;
maximumFeatures = max(featureTargets);
maximumComplexTerms = maximumFeatures;
if cfg.sweep.includeHistoricalPNIQReference
    maximumComplexTerms = max( ...
        maximumComplexTerms, cfg.gmp.baseSupportSize);
end

%% Build the shared GMP population and internal designs
% Full-signal rows never enter support or lambda selection.
manager = GMP_createRegressorManager(x, y, cfg.gmp);
population = (1:numel(manager.regPopulation)).';
if maximumComplexTerms > numel(population)
    error('runLinearComplexitySweep:InsufficientPopulation', ...
        'The GMP population cannot represent the largest target.');
end
trainU = buildGMPRegressorRows(x, rows.train, manager, population);
validationU = buildGMPRegressorRows( ...
    x, rows.validation, manager, population);
trainY = y(rows.train);
validationY = y(rows.validation);

%% Select the two maximum internal paths and validation lambdas
% Each lambda belongs to one fixed prefix selected only on internal train.
[complexTrainPath, ~] = selectDOMPSupport( ...
    trainU, trainY, maximumComplexTerms, cfg.gmp.dompOptions);
requireLength(complexTrainPath, maximumComplexTerms, 'complex internal');
[complexLambdas, complexValidationNMSE] = selectComplexLambdas( ...
    trainU, validationU, trainY, validationY, complexTrainPath, ...
    featureTargets, cfg.lambdaGrid);
trainPN = buildPNDomain(x, rows.train, manager, population, cfg);
validationPN = buildPNDomain( ...
    x, rows.validation, manager, population, cfg);
assertSameReduction(trainPN.reduction, validationPN.reduction);
if trainPN.reduction.effectiveFeatureCount < maximumFeatures
    error('runLinearComplexitySweep:InsufficientPNFeatures', ...
        'The retained PN population is smaller than the largest prefix.');
end
pnTrainSelection = selectSharedIQFeatures(trainPN.features, ...
    trainPN.rotation.*trainY, maximumFeatures, cfg.gmp.dompOptions);
pnTrainPath = pnTrainSelection.supportFeatures;
[pnLambdas, pnValidationNMSE] = selectPNLambdas( ...
    trainPN.features, validationPN.features, trainPN.rotation.*trainY, ...
    validationPN.rotation, validationY, pnTrainPath, featureTargets, ...
    cfg.lambdaGrid);

pnReferenceReduction = trainPN.reduction;
clear trainU validationU trainPN validationPN

%% Refit every exact prefix on identification
% A second maximum path is shared by all final fits of each family.
identificationY = y(rows.identification);
identificationU = buildGMPRegressorRows( ...
    x, rows.identification, manager, population);
[complexIdentificationPath, ~] = ...
    selectDOMPSupport(identificationU, identificationY, ...
    maximumComplexTerms, cfg.gmp.dompOptions);
requireLength(complexIdentificationPath, maximumComplexTerms, ...
    'complex identification');
complexCoefficients = fitComplexPrefixes( ...
    identificationU, identificationY, complexIdentificationPath, ...
    featureTargets, complexLambdas);
complexIdentificationPredictions = identificationU(:, ...
    complexIdentificationPath(1:maximumFeatures))*complexCoefficients;
complexFullPredictions = predictComplexGrid(x, rows.fullSignal, manager, ...
    complexIdentificationPath(1:maximumFeatures), complexCoefficients, ...
    cfg.gmp.blockSize);

identificationPN = buildPNDomain( ...
    x, rows.identification, manager, population, cfg);
assertSameReduction(pnReferenceReduction, identificationPN.reduction);
pnIdentificationSelection = selectSharedIQFeatures( ...
    identificationPN.features, identificationPN.rotation.*identificationY, ...
    maximumFeatures, cfg.gmp.dompOptions);
pnIdentificationPath = pnIdentificationSelection.supportFeatures;
[pnCoefficientsI, pnCoefficientsQ] = fitPNPrefixes( ...
    identificationPN.features, identificationPN.rotation.*identificationY, ...
    pnIdentificationPath, featureTargets, pnLambdas);
pnIdentificationPredictions = restorePredictions( ...
    identificationPN.features(:, pnIdentificationPath), ...
    pnCoefficientsI, pnCoefficientsQ, identificationPN.rotation);
pnFullPredictions = predictPNGrid(x, rows.fullSignal, manager, ...
    identificationPN.metadata, pnIdentificationPath, pnCoefficientsI, ...
    pnCoefficientsQ, cfg.gmp.blockSize);

%% Build one canonical table schema and compact artifacts
% Supports and predictions remain arrays; rows contain only scalar summaries.
complexTable = emptyResultTable(cfg);
pnTable = emptyResultTable(cfg);
complexSupports = cell(numel(targets), 1);
pnFeatureSupports = cell(numel(targets), 1);
pnComplexSupports = cell(numel(targets), 1);
for index = 1:numel(targets)
    complexSupport = complexIdentificationPath(1:featureTargets(index));
    complexSupports{index} = complexSupport;
    cost = modelCost(manager.regPopulation, complexSupport, "complex", ...
        NaN, targets(index));
    complexTable(index, :) = makeRow(cfg, ...
        "Complex GMP DOMP sweep", "Sweep point", targets(index), ...
        complexLambdas(index), complexValidationNMSE(index), ...
        identificationY, y(rows.fullSignal), ...
        complexIdentificationPredictions(:, index), ...
        complexFullPredictions(:, index), cost, ...
        [NaN NaN featureTargets(index)]);

    pnFeatures = pnIdentificationPath(1:featureTargets(index));
    pnMetadata = identificationPN.metadata(pnFeatures, :);
    pnComplexSupport = unique(pnMetadata.SourceRegressorIndex, 'stable');
    pnFeatureSupports{index} = pnFeatures;
    pnComplexSupports{index} = pnComplexSupport;
    cost = modelCost(manager.regPopulation, pnComplexSupport, "pn", ...
        featureTargets(index), targets(index));
    pnTable(index, :) = makeRow(cfg, ...
        "Independent PN-IQ PN-DOMP sweep", "Sweep point", ...
        targets(index), pnLambdas(index), pnValidationNMSE(index), ...
        identificationY, y(rows.fullSignal), ...
        pnIdentificationPredictions(:, index), ...
        pnFullPredictions(:, index), cost, ...
        [identificationPN.reduction.rawFeatureCount, ...
        identificationPN.reduction.effectiveFeatureCount, ...
        featureTargets(index)]);
end

historical = runHistorical(x, y, rows, manager, complexTrainPath, ...
    complexIdentificationPath, cfg);
sweep.complexTable = complexTable;
sweep.pnTable = pnTable;
sweep.historicalTable = historical.table;
sweep.comparison344 = comparePN344(pnTable, pnFullPredictions, ...
    pnFeatureSupports, historical, cfg);
sweep.supports = struct('complex', {complexSupports}, ...
    'pnFeatures', {pnFeatureSupports}, 'pnComplex', {pnComplexSupports}, ...
    'historicalTrainComplex', historical.trainSupportComplex, ...
    'historicalComplex', historical.supportComplex);
sweep.paths = struct('complexTrain', complexTrainPath, ...
    'complexIdentification', complexIdentificationPath, ...
    'pnTrain', pnTrainPath, 'pnIdentification', pnIdentificationPath);
sweep.lambdas = struct('complex', complexLambdas, 'pn', pnLambdas, ...
    'historical', historical.lambda);
sweep.predictions = struct('complexIdentification', ...
    complexIdentificationPredictions, 'complexFull', complexFullPredictions, ...
    'pnIdentification', pnIdentificationPredictions, ...
    'pnFull', pnFullPredictions, 'historicalIdentification', ...
    historical.identificationPrediction, 'historicalFull', historical.fullPrediction);
sweep.featureMetadata = identificationPN.metadata;
sweep.historicalMetadata = historical.metadata;
sweep.metadata = struct('candidateFeatures', ...
    identificationPN.reduction.rawFeatureCount, 'retainedFeatures', ...
    identificationPN.reduction.effectiveFeatureCount, ...
    'dompInvocationCount', struct('complexInternalTrain', 1, ...
    'complexIdentification', 1, 'pnInternalTrain', 1, ...
    'pnIdentification', 1), 'fullSignalUsedForSelection', false, ...
    'fullSignalUsedForFitting', false);
end
function [targets, rows] = validateInputs(x, y, split, cfg)
required = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices','fullSignalIndices'};
if numel(x) ~= numel(y) || isempty(x) || any(~isfinite(x)) || ...
        any(~isfinite(y)) || ~all(isfield(split, required))
    error('runLinearComplexitySweep:InvalidInput', ...
        'Finite aligned signals and the complete shared split are required.');
end
targets = double(cfg.sweep.parameterGrid(:).');
if isempty(targets) || any(targets <= 0) || any(mod(targets, 2)) || ...
        ~isequal(targets, unique(targets, 'sorted'))
    error('runLinearComplexitySweep:InvalidGrid', ...
        'Linear targets must be sorted unique positive even integers.');
end
rows = struct('train', split.internalTrainIndices(:), ...
    'validation', split.internalValidationIndices(:), ...
    'identification', split.identificationIndices(:), ...
    'fullSignal', split.fullSignalIndices(:));
end
function domain = buildPNDomain(x, rows, manager, population, cfg)
[probe, details] = buildPhaseNormalizedIQRegressors( ...
    x, rows(1), manager, population);
[~, reduction] = removeStructurallyZeroQFeatures( ...
    probe, details.featureMetadata, 1e-12);
features = zeros(numel(rows), reduction.effectiveFeatureCount);
for first = 1:cfg.sweep.candidateBlockSize:numel(rows)
    local = first:min(first + cfg.sweep.candidateBlockSize - 1, numel(rows));
    raw = buildPhaseNormalizedIQRegressors(x, rows(local), manager, population);
    features(local, :) = raw(:, reduction.keptIndices);
end
domain = struct('features', features, ...
    'rotation', computePhaseNormGMPRotation(x, rows), ...
    'reduction', reduction, ...
    'metadata', reduction.featureMetadata(reduction.keptIndices, :));
end
function [lambdas, nmse] = selectComplexLambdas( ...
    trainU, validationU, trainY, validationY, path, counts, grid)
lambdas = zeros(size(counts));
nmse = zeros(size(counts));
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitComplexGMPGrid(trainU, trainY, support, grid);
    values = arrayfun(@(candidate) nmseComplexDb(validationY, ...
        validationU(:, support)*fit.coefficients(:, candidate)), 1:numel(grid));
    [nmse(index), selected] = min(values);
    lambdas(index) = grid(selected);
end
end
function [lambdas, nmse] = selectPNLambdas(trainF, validationF, ...
    trainTarget, validationRotation, validationY, path, counts, grid)
lambdas = zeros(size(counts));
nmse = zeros(size(counts));
for index = 1:numel(counts)
    support = path(1:counts(index));
    values = zeros(numel(grid), 1);
    for candidate = 1:numel(grid)
        fit = fitIndependentIQGMP(trainF(:, support), trainTarget, ...
            grid(candidate), struct(), "PN-DOMP sweep");
        values(candidate) = nmseComplexDb(validationY, restorePredictions( ...
            validationF(:, support), fit.coefficientsI, ...
            fit.coefficientsQ, validationRotation));
    end
    [nmse(index), selected] = min(values);
    lambdas(index) = grid(selected);
end
end
function coefficients = fitComplexPrefixes(U, target, path, counts, lambdas)
coefficients = complex(zeros(max(counts), numel(counts)));
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitComplexGMPGrid(U, target, support, lambdas(index));
    coefficients(1:counts(index), index) = fit.coefficients;
end
end
function [coefficientsI, coefficientsQ] = fitPNPrefixes( ...
    features, target, path, counts, lambdas)
coefficientsI = zeros(max(counts), numel(counts));
coefficientsQ = coefficientsI;
for index = 1:numel(counts)
    support = path(1:counts(index));
    fit = fitIndependentIQGMP(features(:, support), target, ...
        lambdas(index), struct(), "Independent PN-IQ PN-DOMP sweep");
    coefficientsI(1:counts(index), index) = fit.coefficientsI;
    coefficientsQ(1:counts(index), index) = fit.coefficientsQ;
end
end
function predictions = predictComplexGrid(x, rows, manager, support, coefficients, blockSize)
predictions = complex(zeros(numel(rows), size(coefficients, 2)));
for first = 1:blockSize:numel(rows)
    local = first:min(first + blockSize - 1, numel(rows));
    U = buildGMPRegressorRows(x, rows(local), manager, support);
    predictions(local, :) = U*coefficients;
end
end
function predictions = predictPNGrid( ...
    x, rows, manager, metadata, path, coefficientsI, coefficientsQ, blockSize)
selected = metadata(path, :);
supportComplex = unique(selected.SourceRegressorIndex, 'stable');
[~, columns] = ismember(selected.SourceRegressorIndex, supportComplex);
isQ = string(selected.Component) == "Q";
columns(isQ) = columns(isQ) + numel(supportComplex);
predictions = complex(zeros(numel(rows), size(coefficientsI, 2)));
for first = 1:blockSize:numel(rows)
    local = first:min(first + blockSize - 1, numel(rows));
    [raw, details] = buildPhaseNormalizedIQRegressors( ...
        x, rows(local), manager, supportComplex);
    normalized = raw(:, columns)*coefficientsI + ...
        1j*(raw(:, columns)*coefficientsQ);
    predictions(local, :) = conj(details.phaseRotation).*normalized;
end
end
function prediction = restorePredictions(features, coefficientsI, coefficientsQ, rotation)
prediction = conj(rotation).*(features*coefficientsI + 1j*(features*coefficientsQ));
end
function cost = modelCost(population, support, type, features, parameters)
if type == "complex"
    operations = countModelOperations(population, support);
    row = 1;
else
    reduction = struct('effectiveFeatureCount', features);
    operations = countModelOperations(population, support, reduction);
    row = 4;
end
cost = countModelFLOPs(operations(row, :), getFLOPConvention());
if cost.NumRealParameters ~= parameters
    error('runLinearComplexitySweep:ParameterCostMismatch', ...
        'Analytical cost and requested parameter count differ.');
end
end
function row = makeRow(cfg, model, role, target, lambda, validationNMSE, ...
    identificationY, fullY, identificationPrediction, fullPrediction, ...
    cost, featureCounts)
schema = cfg.sweep.resultSchema;
values = {string(model), string(role), double(target), ...
    double(cost.NumRealParameters), "Validation-selected Ridge", ...
    double(lambda), double(validationNMSE), ...
    nmseComplexDb(identificationY, identificationPrediction), ...
    nmseComplexDb(fullY, fullPrediction), double(cost.FLOPsPerSample), ...
    double(target), 0, NaN, "Not applicable", double(featureCounts(1)), ...
    double(featureCounts(2)), double(featureCounts(3)), ...
    NaN, "Not applicable", NaN, NaN, ...
    NaN, "linear_sweep.mat"};
row = cell2table(values, 'VariableNames', schema.names);
end
function historical = runHistorical( ...
    x, y, rows, manager, trainPath, identificationPath, cfg)
historical = struct('table', emptyResultTable(cfg), ...
    'trainSupportComplex', [], 'supportComplex', [], 'lambda', NaN, ...
    'identificationPrediction', complex([]), 'fullPrediction', complex([]));
historical.metadata = struct();
if ~cfg.sweep.includeHistoricalPNIQReference
    return;
end
baseSupportSize = cfg.gmp.baseSupportSize;
if baseSupportSize ~= 100
    error('runLinearComplexitySweep:HistoricalSupportSize', ...
        'The historical Complex GMP support must contain exactly 100 terms.');
end
requireLength(trainPath, baseSupportSize, 'historical complex internal');
requireLength(identificationPath, baseSupportSize, ...
    'historical complex identification');
trainSupport = trainPath(1:baseSupportSize);
[trainRaw, trainDetails] = buildPhaseNormalizedIQRegressors( ...
    x, rows.train, manager, trainSupport);
[trainFeatures, trainReduction] = removeStructurallyZeroQFeatures( ...
    trainRaw, trainDetails.featureMetadata, 1e-12);
validationRaw = buildPhaseNormalizedIQRegressors( ...
    x, rows.validation, manager, trainSupport);
validationFeatures = validationRaw(:, trainReduction.keptIndices);
trainFeatureCount = size(trainFeatures, 2);
if size(trainRaw, 2) ~= 2*baseSupportSize
    error('runLinearComplexitySweep:HistoricalRawFeatureCount', ...
        'Historical train support must produce 200 raw PN-IQ features.');
end
[lambda, validationNMSE] = selectPNLambdas(trainFeatures, ...
    validationFeatures, trainDetails.phaseRotation.*y(rows.train), ...
    computePhaseNormGMPRotation(x, rows.validation), ...
    y(rows.validation), (1:trainFeatureCount).', trainFeatureCount, ...
    cfg.lambdaGrid);
support = identificationPath(1:baseSupportSize);
[raw, details] = buildPhaseNormalizedIQRegressors( ...
    x, rows.identification, manager, support);
[features, reduction] = removeStructurallyZeroQFeatures( ...
    raw, details.featureMetadata, 1e-12);
effectiveFeatureCount = size(features, 2);
finalRealParameters = 2*effectiveFeatureCount;
if size(raw, 2) ~= 2*baseSupportSize || ...
        effectiveFeatureCount ~= 172 || ...
        finalRealParameters ~= cfg.sweep.historicalReferenceParameters
    error('runLinearComplexitySweep:HistoricalParameterMismatch', ...
        ['Historical DOMP-%d produced %d raw features, %d effective ' ...
        'features, and %d real parameters; expected 100, 200, 172, and 344.'], ...
        numel(support), size(raw, 2), effectiveFeatureCount, ...
        finalRealParameters);
end
fit = fitIndependentIQGMP(features, details.phaseRotation.*y(rows.identification), ...
    lambda, reduction, "Historical PN-IQ full");
identificationPrediction = restorePredictions(features, fit.coefficientsI, ...
    fit.coefficientsQ, details.phaseRotation);
fullPrediction = predictIndependentIQGMP( ...
    x, rows.fullSignal, manager, support, fit, cfg.gmp.blockSize);
cost = modelCost(manager.regPopulation, support, "pn", ...
    effectiveFeatureCount, finalRealParameters);
historical.table = makeRow(cfg, ...
    "Historical PN-IQ full, complex-DOMP-derived", ...
    "Historical reference", cfg.sweep.historicalReferenceParameters, ...
    lambda, validationNMSE, y(rows.identification), ...
    y(rows.fullSignal), identificationPrediction, fullPrediction, cost, ...
    [reduction.rawFeatureCount, reduction.effectiveFeatureCount, ...
    size(features, 2)]);
historical.supportComplex = support;
historical.trainSupportComplex = trainSupport;
historical.lambda = lambda;
historical.identificationPrediction = identificationPrediction;
historical.fullPrediction = fullPrediction;
historical.metadata = struct( ...
    'HistoricalGMPComplexSupportSize', numel(support), ...
    'HistoricalTrainGMPComplexSupportSize', numel(trainSupport), ...
    'HistoricalRawPNFeatures', size(raw, 2), ...
    'HistoricalTrainRawPNFeatures', size(trainRaw, 2), ...
    'HistoricalEffectivePNFeatures', effectiveFeatureCount, ...
    'HistoricalTrainEffectivePNFeatures', trainFeatureCount, ...
    'HistoricalNumRealParameters', finalRealParameters);
end
function comparison = comparePN344(pnTable, pnPredictions, supports, historical, cfg)
comparison = table();
if isempty(historical.table)
    return;
end
index = find(pnTable.ActualRealParameters == ...
    cfg.sweep.historicalReferenceParameters, 1);
if isempty(index)
    return;
end
relativeError = norm(pnPredictions(:, index) - historical.fullPrediction) / ...
    max(norm(historical.fullPrediction), realmin);
comparison = table( ...
    [pnTable.Model(index); historical.table.Model], ...
    [pnTable.SweepRole(index); historical.table.SweepRole], ...
    [pnTable.ActualRealParameters(index); ...
        historical.table.ActualRealParameters], ...
    [pnTable.SelectedLambda(index); historical.table.SelectedLambda], ...
    [pnTable.IdentificationNMSEdB(index); ...
        historical.table.IdentificationNMSEdB], ...
    [pnTable.FullSignalNMSEdB(index); historical.table.FullSignalNMSEdB], ...
    [pnTable.FLOPsPerSample(index); historical.table.FLOPsPerSample], ...
    ["genuine PN-DOMP prefix, " + string(numel(supports{index})) + ...
        " features"; "nonzero PN-IQ features induced by Complex GMP DOMP-100"], ...
    [relativeError; 0], 'VariableNames', {'Model','SweepRole', ...
        'ActualRealParameters','SelectedLambda','IdentificationNMSEdB', ...
        'FullSignalNMSEdB','FLOPsPerSample','SupportDescription', ...
        'FullSignalRelativePredictionError'});
end
function requireLength(path, expected, label)
if numel(path) < expected
    error('runLinearComplexitySweep:EarlyDOMPTermination', ...
        '%s selected %d of %d required entries.', label, numel(path), expected);
end
end
function assertSameReduction(a, b)
if ~isequal(a.keptIndices, b.keptIndices) || ...
        a.effectiveFeatureCount ~= b.effectiveFeatureCount
    error('runLinearComplexitySweep:ReductionMismatch', ...
        'The structural PN-IQ reduction changed between domains.');
end
end
function value = emptyResultTable(cfg)
schema = cfg.sweep.resultSchema;
value = table('Size', [0 numel(schema.names)], ...
    'VariableTypes', schema.types, 'VariableNames', schema.names);
end
