function [flops, convention] = buildLinearComparisonFLOPs( ...
    design, models)
% buildLinearComparisonFLOPs - Build the established six-row FLOP table.
% The function preserves the analytical operation convention and only maps
% the active supports and feature reductions to their published model names.

population = design.gmpManager.regPopulation;
convention = getFLOPConvention();
[baseOperations, ~] = countModelOperations( ...
    population, design.supportBase, design.identification.pnReduction);
[matchedOperations, ~] = countModelOperations( ...
    population, design.supportMatched);
[baseFLOPs, ~] = countModelFLOPs(baseOperations, convention);
[matchedFLOPs, ~] = countModelFLOPs(matchedOperations, convention);

complexBase = baseFLOPs(baseFLOPs.Model == "Complex GMP", :);
complexBase.Model = "Complex GMP DOMP-100";
coupled = baseFLOPs( ...
    baseFLOPs.Model == "Coupled PN-IQ-GMP structure-aware", :);
coupled.Model = "Coupled PN-IQ (shared DOMP-100)";
independent = baseFLOPs( ...
    baseFLOPs.Model == "Independent PN-IQ-GMP", :);
independent.Model = "Independent PN-IQ full";
complexMatched = matchedFLOPs(matchedFLOPs.Model == "Complex GMP", :);
complexMatched.Model = "Complex GMP DOMP parameter-matched";

complexOperations = baseOperations( ...
    baseOperations.Model == "Complex GMP", :);
independentOperations = baseOperations( ...
    baseOperations.Model == "Independent PN-IQ-GMP", :);
noPNSpecification = canonicalSpecification( ...
    "Independent I/Q without PN", models.noPN.realParameters, ...
    complexOperations.FeatureGenerationMultiplications + ...
        2*models.noPN.effectiveRealFeatures, ...
    complexOperations.FeatureGenerationAdditions + ...
        2*max(models.noPN.effectiveRealFeatures-1, 0), ...
    0, 0, 0, 0, complexOperations.SquareRoots, 0, ...
    complexOperations.SquareRoots, false, false);
reducedSpecification = canonicalSpecification( ...
    "Independent PN-IQ reduced DOMP", models.pnReduced.realParameters, ...
    independentOperations.FeatureGenerationMultiplications + ...
        independentOperations.PhaseNormalizationMultiplications + ...
        2*models.pnReduced.effectiveRealFeatures + ...
        independentOperations.PhaseRestorationMultiplications, ...
    independentOperations.FeatureGenerationAdditions + ...
        independentOperations.PhaseNormalizationAdditions + ...
        2*max(models.pnReduced.effectiveRealFeatures-1, 0) + ...
        independentOperations.PhaseRestorationAdditions, ...
    0, 0, 0, 0, independentOperations.SquareRoots, ...
    independentOperations.Divisions, independentOperations.SquareRoots, ...
    true, true);
[customFLOPs, ~] = countModelFLOPs( ...
    [noPNSpecification; reducedSpecification], convention);
flops = [complexBase; coupled; independent; complexMatched; customFLOPs];
end

function specification = canonicalSpecification( ...
    model, parameters, realMultiplications, realAdditions, ...
    complexMultiplications, complexAdditions, activations, ...
    worstCaseExponentials, squareRoots, divisions, absoluteValues, ...
    phaseNormalization, phaseRestoration)
Model = string(model);
NumRealParameters = parameters;
RealMultiplicationsPerSample = realMultiplications;
RealAdditionsPerSample = realAdditions;
ComplexMultiplicationsPerSample = complexMultiplications;
ComplexAdditionsPerSample = complexAdditions;
NumELUPerSample = activations;
NumExpWorstCasePerSample = worstCaseExponentials;
NumSqrtPerSample = squareRoots;
NumRealDivisionsPerSample = divisions;
NumAbsPerSample = absoluteValues;
PhaseNormalizationIncluded = logical(phaseNormalization);
PhaseRestorationIncluded = logical(phaseRestoration);
ComplexityScope = "inference per output sample";
NumRealWeights = parameters;
NumRealBiases = 0;
DenseLayerCoreFLOPs = 0;
OutputLayerCoreFLOPs = 0;
specification = table(Model, NumRealParameters, ...
    RealMultiplicationsPerSample, RealAdditionsPerSample, ...
    ComplexMultiplicationsPerSample, ComplexAdditionsPerSample, ...
    NumELUPerSample, NumExpWorstCasePerSample, NumSqrtPerSample, ...
    NumRealDivisionsPerSample, NumAbsPerSample, ...
    PhaseNormalizationIncluded, PhaseRestorationIncluded, ...
    ComplexityScope, NumRealWeights, NumRealBiases, ...
    DenseLayerCoreFLOPs, OutputLayerCoreFLOPs);
end
