function [U_real, y_real] = complexToCoupledReal( ...
    U_phase_normalized, y_phase_normalized)
% complexToCoupledReal - Embed a complex linear system in coupled real I/Q form.
% The block structure preserves exactly one complex coefficient as two real
% parameters while retaining the required coupling between output channels.

if nargin < 2
    error('complexToCoupledReal:MissingTarget', ...
        ['Both U_phase_normalized and y_phase_normalized must be ' ...
         'provided; y_phase_normalized may be empty.']);
end
if ~isnumeric(U_phase_normalized) || ...
        ~ismatrix(U_phase_normalized) || ...
        isempty(U_phase_normalized) || ...
        any(~isfinite(U_phase_normalized), 'all')
    error('complexToCoupledReal:InvalidMatrix', ...
        'U_phase_normalized must be a non-empty finite numeric matrix.');
end

nRows = size(U_phase_normalized, 1);
if isempty(y_phase_normalized)
    y_real = [];
else
    if ~isnumeric(y_phase_normalized) || ...
            ~isvector(y_phase_normalized) || ...
            numel(y_phase_normalized) ~= nRows || ...
            any(~isfinite(y_phase_normalized))
        error('complexToCoupledReal:InvalidTarget', ...
            ['y_phase_normalized must be a finite vector with one ' ...
             'value per matrix row.']);
    end
    y_phase_normalized = y_phase_normalized(:);
    y_real = [real(y_phase_normalized); imag(y_phase_normalized)];
end

A = real(U_phase_normalized);
B = imag(U_phase_normalized);
U_real = [A, -B; B, A];

if size(U_real, 1) ~= 2*nRows || ...
        size(U_real, 2) ~= 2*size(U_phase_normalized, 2) || ...
        ~isreal(U_real) || any(~isfinite(U_real), 'all')
    error('complexToCoupledReal:InvalidEmbedding', ...
        'The coupled real embedding has invalid dimensions or values.');
end
end
