function evaluation = evaluatePNGMPDOMPModels( ...
    x, y, design, selection, models, cfg)
% evaluatePNGMPDOMPModels - Predict and tabulate the six linear models.
% All supports, lambdas, and coefficients are frozen before full-signal use;
% identification metrics describe the final refit and are secondary results.

identification = design.identification;
fullRows = design.rows.fullSignal;
yFull = y(fullRows);

fullPredictions = struct();
fullPredictions.complexGMP = GMP_blockPredict( ...
    x, design.gmpManager, design.supportBase, ...
    models.complexBase.coefficients(:, 1), cfg.gmp.blockSize, fullRows);
fullPredictions.coupledPNIQ = predictPhaseNormGMPReal( ...
    x, fullRows, design.gmpManager, models.coupled, cfg.gmp.blockSize);
fullPredictions.independentPNIQ = predictIndependentIQGMP( ...
    x, fullRows, design.gmpManager, design.supportBase, ...
    models.pnFull, cfg.gmp.blockSize);
fullPredictions.complexParameterMatched = GMP_blockPredict( ...
    x, design.gmpManager, design.supportMatched, ...
    models.complexMatched.coefficients(:, 1), cfg.gmp.blockSize, fullRows);
fullPredictions.independentNoPN = predictIndependentIQNoPN( ...
    x, fullRows, design.gmpManager, design.supportBase, ...
    models.noPN, cfg.gmp.blockSize);
fullPredictions.independentPNIQReduced = predictIndependentIQGMP( ...
    x, fullRows, design.gmpManager, design.supportBase, ...
    models.pnReduced, cfg.gmp.blockSize);

equivalenceError = assertEquivalent( ...
    fullPredictions.complexGMP, fullPredictions.coupledPNIQ, ...
    yFull, 'full signal', cfg.equivalence);

identificationPredictions = struct();
identificationPredictions.complexGMP = ...
    identification.U(:, design.supportBase) * ...
    models.complexBase.coefficients(:, 1);
identificationPredictions.coupledPNIQ = coupledMatrixPrediction( ...
    identification.pnDetails.phaseRotation .* ...
    identification.U(:, design.supportBase), models.coupled.hReal, ...
    identification.pnDetails.phaseRotation);
identificationPredictions.independentPNIQ = independentMatrixPrediction( ...
    identification.pn, models.pnFull, ...
    identification.pnDetails.phaseRotation);
identificationPredictions.complexParameterMatched = ...
    identification.U(:, design.supportMatched) * ...
    models.complexMatched.coefficients(:, 1);
identificationPredictions.independentNoPN = independentMatrixPrediction( ...
    models.noPNFeatures, models.noPN, ...
    ones(numel(design.rows.identification), 1));
identificationPredictions.independentPNIQReduced = ...
    independentMatrixPrediction( ...
    identification.pn(:, models.reducedSupport), models.pnReduced, ...
    identification.pnDetails.phaseRotation);

Model = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; ...
    "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; ...
    "Independent PN-IQ reduced DOMP"];
SelectionMethod = repmat("DOMP", 6, 1);
NumRealParameters = [2*design.baseSupportSize; ...
    2*design.baseSupportSize; models.pnFull.realParameters; ...
    2*numel(design.supportMatched); models.noPN.realParameters; ...
    models.pnReduced.realParameters];
ParameterMatchedTarget = [NaN; NaN; ...
    design.targetIdentificationParameters; ...
    design.targetIdentificationParameters; NaN; ...
    cfg.reducedRealParameterTarget];
ParameterDifference = NumRealParameters - ParameterMatchedTarget;

metrics = selection.metrics;
indices = selection.indices;
InternalTrainNMSEdB = [ ...
    metrics.complexBaseTrain(indices.complexBase); ...
    metrics.coupledTrain; metrics.pnFullTrain(indices.pnFull); ...
    metrics.complexMatchedTrain(indices.complexMatched); ...
    metrics.noPNTrain(indices.noPN); ...
    metrics.pnReducedTrain(indices.pnReduced)];
InternalValidationNMSEdB = [ ...
    metrics.complexBaseValidation(indices.complexBase); ...
    metrics.coupledValidation; ...
    metrics.pnFullValidation(indices.pnFull); ...
    metrics.complexMatchedValidation(indices.complexMatched); ...
    metrics.noPNValidation(indices.noPN); ...
    metrics.pnReducedValidation(indices.pnReduced)];

identificationValues = struct2cell(identificationPredictions);
fullValues = struct2cell(fullPredictions);
IdentificationNMSEdB = zeros(6, 1);
FullSignalNMSEdB = zeros(6, 1);
for index = 1:6
    IdentificationNMSEdB(index) = nmseComplexDb( ...
        identification.y, identificationValues{index});
    FullSignalNMSEdB(index) = nmseComplexDb(yFull, fullValues{index});
end

lambdas = selection.lambdas;
SelectedLambda = [lambdas.complexBase; lambdas.complexBase; ...
    lambdas.pnFull; lambdas.complexMatched; lambdas.noPN; ...
    lambdas.pnReduced];
DOMPSupportSize = [design.baseSupportSize; design.baseSupportSize; ...
    design.baseSupportSize; numel(design.supportMatched); ...
    design.baseSupportSize; design.reducedFeatureCount];
EffectiveFeatureCount = [design.baseSupportSize; ...
    2*design.baseSupportSize; models.pnFull.effectiveRealFeatures; ...
    numel(design.supportMatched); models.noPN.effectiveRealFeatures; ...
    models.pnReduced.effectiveRealFeatures];
PhaseNormalization = [false; true; true; false; false; true];
IQCoupling = ["complex coefficients"; "coupled complex-equivalent"; ...
    "independent I/Q"; "complex coefficients"; ...
    "independent I/Q"; "independent I/Q"];
RelativePredictionErrorToComplex = [0; equivalenceError; ...
    NaN; NaN; NaN; NaN];

[complexityFLOPs, flopConvention] = ...
    buildLinearComparisonFLOPs(design, models);
FLOPsPerSample = zeros(6, 1);
AdditionalOperationsPerSample = strings(6, 1);
for index = 1:6
    costRow = complexityFLOPs.Model == Model(index);
    if nnz(costRow) ~= 1
        error('evaluatePNGMPDOMPModels:MissingFLOPRow', ...
            'Missing FLOP row for %s.', Model(index));
    end
    FLOPsPerSample(index) = complexityFLOPs.FLOPsPerSample(costRow);
    AdditionalOperationsPerSample(index) = ...
        describeAdditionalOperations(complexityFLOPs(costRow, :));
end

comparisonResults = table(Model, SelectionMethod, NumRealParameters, ...
    ParameterMatchedTarget, ParameterDifference, InternalTrainNMSEdB, ...
    InternalValidationNMSEdB, IdentificationNMSEdB, ...
    FullSignalNMSEdB, SelectedLambda, DOMPSupportSize, ...
    EffectiveFeatureCount, PhaseNormalization, IQCoupling, ...
    RelativePredictionErrorToComplex, FLOPsPerSample, ...
    AdditionalOperationsPerSample);
selectedHyperparameters = table(Model, SelectedLambda, DOMPSupportSize, ...
    InternalValidationNMSEdB, SelectionMethod);

evaluation = struct( ...
    'comparisonResults', comparisonResults, ...
    'selectedHyperparameters', selectedHyperparameters, ...
    'complexityFLOPs', complexityFLOPs, ...
    'flopConvention', flopConvention, ...
    'identificationPredictions', identificationPredictions, ...
    'fullSignalPredictions', fullPredictions, ...
    'equivalenceRelativeError', equivalenceError);
end

function prediction = independentMatrixPrediction(features, fit, rotation)
predictionPN = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
prediction = conj(rotation(:)).*predictionPN;
end

function prediction = coupledMatrixPrediction(UPhase, hReal, rotation)
nRows = size(UPhase, 1);
UReal = [real(UPhase), -imag(UPhase); imag(UPhase), real(UPhase)];
predictionReal = UReal*hReal;
predictionPN = predictionReal(1:nRows) + ...
    1j*predictionReal(nRows+1:end);
prediction = conj(rotation(:)).*predictionPN;
end

function relativeError = assertEquivalent( ...
    reference, candidate, target, domain, tolerances)
relativeError = norm(candidate-reference)/max(norm(reference), realmin);
nmseDifference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if relativeError >= tolerances.relativePredictionTolerance || ...
        nmseDifference >= tolerances.nmseDifferenceToleranceDb
    error('evaluatePNGMPDOMPModels:CoupledEquivalenceFailed', ...
        ['Complex/coupled equivalence failed on %s: relative %.3e, ' ...
        'NMSE difference %.3e dB.'], domain, relativeError, nmseDifference);
end
end
