function models = fitPNGMPDOMPModels(x, design, selection, cfg)
% fitPNGMPDOMPModels - Fit all six frozen linear models on identification.
% Supports and lambdas arrive from the selection stage; this function only
% estimates final coefficients and the reduced identification feature support.

identification = design.identification;
complexBase = fitComplexGMPGrid( ...
    identification.U, identification.y, design.supportBase, ...
    selection.lambdas.complexBase);
complexMatched = fitComplexGMPGrid( ...
    identification.U, identification.y, design.supportMatched, ...
    selection.lambdas.complexMatched);
coupled = mapComplexGMPFitToCoupled( ...
    design.supportBase, complexBase.coefficients(:, 1), ...
    design.populationSize, selection.lambdas.complexBase, ...
    complexBase.normU);
pnFull = fitIndependentIQGMP( ...
    identification.pn, identification.yPN, selection.lambdas.pnFull, ...
    identification.pnReduction, "Independent PN-IQ full");

[noPNRaw, noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, design.rows.identification, design.gmpManager, design.supportBase);
[noPNFeatures, noPNReduction] = reduceStructuralFeatures( ...
    noPNRaw, noPNDetails.featureMetadata, 1e-12);
noPN = fitIndependentIQGMP( ...
    noPNFeatures, identification.y, selection.lambdas.noPN, ...
    noPNReduction, "Independent I/Q without PN");

reducedSelection = selectSharedIQFeatures( ...
    identification.pn, identification.yPN, design.reducedFeatureCount, ...
    cfg.gmp.dompOptions);
reducedSupport = reducedSelection.supportFeatures;
reducedReduction = restrictIQFeatureReduction( ...
    identification.pnReduction, reducedSupport);
pnReduced = fitIndependentIQGMP( ...
    identification.pn(:, reducedSupport), identification.yPN, ...
    selection.lambdas.pnReduced, reducedReduction, ...
    "Independent PN-IQ reduced DOMP");

models = struct( ...
    'complexBase', complexBase, ...
    'complexMatched', complexMatched, ...
    'coupled', coupled, ...
    'pnFull', pnFull, ...
    'noPN', noPN, ...
    'pnReduced', pnReduced, ...
    'noPNFeatures', noPNFeatures, ...
    'noPNReduction', noPNReduction, ...
    'reducedSupport', reducedSupport, ...
    'reducedReduction', reducedReduction, ...
    'reducedSelection', reducedSelection);
end
