function fit = mapComplexGMPFitToCoupled( ...
    support, complexCoefficients, populationSize, lambda, columnNorms)
% mapComplexGMPFitToCoupled - Express a complex GMP fit in coupled I/Q form.
% Each active complex coefficient becomes its real and imaginary component;
% both real columns retain the same complex-regressor normalization.

support = support(:);
complexCoefficients = complexCoefficients(:);
if numel(complexCoefficients) ~= numel(support)
    error('mapComplexGMPFitToCoupled:InvalidCoefficientCount', ...
        'The complex coefficients must match the active GMP support.');
end

fit = struct( ...
    'supportComplex', support, ...
    'supportReal', [support; populationSize + support], ...
    'hReal', [real(complexCoefficients); imag(complexCoefficients)], ...
    'hComplexRecovered', complexCoefficients, ...
    'normUComplex', columnNorms(:), ...
    'lambda', lambda, ...
    'selectionMethod', 'DOMP', ...
    'nComplexTotal', populationSize, ...
    'nActiveComplex', numel(support), ...
    'nActiveReal', 2*numel(support));
end
