function [design, selection] = preparePNGMPDOMPSelection(x, y, split, cfg)
% preparePNGMPDOMPSelection - Build shared matrices, supports, and lambdas.
% Hyperparameters use only the internal identification split. Final complex
% supports are regenerated on all identification rows before coefficient fit.

rows = struct( ...
    'train', split.internalTrainIndices, ...
    'validation', split.internalValidationIndices, ...
    'identification', split.identificationIndices, ...
    'fullSignal', split.fullSignalIndices);
gmpManager = GMP_createRegressorManager(x, y, cfg.gmp);
populationSize = numel(gmpManager.regPopulation);
population = (1:populationSize).';
baseSupportSize = cfg.gmp.maxPopulation;
maximumPathSize = min(2*baseSupportSize, populationSize);

train = struct();
validation = struct();
train.U = buildGMPRegressorRows(x, rows.train, gmpManager, population);
validation.U = buildGMPRegressorRows( ...
    x, rows.validation, gmpManager, population);
train.y = y(rows.train);
validation.y = y(rows.validation);
[trainPath, trainPathHistory] = selectDOMPSupport( ...
    train.U, train.y, maximumPathSize, cfg.gmp.dompOptions);
requirePathLength(trainPath, baseSupportSize, 'internal train base');
supportTrainBase = trainPath(1:baseSupportSize);

[train.pnRaw, train.pnDetails] = buildPhaseNormalizedIQRegressors( ...
    x, rows.train, gmpManager, supportTrainBase);
[train.pn, train.pnReduction] = removeStructurallyZeroQFeatures( ...
    train.pnRaw, train.pnDetails.featureMetadata, 1e-12);
[validation.pnRaw, validation.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.validation, gmpManager, supportTrainBase);
validation.pn = validation.pnRaw(:, train.pnReduction.keptIndices);
train.yPN = train.pnDetails.phaseRotation .* train.y;
validation.yPN = validation.pnDetails.phaseRotation .* validation.y;
targetTrainParameters = 2*size(train.pn, 2);

complexBaseGrid = fitComplexGMPGrid( ...
    train.U, train.y, supportTrainBase, cfg.lambdaGrid);
[metrics.complexBaseTrain, metrics.complexBaseValidation] = ...
    complexGridNMSE(train.U, validation.U, train.y, validation.y, ...
    complexBaseGrid);
indexComplexBase = bestLambda(metrics.complexBaseValidation);
lambdas.complexBase = cfg.lambdaGrid(indexComplexBase);
indices.complexBase = indexComplexBase;

[metrics.pnFullTrain, metrics.pnFullValidation] = independentGridNMSE( ...
    train.pn, validation.pn, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, train.pnReduction, ...
    "Independent PN-IQ full");
indices.pnFull = bestLambda(metrics.pnFullValidation);
lambdas.pnFull = cfg.lambdaGrid(indices.pnFull);

[train.noPNRaw, train.noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, rows.train, gmpManager, supportTrainBase);
[train.noPN, train.noPNReduction] = reduceStructuralFeatures( ...
    train.noPNRaw, train.noPNDetails.featureMetadata, 1e-12);
validation.noPNRaw = buildUnnormalizedIQRegressors( ...
    x, rows.validation, gmpManager, supportTrainBase);
validation.noPN = validation.noPNRaw(:, train.noPNReduction.keptIndices);
[metrics.noPNTrain, metrics.noPNValidation] = independentGridNMSE( ...
    train.noPN, validation.noPN, train.y, ...
    ones(numel(rows.train), 1), ones(numel(rows.validation), 1), ...
    train.y, validation.y, cfg.lambdaGrid, train.noPNReduction, ...
    "Independent I/Q without PN");
indices.noPN = bestLambda(metrics.noPNValidation);
lambdas.noPN = cfg.lambdaGrid(indices.noPN);

reducedFeatureCount = floor(cfg.reducedRealParameterTarget/2);
reducedTrainSelection = selectSharedIQFeatures( ...
    train.pn, train.yPN, reducedFeatureCount, cfg.gmp.dompOptions);
train.pnReduced = train.pn(:, reducedTrainSelection.supportFeatures);
validation.pnReduced = validation.pn( ...
    :, reducedTrainSelection.supportFeatures);
reducedTrainReduction = restrictIQFeatureReduction( ...
    train.pnReduction, reducedTrainSelection.supportFeatures);
[metrics.pnReducedTrain, metrics.pnReducedValidation] = ...
    independentGridNMSE( ...
    train.pnReduced, validation.pnReduced, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, reducedTrainReduction, ...
    "Independent PN-IQ reduced DOMP");
indices.pnReduced = bestLambda(metrics.pnReducedValidation);
lambdas.pnReduced = cfg.lambdaGrid(indices.pnReduced);

complexTrainCoefficients = ...
    complexBaseGrid.coefficients(:, indexComplexBase);
coupledTrainFit = mapComplexGMPFitToCoupled( ...
    supportTrainBase, complexTrainCoefficients, populationSize, ...
    lambdas.complexBase, complexBaseGrid.normU);
trainComplexPrediction = ...
    train.U(:, supportTrainBase)*complexTrainCoefficients;
validationComplexPrediction = ...
    validation.U(:, supportTrainBase)*complexTrainCoefficients;
trainCoupledPrediction = coupledMatrixPrediction( ...
    train.pnDetails.phaseRotation.*train.U(:, supportTrainBase), ...
    coupledTrainFit.hReal, train.pnDetails.phaseRotation);
validationCoupledPrediction = coupledMatrixPrediction( ...
    validation.pnDetails.phaseRotation.* ...
    validation.U(:, supportTrainBase), coupledTrainFit.hReal, ...
    validation.pnDetails.phaseRotation);
assertEquivalent(trainComplexPrediction, trainCoupledPrediction, ...
    train.y, 'internal train', cfg.equivalence);
assertEquivalent(validationComplexPrediction, ...
    validationCoupledPrediction, validation.y, ...
    'internal validation', cfg.equivalence);
metrics.coupledTrain = nmseComplexDb(train.y, trainCoupledPrediction);
metrics.coupledValidation = nmseComplexDb( ...
    validation.y, validationCoupledPrediction);

identification = struct();
identification.U = buildGMPRegressorRows( ...
    x, rows.identification, gmpManager, population);
identification.y = y(rows.identification);
[identificationPath, identificationPathHistory] = selectDOMPSupport( ...
    identification.U, identification.y, maximumPathSize, ...
    cfg.gmp.dompOptions);
requirePathLength(identificationPath, baseSupportSize, ...
    'identification base');
supportBase = identificationPath(1:baseSupportSize);

[identification.pnRaw, identification.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.identification, gmpManager, supportBase);
[identification.pn, identification.pnReduction] = ...
    removeStructurallyZeroQFeatures(identification.pnRaw, ...
    identification.pnDetails.featureMetadata, 1e-12);
identification.yPN = ...
    identification.pnDetails.phaseRotation .* identification.y;
targetIdentificationParameters = 2*size(identification.pn, 2);
matchedSupportSize = ceil(targetIdentificationParameters/2);
requirePathLength(trainPath, matchedSupportSize, ...
    'internal train parameter match');
requirePathLength(identificationPath, matchedSupportSize, ...
    'identification parameter match');
supportTrainMatched = trainPath(1:matchedSupportSize);
supportMatched = identificationPath(1:matchedSupportSize);

complexMatchedGrid = fitComplexGMPGrid( ...
    train.U, train.y, supportTrainMatched, cfg.lambdaGrid);
[metrics.complexMatchedTrain, metrics.complexMatchedValidation] = ...
    complexGridNMSE(train.U, validation.U, train.y, validation.y, ...
    complexMatchedGrid);
lambdas.complexMatched = cfg.lambdaGrid( ...
    bestLambda(metrics.complexMatchedValidation));
indices.complexMatched = bestLambda(metrics.complexMatchedValidation);

design = struct( ...
    'rows', rows, ...
    'gmpManager', gmpManager, ...
    'populationSize', populationSize, ...
    'baseSupportSize', baseSupportSize, ...
    'train', train, ...
    'validation', validation, ...
    'identification', identification, ...
    'supportTrainBase', supportTrainBase, ...
    'supportBase', supportBase, ...
    'supportTrainMatched', supportTrainMatched, ...
    'supportMatched', supportMatched, ...
    'trainPathHistory', trainPathHistory, ...
    'identificationPathHistory', identificationPathHistory, ...
    'reducedTrainSelection', reducedTrainSelection, ...
    'reducedFeatureCount', reducedFeatureCount, ...
    'targetTrainParameters', targetTrainParameters, ...
    'targetIdentificationParameters', targetIdentificationParameters);
selection = struct( ...
    'lambdas', lambdas, 'indices', indices, 'metrics', metrics);
end

function index = bestLambda(validationNMSE)
[~, index] = min(validationNMSE);
end

function [trainNMSE, validationNMSE] = complexGridNMSE( ...
    UTrain, UValidation, yTrain, yValidation, fit)
nLambdas = numel(fit.lambdaGrid);
trainNMSE = zeros(nLambdas, 1);
validationNMSE = zeros(nLambdas, 1);
for index = 1:nLambdas
    coefficients = fit.coefficients(:, index);
    trainNMSE(index) = nmseComplexDb( ...
        yTrain, UTrain(:, fit.support)*coefficients);
    validationNMSE(index) = nmseComplexDb( ...
        yValidation, UValidation(:, fit.support)*coefficients);
end
end

function [trainNMSE, validationNMSE] = independentGridNMSE( ...
    trainFeatures, validationFeatures, trainTarget, trainRotation, ...
    validationRotation, yTrain, yValidation, lambdaGrid, reduction, ...
    modelName)
nLambdas = numel(lambdaGrid);
trainNMSE = zeros(nLambdas, 1);
validationNMSE = zeros(nLambdas, 1);
for index = 1:nLambdas
    fit = fitIndependentIQGMP(trainFeatures, trainTarget, ...
        lambdaGrid(index), reduction, modelName);
    trainPrediction = independentMatrixPrediction( ...
        trainFeatures, fit, trainRotation);
    validationPrediction = independentMatrixPrediction( ...
        validationFeatures, fit, validationRotation);
    trainNMSE(index) = nmseComplexDb(yTrain, trainPrediction);
    validationNMSE(index) = nmseComplexDb( ...
        yValidation, validationPrediction);
end
end

function prediction = independentMatrixPrediction(features, fit, rotation)
predictionPN = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
prediction = conj(rotation(:)).*predictionPN;
end

function prediction = coupledMatrixPrediction(UPhase, hReal, rotation)
nRows = size(UPhase, 1);
UReal = [real(UPhase), -imag(UPhase); imag(UPhase), real(UPhase)];
predictionReal = UReal*hReal;
predictionPN = predictionReal(1:nRows) + ...
    1j*predictionReal(nRows+1:end);
prediction = conj(rotation(:)).*predictionPN;
end

function assertEquivalent(reference, candidate, target, domain, tolerances)
relativeError = norm(candidate-reference)/max(norm(reference), realmin);
nmseDifference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if relativeError >= tolerances.relativePredictionTolerance || ...
        nmseDifference >= tolerances.nmseDifferenceToleranceDb
    error('preparePNGMPDOMPSelection:CoupledEquivalenceFailed', ...
        ['Complex/coupled equivalence failed on %s: relative %.3e, ' ...
        'NMSE difference %.3e dB.'], domain, relativeError, nmseDifference);
end
end

function requirePathLength(path, requiredLength, stage)
if numel(path) < requiredLength
    error('preparePNGMPDOMPSelection:ShortDOMPPath', ...
        'DOMP produced %d terms for %s; %d are required.', ...
        numel(path), stage, requiredLength);
end
end
