function study = runPNGMPDOMPStudy(x, y, split, cfg)
% runPNGMPDOMPStudy - Fit the six linear DOMP comparison models.
% Hyperparameters use the internal identification split. Final supports and
% coefficients use all identification rows; evaluation uses the full signal.

study_timer = tic;
x = x(:);
y = y(:);
if isempty(x) || numel(x) ~= numel(y) || ...
        any(~isfinite(x)) || any(~isfinite(y))
    error('runPNGMPDOMPStudy:InvalidSignals', ...
        'Modeled-block X and Y must be finite vectors of equal length.');
end

INTERNAL_TRAIN = split.internalTrainIndices;
INTERNAL_VALIDATION = split.internalValidationIndices;
IDENTIFICATION = split.identificationIndices;
FULL_SIGNAL = split.fullSignalIndices;
required_split_fields = {'internalTrainIndices', ...
    'internalValidationIndices','identificationIndices', ...
    'fullSignalIndices'};
if ~all(isfield(split, required_split_fields)) || ...
        ~all(ismember(IDENTIFICATION, FULL_SIGNAL)) || ...
        ~all(ismember(INTERNAL_TRAIN, IDENTIFICATION)) || ...
        ~all(ismember(INTERNAL_VALIDATION, IDENTIFICATION)) || ...
        ~isequal(FULL_SIGNAL(:), (1:numel(x)).')
    error('runPNGMPDOMPStudy:InvalidSplit', ...
        'The supplied identification/full-signal protocol is invalid.');
end
gmp_manager = GMP_createRegressorManager(x, y, cfg.gmp);
n_population = numel(gmp_manager.regPopulation);
population_indices = (1:n_population).';
base_support_size = cfg.gmp.maxPopulation;
maximum_path_size = min(2*base_support_size, n_population);

% Hyperparameter-selection domain: DOMP support uses INTERNAL_TRAIN only.
U_train = buildGMPRegressorRows( ...
    x, INTERNAL_TRAIN, gmp_manager, population_indices);
U_val = buildGMPRegressorRows( ...
    x, INTERNAL_VALIDATION, gmp_manager, population_indices);
y_train = y(INTERNAL_TRAIN);
y_val = y(INTERNAL_VALIDATION);
[train_path, train_path_history] = selectDOMPSupport( ...
    U_train, y_train, maximum_path_size, cfg.gmp.dompOptions);
if numel(train_path) < base_support_size
    error('run_article_experiment:ShortTrainDOMPPath', ...
        'DOMP did not produce the required base support on INTERNAL_TRAIN.');
end
support_train_base = train_path(1:base_support_size);

[pn_raw_train, pn_train_details] = buildPhaseNormalizedIQRegressors( ...
    x, INTERNAL_TRAIN, gmp_manager, support_train_base);
[pn_train, pn_train_reduction] = removeStructurallyZeroQFeatures( ...
    pn_raw_train, pn_train_details.featureMetadata, 1e-12);
[pn_raw_val, pn_val_details] = buildPhaseNormalizedIQRegressors( ...
    x, INTERNAL_VALIDATION, gmp_manager, support_train_base);
pn_val = pn_raw_val(:, pn_train_reduction.keptIndices);
y_pn_train = pn_train_details.phaseRotation .* y_train;
y_pn_val = pn_val_details.phaseRotation .* y_val;
target_independent_parameters = 2*size(pn_train, 2);

% Select one lambda per linear model using the common grid and INTERNAL_VALIDATION only.
complex_base_train_grid = fitComplexGMPGrid( ...
    U_train, y_train, support_train_base, cfg.lambdaGrid);
[complex_base_train_nmse, complex_base_val_nmse] = ...
    complexGridNMSE(U_train, U_val, y_train, y_val, ...
    complex_base_train_grid);
index_complex_base = selectLambdaIndex(complex_base_val_nmse);
lambda_complex_base = cfg.lambdaGrid(index_complex_base);

[~, pn_full_train_nmse, pn_full_val_nmse] = ...
    independentGridNMSE(pn_train, pn_val, y_pn_train, y_pn_val, ...
    pn_train_details.phaseRotation, pn_val_details.phaseRotation, ...
    y_train, y_val, cfg.lambdaGrid, pn_train_reduction, ...
    "Independent PN-IQ full");
index_pn_full = selectLambdaIndex(pn_full_val_nmse);
lambda_pn_full = cfg.lambdaGrid(index_pn_full);

[no_pn_raw_train, no_pn_train_details] = ...
    buildUnnormalizedIQRegressors( ...
    x, INTERNAL_TRAIN, gmp_manager, support_train_base);
[no_pn_train, no_pn_train_reduction] = reduceStructuralFeatures( ...
    no_pn_raw_train, no_pn_train_details.featureMetadata, 1e-12);
no_pn_raw_val = buildUnnormalizedIQRegressors( ...
    x, INTERNAL_VALIDATION, gmp_manager, support_train_base);
no_pn_val = no_pn_raw_val(:, no_pn_train_reduction.keptIndices);
[~, no_pn_train_nmse, no_pn_val_nmse] = ...
    independentGridNMSE(no_pn_train, no_pn_val, y_train, y_val, ...
    ones(numel(INTERNAL_TRAIN), 1), ones(numel(INTERNAL_VALIDATION), 1), y_train, y_val, ...
    cfg.lambdaGrid, no_pn_train_reduction, ...
    "Independent I/Q without PN");
index_no_pn = selectLambdaIndex(no_pn_val_nmse);
lambda_no_pn = cfg.lambdaGrid(index_no_pn);

reduced_feature_count = floor(cfg.reducedRealParameterTarget/2);
reduced_train_selection = selectSharedIQFeatures( ...
    pn_train, y_pn_train, reduced_feature_count, cfg.gmp.dompOptions);
pn_reduced_train = pn_train(:, ...
    reduced_train_selection.supportFeatures);
pn_reduced_val = pn_val(:, reduced_train_selection.supportFeatures);
pn_reduced_train_reduction = buildSelectedReduction( ...
    pn_train_reduction, reduced_train_selection.supportFeatures);
[~, pn_reduced_train_nmse, pn_reduced_val_nmse] = ...
    independentGridNMSE(pn_reduced_train, pn_reduced_val, ...
    y_pn_train, y_pn_val, pn_train_details.phaseRotation, ...
    pn_val_details.phaseRotation, y_train, y_val, cfg.lambdaGrid, ...
    pn_reduced_train_reduction, "Independent PN-IQ reduced DOMP");
index_pn_reduced = selectLambdaIndex(pn_reduced_val_nmse);
lambda_pn_reduced = cfg.lambdaGrid(index_pn_reduced);

% Coupled PN-IQ maps the already fitted complex coefficients exactly.
U_pn_train = pn_train_details.phaseRotation .* U_train;
U_pn_val = pn_val_details.phaseRotation .* U_val;
h_complex_train = complex_base_train_grid.coefficients( ...
    :, index_complex_base);
coupled_train_fit = mapComplexFitToCoupled( ...
    support_train_base, h_complex_train, n_population, ...
    lambda_complex_base, complex_base_train_grid.normU);
yhat_complex_train = U_train(:, support_train_base) * ...
    complex_base_train_grid.coefficients(:, index_complex_base);
yhat_complex_val = U_val(:, support_train_base) * ...
    complex_base_train_grid.coefficients(:, index_complex_base);
yhat_coupled_train = coupledMatrixPrediction( ...
    U_pn_train(:, support_train_base), ...
    coupled_train_fit.hReal, pn_train_details.phaseRotation);
yhat_coupled_val = coupledMatrixPrediction( ...
    U_pn_val(:, support_train_base), ...
    coupled_train_fit.hReal, pn_val_details.phaseRotation);
assertEquivalent(yhat_complex_train, yhat_coupled_train, ...
    y_train, 'INTERNAL_TRAIN');
assertEquivalent(yhat_complex_val, yhat_coupled_val, y_val, 'INTERNAL_VALIDATION');
coupled_train_nmse = nmseComplexDb(y_train, yhat_coupled_train);
coupled_val_nmse = nmseComplexDb(y_val, yhat_coupled_val);

% Final support regeneration and coefficient fitting use IDENTIFICATION only.
U_fit = buildGMPRegressorRows( ...
    x, IDENTIFICATION, gmp_manager, population_indices);
y_fit = y(IDENTIFICATION);
[fit_path, fit_path_history] = selectDOMPSupport( ...
    U_fit, y_fit, maximum_path_size, cfg.gmp.dompOptions);
supportDOMP = fit_path(1:base_support_size);

[pn_raw_fit, pn_fit_details] = buildPhaseNormalizedIQRegressors( ...
    x, IDENTIFICATION, gmp_manager, supportDOMP);
[pn_fit, pn_fit_reduction] = removeStructurallyZeroQFeatures( ...
    pn_raw_fit, pn_fit_details.featureMetadata, 1e-12);
y_pn_fit = pn_fit_details.phaseRotation .* y_fit;
final_independent_parameters = 2*size(pn_fit, 2);
matched_complex_size = ceil(final_independent_parameters/2);
if numel(train_path) < matched_complex_size || ...
        numel(fit_path) < matched_complex_size
    error('runPNGMPDOMPStudy:ShortParameterMatchedDOMPPath', ...
        ['A DOMP path is shorter than the final parameter-matched ' ...
        'support of %d complex regressors.'], matched_complex_size);
end
support_train_matched = train_path(1:matched_complex_size);
supportParameterMatchedDOMP = fit_path(1:matched_complex_size);

% Select the matched-model lambda using the exact final parameter count.
complex_matched_train_grid = fitComplexGMPGrid( ...
    U_train, y_train, support_train_matched, cfg.lambdaGrid);
[complex_matched_train_nmse, complex_matched_val_nmse] = ...
    complexGridNMSE(U_train, U_val, y_train, y_val, ...
    complex_matched_train_grid);
index_complex_matched = selectLambdaIndex(complex_matched_val_nmse);
lambda_complex_matched = cfg.lambdaGrid(index_complex_matched);

complex_base_final = fitComplexGMPGrid( ...
    U_fit, y_fit, supportDOMP, lambda_complex_base);
complex_matched_final = fitComplexGMPGrid( ...
    U_fit, y_fit, supportParameterMatchedDOMP, ...
    lambda_complex_matched);
coupled_final_fit = mapComplexFitToCoupled( ...
    supportDOMP, complex_base_final.coefficients(:, 1), ...
    n_population, lambda_complex_base, complex_base_final.normU);
pn_full_final_fit = fitIndependentIQGMP( ...
    pn_fit, y_pn_fit, lambda_pn_full, pn_fit_reduction, ...
    "Independent PN-IQ full");

[no_pn_raw_fit, no_pn_fit_details] = buildUnnormalizedIQRegressors( ...
    x, IDENTIFICATION, gmp_manager, supportDOMP);
[no_pn_fit_features, no_pn_fit_reduction] = reduceStructuralFeatures( ...
    no_pn_raw_fit, no_pn_fit_details.featureMetadata, 1e-12);
no_pn_final_fit = fitIndependentIQGMP( ...
    no_pn_fit_features, y_fit, lambda_no_pn, no_pn_fit_reduction, ...
    "Independent I/Q without PN");

reduced_fit_selection = selectSharedIQFeatures( ...
    pn_fit, y_pn_fit, reduced_feature_count, cfg.gmp.dompOptions);
reducedFeatureSupportDOMP = reduced_fit_selection.supportFeatures;
pn_reduced_fit_reduction = buildSelectedReduction( ...
    pn_fit_reduction, reducedFeatureSupportDOMP);
pn_reduced_final_fit = fitIndependentIQGMP( ...
    pn_fit(:, reducedFeatureSupportDOMP), y_pn_fit, ...
    lambda_pn_reduced, pn_reduced_fit_reduction, ...
    "Independent PN-IQ reduced DOMP");

% Evaluate the complete signal after all hyperparameters and supports freeze.
y_full_signal = y(FULL_SIGNAL);
yhat_complex_full_signal = GMP_blockPredict(x, gmp_manager, supportDOMP, ...
    complex_base_final.coefficients(:, 1), cfg.gmp.blockSize, FULL_SIGNAL);
yhat_coupled_full_signal = predictPhaseNormGMPReal( ...
    x, FULL_SIGNAL, gmp_manager, coupled_final_fit, cfg.gmp.blockSize);
yhat_pn_full_full_signal = predictIndependentIQGMP( ...
    x, FULL_SIGNAL, gmp_manager, supportDOMP, pn_full_final_fit, ...
    cfg.gmp.blockSize);
yhat_complex_matched_full_signal = GMP_blockPredict( ...
    x, gmp_manager, supportParameterMatchedDOMP, ...
    complex_matched_final.coefficients(:, 1), cfg.gmp.blockSize, FULL_SIGNAL);
yhat_no_pn_full_signal = predictIndependentIQNoPN( ...
    x, FULL_SIGNAL, gmp_manager, supportDOMP, no_pn_final_fit, ...
    cfg.gmp.blockSize);
yhat_pn_reduced_full_signal = predictIndependentIQGMP( ...
    x, FULL_SIGNAL, gmp_manager, supportDOMP, pn_reduced_final_fit, ...
    cfg.gmp.blockSize);
assertEquivalent(yhat_complex_full_signal, yhat_coupled_full_signal, ...
    y_full_signal, 'full signal');

% IDENTIFICATION metrics describe the final refit but are not the primary result.
yhat_complex_fit = U_fit(:, supportDOMP) * ...
    complex_base_final.coefficients(:, 1);
yhat_coupled_fit = coupledMatrixPrediction( ...
    pn_fit_details.phaseRotation .* U_fit(:, supportDOMP), ...
    coupled_final_fit.hReal, pn_fit_details.phaseRotation);
yhat_pn_full_fit = independentMatrixPrediction( ...
    pn_fit, pn_full_final_fit, pn_fit_details.phaseRotation);
yhat_complex_matched_fit = U_fit(:, supportParameterMatchedDOMP) * ...
    complex_matched_final.coefficients(:, 1);
yhat_no_pn_fit = independentMatrixPrediction( ...
    no_pn_fit_features, no_pn_final_fit, ones(numel(IDENTIFICATION), 1));
yhat_pn_reduced_fit = independentMatrixPrediction( ...
    pn_fit(:, reducedFeatureSupportDOMP), pn_reduced_final_fit, ...
    pn_fit_details.phaseRotation);

Model = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; ...
    "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; ...
    "Independent PN-IQ reduced DOMP"];
SelectionMethod = repmat("DOMP", 6, 1);
NumRealParameters = [2*base_support_size; 2*base_support_size; ...
    pn_full_final_fit.realParameters; ...
    2*matched_complex_size; no_pn_final_fit.realParameters; ...
    pn_reduced_final_fit.realParameters];
ParameterMatchedTarget = [NaN; NaN; final_independent_parameters; ...
    final_independent_parameters; NaN; cfg.reducedRealParameterTarget];
ParameterDifference = NumRealParameters - ParameterMatchedTarget;
InternalTrainNMSEdB = [complex_base_train_nmse(index_complex_base); ...
    coupled_train_nmse; pn_full_train_nmse(index_pn_full); ...
    complex_matched_train_nmse(index_complex_matched); ...
    no_pn_train_nmse(index_no_pn); ...
    pn_reduced_train_nmse(index_pn_reduced)];
InternalValidationNMSEdB = [complex_base_val_nmse(index_complex_base); ...
    coupled_val_nmse; pn_full_val_nmse(index_pn_full); ...
    complex_matched_val_nmse(index_complex_matched); ...
    no_pn_val_nmse(index_no_pn); ...
    pn_reduced_val_nmse(index_pn_reduced)];
identification_predictions = {yhat_complex_fit; yhat_coupled_fit; ...
    yhat_pn_full_fit; yhat_complex_matched_fit; yhat_no_pn_fit; ...
    yhat_pn_reduced_fit};
full_signal_predictions = {yhat_complex_full_signal; ...
    yhat_coupled_full_signal; yhat_pn_full_full_signal; ...
    yhat_complex_matched_full_signal; yhat_no_pn_full_signal; ...
    yhat_pn_reduced_full_signal};
IdentificationNMSEdB = zeros(6, 1);
FullSignalNMSEdB = zeros(6, 1);
for model_index = 1:6
    IdentificationNMSEdB(model_index) = nmseComplexDb( ...
        y_fit, identification_predictions{model_index});
    FullSignalNMSEdB(model_index) = nmseComplexDb( ...
        y_full_signal, full_signal_predictions{model_index});
end
SelectedLambda = [lambda_complex_base; lambda_complex_base; ...
    lambda_pn_full; lambda_complex_matched; lambda_no_pn; ...
    lambda_pn_reduced];
DOMPSupportSize = [base_support_size; base_support_size; ...
    base_support_size; matched_complex_size; base_support_size; ...
    reduced_feature_count];
EffectiveFeatureCount = [base_support_size; 2*base_support_size; ...
    pn_full_final_fit.effectiveRealFeatures; matched_complex_size; ...
    no_pn_final_fit.effectiveRealFeatures; ...
    pn_reduced_final_fit.effectiveRealFeatures];
PhaseNormalization = [false; true; true; false; false; true];
IQCoupling = ["complex coefficients"; "coupled complex-equivalent"; ...
    "independent I/Q"; "complex coefficients"; ...
    "independent I/Q"; "independent I/Q"];
RelativePredictionErrorToComplex = [0; ...
    relativePredictionError(yhat_complex_full_signal, ...
    yhat_coupled_full_signal); ...
    NaN; NaN; NaN; NaN];

[complexity_flops, flop_convention] = buildModelFLOPs( ...
    gmp_manager.regPopulation, supportDOMP, ...
    supportParameterMatchedDOMP, pn_fit_reduction, ...
    no_pn_final_fit, pn_reduced_final_fit);
FLOPsPerSample = zeros(6, 1);
AdditionalOperationsPerSample = strings(6, 1);
for model_index = 1:6
    cost_row = complexity_flops.Model == Model(model_index);
    if nnz(cost_row) ~= 1
        error('run_article_experiment:MissingFLOPRow', ...
            'Missing FLOP row for %s.', Model(model_index));
    end
    FLOPsPerSample(model_index) = ...
        complexity_flops.FLOPsPerSample(cost_row);
    AdditionalOperationsPerSample(model_index) = ...
        describeAdditionalOperations(complexity_flops(cost_row, :));
end

comparison_results = table(Model, SelectionMethod, NumRealParameters, ...
    ParameterMatchedTarget, ParameterDifference, InternalTrainNMSEdB, ...
    InternalValidationNMSEdB, IdentificationNMSEdB, ...
    FullSignalNMSEdB, SelectedLambda, DOMPSupportSize, ...
    EffectiveFeatureCount, PhaseNormalization, IQCoupling, ...
    RelativePredictionErrorToComplex, FLOPsPerSample, ...
    AdditionalOperationsPerSample);

[regressor_structure_summary, ~] = analyzeRegressorStructure( ...
    gmp_manager.regPopulation, supportDOMP);

selected_hyperparameters = table(Model, SelectedLambda, DOMPSupportSize, ...
    InternalValidationNMSEdB, SelectionMethod);

history_labels = ["INTERNAL_TRAIN complex path"; "IDENTIFICATION complex path"; ...
    "INTERNAL_TRAIN reduced PN-IQ"; "IDENTIFICATION reduced PN-IQ"];
history_tables = {summarizeDOMPHistory(train_path_history); ...
    summarizeDOMPHistory(fit_path_history); ...
    summarizeDOMPHistory(reduced_train_selection.dompHistory); ...
    summarizeDOMPHistory(reduced_fit_selection.dompHistory)};
domp_history_summary = vertcat(history_tables{:});
domp_history_summary = addvars(domp_history_summary, history_labels, ...
    'Before', 1, 'NewVariableNames', 'Stage');

study = struct();
study.comparisonResults = comparison_results;
study.complexityFLOPs = complexity_flops;
study.flopConvention = flop_convention;
study.selectedHyperparameters = selected_hyperparameters;
study.dompHistorySummary = domp_history_summary;
study.regressorStructureSummary = regressor_structure_summary;
study.supports = struct( ...
    'supportDOMP', supportDOMP, ...
    'supportParameterMatchedDOMP', supportParameterMatchedDOMP, ...
    'reducedFeatureSupportDOMP', reducedFeatureSupportDOMP, ...
    'supportTrainBase', support_train_base, ...
    'supportTrainParameterMatched', support_train_matched);
study.dompHistories = struct( ...
    'internalTrainComplex', train_path_history, ...
    'identificationComplex', fit_path_history, ...
    'internalTrainReducedPNIQ', reduced_train_selection.dompHistory, ...
    'identificationReducedPNIQ', reduced_fit_selection.dompHistory);
study.identificationPredictions = predictionStruct( ...
    identification_predictions);
study.fullSignalPredictions = predictionStruct(full_signal_predictions);
study.targetIndependentPNIQParameters = final_independent_parameters;
study.internalTrainIndependentPNIQParameters = ...
    target_independent_parameters;
study.populationSize = n_population;
study.equivalenceRelativeError = RelativePredictionErrorToComplex(2);
study.totalTimeSeconds = toc(study_timer);
end

function index = selectLambdaIndex(validation_nmse)
[~, index] = min(validation_nmse);
end

function [train_nmse, validation_nmse] = complexGridNMSE( ...
    U_train, U_val, y_train, y_val, fit)
n_lambdas = numel(fit.lambdaGrid);
train_nmse = zeros(n_lambdas, 1);
validation_nmse = zeros(n_lambdas, 1);
for index = 1:n_lambdas
    h = fit.coefficients(:, index);
    train_nmse(index) = nmseComplexDb( ...
        y_train, U_train(:, fit.support)*h);
    validation_nmse(index) = nmseComplexDb( ...
        y_val, U_val(:, fit.support)*h);
end
end

function [fits, train_nmse, validation_nmse] = independentGridNMSE( ...
    features_train, features_val, target_train, ~, rotation_train, ...
    rotation_val, y_train, y_val, lambda_grid, reduction, model_name)
n_lambdas = numel(lambda_grid);
fits = cell(n_lambdas, 1);
train_nmse = zeros(n_lambdas, 1);
validation_nmse = zeros(n_lambdas, 1);
for index = 1:n_lambdas
    fits{index} = fitIndependentIQGMP(features_train, target_train, ...
        lambda_grid(index), reduction, model_name);
    yhat_train = independentMatrixPrediction( ...
        features_train, fits{index}, rotation_train);
    yhat_val = independentMatrixPrediction( ...
        features_val, fits{index}, rotation_val);
    train_nmse(index) = nmseComplexDb(y_train, yhat_train);
    validation_nmse(index) = nmseComplexDb(y_val, yhat_val);
end
end

function yhat = independentMatrixPrediction(features, fit, rotation)
yhat_phase = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
yhat = conj(rotation(:)) .* yhat_phase;
end

function yhat = coupledMatrixPrediction(U_phase, h_real, rotation)
n_rows = size(U_phase, 1);
U_real = [real(U_phase), -imag(U_phase); ...
    imag(U_phase), real(U_phase)];
prediction_real = U_real*h_real;
prediction_phase = prediction_real(1:n_rows) + ...
    1j*prediction_real(n_rows+1:end);
yhat = conj(rotation(:)) .* prediction_phase;
end

function fit = mapComplexFitToCoupled( ...
    support, h_complex, n_population, lambda, normU)
support = support(:);
h_complex = h_complex(:);
if numel(h_complex) ~= numel(support)
    error('run_article_experiment:InvalidComplexMapping', ...
        'The complex coefficient vector must match the DOMP support.');
end
fit = struct();
fit.supportComplex = support;
fit.supportReal = [support; n_population + support];
fit.hReal = [real(h_complex); imag(h_complex)];
fit.hComplexRecovered = h_complex;
fit.normUComplex = normU(:);
fit.lambda = lambda;
fit.selectionMethod = 'DOMP';
fit.nComplexTotal = n_population;
fit.nActiveComplex = numel(support);
fit.nActiveReal = 2*numel(support);
end

function reduction = buildSelectedReduction(base_reduction, local_support)
local_support = double(local_support(:));
reduction = base_reduction;
reduction.keptIndices = base_reduction.keptIndices(local_support);
reduction.effectiveFeatureCount = numel(local_support);
reduction.groupSupportFeatures = local_support;
reduction.selectionMethod = 'DOMP';
end

function assertEquivalent(reference, candidate, target, domain)
relative_error = relativePredictionError(reference, candidate);
nmse_difference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if relative_error >= 1e-10 || nmse_difference >= 1e-9
    error('run_article_experiment:CoupledEquivalenceFailed', ...
        ['Complex/coupled equivalence failed on %s: relative %.3e, ' ...
         'NMSE difference %.3e dB.'], domain, relative_error, ...
        nmse_difference);
end
end

function value = relativePredictionError(reference, candidate)
value = norm(candidate-reference)/max(norm(reference), realmin);
end

function [flops, convention] = buildModelFLOPs( ...
    population, support_base, support_matched, pn_reduction, ...
    no_pn_fit, reduced_fit)
convention = getFLOPConvention();
[operations_base, ~] = countModelOperations( ...
    population, support_base, pn_reduction);
[operations_matched, ~] = countModelOperations( ...
    population, support_matched);
[flops_base, ~] = countModelFLOPs(operations_base, convention);
[flops_matched, ~] = countModelFLOPs(operations_matched, convention);

complex_base = flops_base(flops_base.Model == "Complex GMP", :);
complex_base.Model = "Complex GMP DOMP-100";
coupled = flops_base( ...
    flops_base.Model == "Coupled PN-IQ-GMP structure-aware", :);
coupled.Model = "Coupled PN-IQ (shared DOMP-100)";
independent = flops_base( ...
    flops_base.Model == "Independent PN-IQ-GMP", :);
independent.Model = "Independent PN-IQ full";
complex_parameter_matched = flops_matched( ...
    flops_matched.Model == "Complex GMP", :);
complex_parameter_matched.Model = ...
    "Complex GMP DOMP parameter-matched";

complex_operation_row = operations_base( ...
    operations_base.Model == "Complex GMP", :);
independent_operation_row = operations_base( ...
    operations_base.Model == "Independent PN-IQ-GMP", :);
no_pn_spec = canonicalSpecification( ...
    "Independent I/Q without PN", no_pn_fit.realParameters, ...
    complex_operation_row.FeatureGenerationMultiplications + ...
        2*no_pn_fit.effectiveRealFeatures, ...
    complex_operation_row.FeatureGenerationAdditions + ...
        2*max(no_pn_fit.effectiveRealFeatures-1, 0), ...
    0, 0, 0, 0, complex_operation_row.SquareRoots, 0, ...
    complex_operation_row.SquareRoots, false, false);
reduced_spec = canonicalSpecification( ...
    "Independent PN-IQ reduced DOMP", reduced_fit.realParameters, ...
    independent_operation_row.FeatureGenerationMultiplications + ...
        independent_operation_row.PhaseNormalizationMultiplications + ...
        2*reduced_fit.effectiveRealFeatures + ...
        independent_operation_row.PhaseRestorationMultiplications, ...
    independent_operation_row.FeatureGenerationAdditions + ...
        independent_operation_row.PhaseNormalizationAdditions + ...
        2*max(reduced_fit.effectiveRealFeatures-1, 0) + ...
        independent_operation_row.PhaseRestorationAdditions, ...
    0, 0, 0, 0, independent_operation_row.SquareRoots, ...
    independent_operation_row.Divisions, ...
    independent_operation_row.SquareRoots, true, true);
[custom_flops, ~] = countModelFLOPs([no_pn_spec; reduced_spec], convention);
flops = [complex_base; coupled; independent; ...
    complex_parameter_matched; custom_flops];
end

function specification = canonicalSpecification( ...
    model, parameters, real_multiplications, real_additions, ...
    complex_multiplications, complex_additions, elu, exp_worst, ...
    square_roots, divisions, absolute_values, phase_normalization, ...
    phase_restoration)
Model = string(model);
NumRealParameters = parameters;
RealMultiplicationsPerSample = real_multiplications;
RealAdditionsPerSample = real_additions;
ComplexMultiplicationsPerSample = complex_multiplications;
ComplexAdditionsPerSample = complex_additions;
NumELUPerSample = elu;
NumExpWorstCasePerSample = exp_worst;
NumSqrtPerSample = square_roots;
NumRealDivisionsPerSample = divisions;
NumAbsPerSample = absolute_values;
PhaseNormalizationIncluded = logical(phase_normalization);
PhaseRestorationIncluded = logical(phase_restoration);
ComplexityScope = "inference per output sample";
NumRealWeights = parameters;
NumRealBiases = 0;
DenseLayerCoreFLOPs = 0;
OutputLayerCoreFLOPs = 0;
specification = table(Model, NumRealParameters, ...
    RealMultiplicationsPerSample, RealAdditionsPerSample, ...
    ComplexMultiplicationsPerSample, ComplexAdditionsPerSample, ...
    NumELUPerSample, NumExpWorstCasePerSample, NumSqrtPerSample, ...
    NumRealDivisionsPerSample, NumAbsPerSample, ...
    PhaseNormalizationIncluded, PhaseRestorationIncluded, ...
    ComplexityScope, NumRealWeights, NumRealBiases, ...
    DenseLayerCoreFLOPs, OutputLayerCoreFLOPs);
end

function predictions = predictionStruct(values)
predictions = struct( ...
    'complexGMP', values{1}, ...
    'coupledPNIQ', values{2}, ...
    'independentPNIQ', values{3}, ...
    'complexParameterMatched', values{4}, ...
    'independentNoPN', values{5}, ...
    'independentPNIQReduced', values{6});
end

function description = describeAdditionalOperations(row)
parts = strings(0, 1);
if row.NumAbsPerSample > 0
    if row.NumSqrtPerSample == row.NumAbsPerSample
        parts(end+1) = sprintf('%d magnitude (including %d sqrt)', ...
            row.NumAbsPerSample, row.NumSqrtPerSample);
    else
        parts(end+1) = sprintf('%d magnitude', row.NumAbsPerSample);
    end
end
if row.NumSqrtPerSample > 0 && ...
        row.NumSqrtPerSample ~= row.NumAbsPerSample
    parts(end+1) = sprintf('%d sqrt', row.NumSqrtPerSample);
end
if row.NumRealDivisionsPerSample > 0
    parts(end+1) = sprintf('%d division', ...
        row.NumRealDivisionsPerSample);
end
if row.NumELUPerSample > 0
    parts(end+1) = sprintf('%d ELU', row.NumELUPerSample);
end
if row.NumExpWorstCasePerSample > 0
    parts(end+1) = sprintf('up to %d exp', ...
        row.NumExpWorstCasePerSample);
end
if row.PhaseNormalizationIncluded
    parts(end+1) = ...
        "phase normalization/restoration arithmetic in FLOPs";
end
if isempty(parts)
    description = "none";
else
    description = strjoin(parts, ', ');
end
end
