function study = runPNGMPDOMPStudy(x, y, split, cfg)
% runPNGMPDOMPStudy - Fit and evaluate the six linear DOMP models.
% Lambda selection uses the internal split; supports and coefficients are
% then regenerated on all identification rows before full-signal evaluation.

studyTimer = tic;
x = x(:);
y = y(:);
requiredFields = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices','fullSignalIndices'};
if numel(x) ~= numel(y) || ~all(isfield(split, requiredFields)) || ...
        ~all(ismember(split.identificationIndices, split.fullSignalIndices))
    error('runPNGMPDOMPStudy:InvalidInput', ...
        'Signals and the shared comparison split are inconsistent.');
end

rows.train = split.internalTrainIndices;
rows.validation = split.internalValidationIndices;
rows.identification = split.identificationIndices;
rows.fullSignal = split.fullSignalIndices;
manager = GMP_createRegressorManager(x, y, cfg.gmp);
populationSize = numel(manager.regPopulation);
population = (1:populationSize).';
baseSupportSize = cfg.gmp.maxPopulation;
maximumPathSize = min(2*baseSupportSize, populationSize);

%% Internal selection domain
train.U = buildGMPRegressorRows(x, rows.train, manager, population);
train.y = y(rows.train);
validation.U = buildGMPRegressorRows( ...
    x, rows.validation, manager, population);
validation.y = y(rows.validation);
[trainPath, trainPathHistory] = selectDOMPSupport( ...
    train.U, train.y, maximumPathSize, cfg.gmp.dompOptions);
requirePathLength(trainPath, baseSupportSize, 'internal train base');
supportTrainBase = trainPath(1:baseSupportSize);

[train.pnRaw, train.pnDetails] = buildPhaseNormalizedIQRegressors( ...
    x, rows.train, manager, supportTrainBase);
[train.pn, train.pnReduction] = removeStructurallyZeroQFeatures( ...
    train.pnRaw, train.pnDetails.featureMetadata, 1e-12);
[validation.pnRaw, validation.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.validation, manager, supportTrainBase);
validation.pn = validation.pnRaw(:, train.pnReduction.keptIndices);
train.yPN = train.pnDetails.phaseRotation .* train.y;
validation.yPN = validation.pnDetails.phaseRotation .* validation.y;

[complexBaseGrid, metrics.complexBaseTrain, ...
    metrics.complexBaseValidation, indices.complexBase, ...
    lambdas.complexBase] = selectComplexLambda( ...
    train.U, validation.U, train.y, validation.y, ...
    supportTrainBase, cfg.lambdaGrid);
[metrics.pnFullTrain, metrics.pnFullValidation, ...
    indices.pnFull, lambdas.pnFull] = selectIndependentLambda( ...
    train.pn, validation.pn, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, train.pnReduction, ...
    "Independent PN-IQ full");

[train.noPNRaw, train.noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, rows.train, manager, supportTrainBase);
[train.noPN, train.noPNReduction] = reduceStructuralFeatures( ...
    train.noPNRaw, train.noPNDetails.featureMetadata, 1e-12);
validation.noPNRaw = buildUnnormalizedIQRegressors( ...
    x, rows.validation, manager, supportTrainBase);
validation.noPN = validation.noPNRaw(:, train.noPNReduction.keptIndices);
[metrics.noPNTrain, metrics.noPNValidation, ...
    indices.noPN, lambdas.noPN] = selectIndependentLambda( ...
    train.noPN, validation.noPN, train.y, ...
    ones(numel(rows.train), 1), ones(numel(rows.validation), 1), ...
    train.y, validation.y, cfg.lambdaGrid, train.noPNReduction, ...
    "Independent I/Q without PN");

reducedFeatureCount = floor(cfg.reducedRealParameterTarget/2);
reducedTrainSelection = selectSharedIQFeatures( ...
    train.pn, train.yPN, reducedFeatureCount, cfg.gmp.dompOptions);
train.pnReduced = train.pn(:, reducedTrainSelection.supportFeatures);
validation.pnReduced = validation.pn( ...
    :, reducedTrainSelection.supportFeatures);
reducedTrainReduction = restrictReduction( ...
    train.pnReduction, reducedTrainSelection.supportFeatures);
[metrics.pnReducedTrain, metrics.pnReducedValidation, ...
    indices.pnReduced, lambdas.pnReduced] = selectIndependentLambda( ...
    train.pnReduced, validation.pnReduced, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, reducedTrainReduction, ...
    "Independent PN-IQ reduced DOMP");

trainComplexCoefficients = ...
    complexBaseGrid.coefficients(:, indices.complexBase);
trainCoupled = mapComplexFit(supportTrainBase, ...
    trainComplexCoefficients, populationSize, lambdas.complexBase, ...
    complexBaseGrid.normU);
trainComplexPrediction = ...
    train.U(:, supportTrainBase)*trainComplexCoefficients;
validationComplexPrediction = ...
    validation.U(:, supportTrainBase)*trainComplexCoefficients;
trainCoupledPrediction = coupledPrediction( ...
    train.pnDetails.phaseRotation.*train.U(:, supportTrainBase), ...
    trainCoupled.hReal, train.pnDetails.phaseRotation);
validationCoupledPrediction = coupledPrediction( ...
    validation.pnDetails.phaseRotation.* ...
    validation.U(:, supportTrainBase), trainCoupled.hReal, ...
    validation.pnDetails.phaseRotation);
assertEquivalent(trainComplexPrediction, trainCoupledPrediction, ...
    train.y, 'internal train', cfg.equivalence);
assertEquivalent(validationComplexPrediction, ...
    validationCoupledPrediction, validation.y, ...
    'internal validation', cfg.equivalence);
metrics.coupledTrain = nmseComplexDb(train.y, trainCoupledPrediction);
metrics.coupledValidation = nmseComplexDb( ...
    validation.y, validationCoupledPrediction);

%% Final support and coefficient estimation on all identification rows
identification.U = buildGMPRegressorRows( ...
    x, rows.identification, manager, population);
identification.y = y(rows.identification);
[identificationPath, identificationPathHistory] = selectDOMPSupport( ...
    identification.U, identification.y, maximumPathSize, ...
    cfg.gmp.dompOptions);
requirePathLength(identificationPath, baseSupportSize, ...
    'identification base');
supportBase = identificationPath(1:baseSupportSize);

[identification.pnRaw, identification.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.identification, manager, supportBase);
[identification.pn, identification.pnReduction] = ...
    removeStructurallyZeroQFeatures(identification.pnRaw, ...
    identification.pnDetails.featureMetadata, 1e-12);
identification.yPN = ...
    identification.pnDetails.phaseRotation .* identification.y;
targetParameters = 2*size(identification.pn, 2);
matchedSupportSize = ceil(targetParameters/2);
requirePathLength(trainPath, matchedSupportSize, ...
    'internal train parameter match');
requirePathLength(identificationPath, matchedSupportSize, ...
    'identification parameter match');
supportTrainMatched = trainPath(1:matchedSupportSize);
supportMatched = identificationPath(1:matchedSupportSize);
[~, metrics.complexMatchedTrain, metrics.complexMatchedValidation, ...
    indices.complexMatched, lambdas.complexMatched] = ...
    selectComplexLambda(train.U, validation.U, train.y, validation.y, ...
    supportTrainMatched, cfg.lambdaGrid);

complexBase = fitComplexGMPGrid(identification.U, identification.y, ...
    supportBase, lambdas.complexBase);
complexMatched = fitComplexGMPGrid( ...
    identification.U, identification.y, ...
    supportMatched, lambdas.complexMatched);
coupled = mapComplexFit(supportBase, complexBase.coefficients(:, 1), ...
    populationSize, lambdas.complexBase, complexBase.normU);
pnFull = fitIndependentIQGMP( ...
    identification.pn, identification.yPN, lambdas.pnFull, ...
    identification.pnReduction, "Independent PN-IQ full");

[noPNRaw, noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, rows.identification, manager, supportBase);
[noPNFeatures, noPNReduction] = reduceStructuralFeatures( ...
    noPNRaw, noPNDetails.featureMetadata, 1e-12);
noPN = fitIndependentIQGMP(noPNFeatures, identification.y, ...
    lambdas.noPN, noPNReduction, "Independent I/Q without PN");

reducedSelection = selectSharedIQFeatures( ...
    identification.pn, identification.yPN, reducedFeatureCount, ...
    cfg.gmp.dompOptions);
reducedSupport = reducedSelection.supportFeatures;
reducedReduction = restrictReduction( ...
    identification.pnReduction, reducedSupport);
pnReduced = fitIndependentIQGMP( ...
    identification.pn(:, reducedSupport), identification.yPN, ...
    lambdas.pnReduced, reducedReduction, ...
    "Independent PN-IQ reduced DOMP");

%% Identification and full-signal predictions
yFull = y(rows.fullSignal);
fullPredictions.complexGMP = GMP_blockPredict( ...
    x, manager, supportBase, complexBase.coefficients(:, 1), ...
    cfg.gmp.blockSize, rows.fullSignal);
fullPredictions.coupledPNIQ = predictPhaseNormGMPReal( ...
    x, rows.fullSignal, manager, coupled, cfg.gmp.blockSize);
fullPredictions.independentPNIQ = predictIndependentIQGMP( ...
    x, rows.fullSignal, manager, supportBase, pnFull, cfg.gmp.blockSize);
fullPredictions.complexParameterMatched = GMP_blockPredict( ...
    x, manager, supportMatched, complexMatched.coefficients(:, 1), ...
    cfg.gmp.blockSize, rows.fullSignal);
fullPredictions.independentNoPN = predictIndependentIQNoPN( ...
    x, rows.fullSignal, manager, supportBase, noPN, cfg.gmp.blockSize);
fullPredictions.independentPNIQReduced = predictIndependentIQGMP( ...
    x, rows.fullSignal, manager, supportBase, pnReduced, cfg.gmp.blockSize);
equivalenceError = assertEquivalent(fullPredictions.complexGMP, ...
    fullPredictions.coupledPNIQ, yFull, 'full signal', cfg.equivalence);

identificationPredictions.complexGMP = ...
    identification.U(:, supportBase)*complexBase.coefficients(:, 1);
identificationPredictions.coupledPNIQ = coupledPrediction( ...
    identification.pnDetails.phaseRotation.* ...
    identification.U(:, supportBase), coupled.hReal, ...
    identification.pnDetails.phaseRotation);
identificationPredictions.independentPNIQ = independentPrediction( ...
    identification.pn, pnFull, identification.pnDetails.phaseRotation);
identificationPredictions.complexParameterMatched = ...
    identification.U(:, supportMatched)*complexMatched.coefficients(:, 1);
identificationPredictions.independentNoPN = independentPrediction( ...
    noPNFeatures, noPN, ones(numel(rows.identification), 1));
identificationPredictions.independentPNIQReduced = ...
    independentPrediction(identification.pn(:, reducedSupport), ...
    pnReduced, identification.pnDetails.phaseRotation);

%% Result and operation tables
Model = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; "Independent PN-IQ reduced DOMP"];
SelectionMethod = repmat("DOMP", 6, 1);
NumRealParameters = [2*baseSupportSize; 2*baseSupportSize; ...
    pnFull.realParameters; 2*numel(supportMatched); ...
    noPN.realParameters; pnReduced.realParameters];
ParameterMatchedTarget = [NaN; NaN; targetParameters; ...
    targetParameters; NaN; cfg.reducedRealParameterTarget];
ParameterDifference = NumRealParameters - ParameterMatchedTarget;
InternalTrainNMSEdB = [metrics.complexBaseTrain(indices.complexBase); ...
    metrics.coupledTrain; metrics.pnFullTrain(indices.pnFull); ...
    metrics.complexMatchedTrain(indices.complexMatched); ...
    metrics.noPNTrain(indices.noPN); ...
    metrics.pnReducedTrain(indices.pnReduced)];
InternalValidationNMSEdB = [ ...
    metrics.complexBaseValidation(indices.complexBase); ...
    metrics.coupledValidation; metrics.pnFullValidation(indices.pnFull); ...
    metrics.complexMatchedValidation(indices.complexMatched); ...
    metrics.noPNValidation(indices.noPN); ...
    metrics.pnReducedValidation(indices.pnReduced)];

identificationValues = { ...
    identificationPredictions.complexGMP; ...
    identificationPredictions.coupledPNIQ; ...
    identificationPredictions.independentPNIQ; ...
    identificationPredictions.complexParameterMatched; ...
    identificationPredictions.independentNoPN; ...
    identificationPredictions.independentPNIQReduced};
fullValues = { ...
    fullPredictions.complexGMP; ...
    fullPredictions.coupledPNIQ; ...
    fullPredictions.independentPNIQ; ...
    fullPredictions.complexParameterMatched; ...
    fullPredictions.independentNoPN; ...
    fullPredictions.independentPNIQReduced};
IdentificationNMSEdB = zeros(6, 1);
FullSignalNMSEdB = zeros(6, 1);
for index = 1:6
    IdentificationNMSEdB(index) = ...
        nmseComplexDb(identification.y, identificationValues{index});
    FullSignalNMSEdB(index) = nmseComplexDb(yFull, fullValues{index});
end

SelectedLambda = [lambdas.complexBase; lambdas.complexBase; ...
    lambdas.pnFull; lambdas.complexMatched; lambdas.noPN; ...
    lambdas.pnReduced];
DOMPSupportSize = [baseSupportSize; baseSupportSize; baseSupportSize; ...
    numel(supportMatched); baseSupportSize; reducedFeatureCount];
EffectiveFeatureCount = [baseSupportSize; 2*baseSupportSize; ...
    pnFull.effectiveRealFeatures; numel(supportMatched); ...
    noPN.effectiveRealFeatures; pnReduced.effectiveRealFeatures];
PhaseNormalization = [false; true; true; false; false; true];
IQCoupling = ["complex coefficients"; "coupled complex-equivalent"; ...
    "independent I/Q"; "complex coefficients"; ...
    "independent I/Q"; "independent I/Q"];
RelativePredictionErrorToComplex = [0; equivalenceError; NaN; NaN; NaN; NaN];

[complexityFLOPs, flopConvention] = buildLinearFLOPs( ...
    manager.regPopulation, supportBase, supportMatched, ...
    identification.pnReduction, noPN, pnReduced);
[~, costRows] = ismember(Model, complexityFLOPs.Model);
FLOPsPerSample = complexityFLOPs.FLOPsPerSample(costRows);
AdditionalOperationsPerSample = strings(6, 1);
for index = 1:6
    AdditionalOperationsPerSample(index) = ...
        describeAdditionalOperations(complexityFLOPs(costRows(index), :));
end
comparisonResults = table(Model, SelectionMethod, NumRealParameters, ...
    ParameterMatchedTarget, ParameterDifference, InternalTrainNMSEdB, ...
    InternalValidationNMSEdB, IdentificationNMSEdB, ...
    FullSignalNMSEdB, SelectedLambda, DOMPSupportSize, ...
    EffectiveFeatureCount, PhaseNormalization, IQCoupling, ...
    RelativePredictionErrorToComplex, FLOPsPerSample, ...
    AdditionalOperationsPerSample);

[regressorStructureSummary, ~] = analyzeRegressorStructure( ...
    manager.regPopulation, supportBase);
historyLabels = ["INTERNAL_TRAIN complex path"; ...
    "IDENTIFICATION complex path"; "INTERNAL_TRAIN reduced PN-IQ"; ...
    "IDENTIFICATION reduced PN-IQ"];
historyTables = {summarizeDOMPHistory(trainPathHistory); ...
    summarizeDOMPHistory(identificationPathHistory); ...
    summarizeDOMPHistory(reducedTrainSelection.dompHistory); ...
    summarizeDOMPHistory(reducedSelection.dompHistory)};
dompHistorySummary = addvars(vertcat(historyTables{:}), historyLabels, ...
    'Before', 1, 'NewVariableNames', 'Stage');

study = struct( ...
    'comparisonResults', comparisonResults, ...
    'complexityFLOPs', complexityFLOPs, ...
    'flopConvention', flopConvention, ...
    'dompHistorySummary', dompHistorySummary, ...
    'regressorStructureSummary', regressorStructureSummary, ...
    'supports', struct('supportDOMP', supportBase, ...
        'supportParameterMatchedDOMP', supportMatched, ...
        'reducedFeatureSupportDOMP', reducedSupport, ...
        'supportTrainBase', supportTrainBase, ...
        'supportTrainParameterMatched', supportTrainMatched), ...
    'dompHistories', struct( ...
        'internalTrainComplex', trainPathHistory, ...
        'identificationComplex', identificationPathHistory, ...
        'internalTrainReducedPNIQ', reducedTrainSelection.dompHistory, ...
        'identificationReducedPNIQ', reducedSelection.dompHistory), ...
    'identificationPredictions', identificationPredictions, ...
    'fullSignalPredictions', fullPredictions, ...
    'equivalenceRelativeError', equivalenceError, ...
    'totalTimeSeconds', toc(studyTimer));
end

function [fit, trainNMSE, validationNMSE, index, lambda] = ...
    selectComplexLambda(UTrain, UValidation, yTrain, yValidation, ...
    support, lambdaGrid)
fit = fitComplexGMPGrid(UTrain, yTrain, support, lambdaGrid);
trainNMSE = zeros(numel(lambdaGrid), 1);
validationNMSE = zeros(numel(lambdaGrid), 1);
for candidate = 1:numel(lambdaGrid)
    coefficients = fit.coefficients(:, candidate);
    trainNMSE(candidate) = ...
        nmseComplexDb(yTrain, UTrain(:, support)*coefficients);
    validationNMSE(candidate) = ...
        nmseComplexDb(yValidation, UValidation(:, support)*coefficients);
end
[~, index] = min(validationNMSE);
lambda = lambdaGrid(index);
end

function [trainNMSE, validationNMSE, index, lambda] = ...
    selectIndependentLambda(trainFeatures, validationFeatures, ...
    trainTarget, trainRotation, validationRotation, yTrain, yValidation, ...
    lambdaGrid, reduction, modelName)
trainNMSE = zeros(numel(lambdaGrid), 1);
validationNMSE = zeros(numel(lambdaGrid), 1);
for candidate = 1:numel(lambdaGrid)
    fit = fitIndependentIQGMP(trainFeatures, trainTarget, ...
        lambdaGrid(candidate), reduction, modelName);
    trainNMSE(candidate) = nmseComplexDb(yTrain, ...
        independentPrediction(trainFeatures, fit, trainRotation));
    validationNMSE(candidate) = nmseComplexDb(yValidation, ...
        independentPrediction(validationFeatures, fit, validationRotation));
end
[~, index] = min(validationNMSE);
lambda = lambdaGrid(index);
end

function fit = mapComplexFit(support, coefficients, populationSize, ...
    lambda, columnNorms)
support = support(:);
coefficients = coefficients(:);
fit = struct( ...
    'supportComplex', support, ...
    'supportReal', [support; populationSize + support], ...
    'hReal', [real(coefficients); imag(coefficients)], ...
    'hComplexRecovered', coefficients, ...
    'normUComplex', columnNorms(:), 'lambda', lambda, ...
    'selectionMethod', 'DOMP', 'nComplexTotal', populationSize, ...
    'nActiveComplex', numel(support), 'nActiveReal', 2*numel(support));
end

function reduction = restrictReduction(baseReduction, support)
support = double(support(:));
reduction = baseReduction;
reduction.keptIndices = baseReduction.keptIndices(support);
reduction.effectiveFeatureCount = numel(support);
reduction.groupSupportFeatures = support;
reduction.selectionMethod = 'DOMP';
end

function prediction = independentPrediction(features, fit, rotation)
predictionPN = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
prediction = conj(rotation(:)).*predictionPN;
end

function prediction = coupledPrediction(UPhase, hReal, rotation)
nRows = size(UPhase, 1);
UReal = [real(UPhase), -imag(UPhase); imag(UPhase), real(UPhase)];
predictionReal = UReal*hReal;
predictionPN = predictionReal(1:nRows) + ...
    1j*predictionReal(nRows+1:end);
prediction = conj(rotation(:)).*predictionPN;
end

function relativeError = assertEquivalent( ...
    reference, candidate, target, domain, tolerances)
relativeError = norm(candidate-reference)/max(norm(reference), realmin);
nmseDifference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if relativeError >= tolerances.relativePredictionTolerance || ...
        nmseDifference >= tolerances.nmseDifferenceToleranceDb
    error('runPNGMPDOMPStudy:CoupledEquivalenceFailed', ...
        ['Complex/coupled equivalence failed on %s: relative %.3e, ' ...
        'NMSE difference %.3e dB.'], domain, relativeError, nmseDifference);
end
end

function requirePathLength(path, requiredLength, stage)
if numel(path) < requiredLength
    error('runPNGMPDOMPStudy:ShortDOMPPath', ...
        'DOMP produced %d terms for %s; %d are required.', ...
        numel(path), stage, requiredLength);
end
end

function [flops, convention] = buildLinearFLOPs( ...
    population, supportBase, supportMatched, pnReduction, noPN, pnReduced)
convention = getFLOPConvention();
[baseOperations, ~] = countModelOperations( ...
    population, supportBase, pnReduction);
[matchedOperations, ~] = countModelOperations(population, supportMatched);
[baseFLOPs, ~] = countModelFLOPs(baseOperations, convention);
[matchedFLOPs, ~] = countModelFLOPs(matchedOperations, convention);

complexBase = baseFLOPs(baseFLOPs.Model == "Complex GMP", :);
complexBase.Model = "Complex GMP DOMP-100";
coupled = baseFLOPs( ...
    baseFLOPs.Model == "Coupled PN-IQ-GMP structure-aware", :);
coupled.Model = "Coupled PN-IQ (shared DOMP-100)";
independent = baseFLOPs( ...
    baseFLOPs.Model == "Independent PN-IQ-GMP", :);
independent.Model = "Independent PN-IQ full";
complexMatched = matchedFLOPs(matchedFLOPs.Model == "Complex GMP", :);
complexMatched.Model = "Complex GMP DOMP parameter-matched";

complexOperations = baseOperations(baseOperations.Model == "Complex GMP", :);
independentOperations = baseOperations( ...
    baseOperations.Model == "Independent PN-IQ-GMP", :);
noPNOperations = customOperationRow(complexOperations, ...
    "Independent I/Q without PN", noPN.realParameters, ...
    noPN.effectiveRealFeatures);
reducedOperations = customOperationRow(independentOperations, ...
    "Independent PN-IQ reduced DOMP", pnReduced.realParameters, ...
    pnReduced.effectiveRealFeatures);
[customFLOPs, ~] = countModelFLOPs( ...
    [noPNOperations; reducedOperations], convention);
flops = [complexBase; coupled; independent; complexMatched; customFLOPs];
end

function row = customOperationRow(row, model, parameters, features)
row.Model = model;
row.EffectiveRealFeatures = features;
row.RealParameters = parameters;
row.CoefficientMemoryBytes = 8*parameters;
row.CoefficientMultiplications = 2*features;
row.CoefficientProductAdditions = 0;
row.AccumulationAdditions = 2*max(features-1, 0);
row.TotalRealMultiplicationsPerSample = ...
    row.FeatureGenerationMultiplications + row.CoefficientMultiplications + ...
    row.PhaseNormalizationMultiplications + ...
    row.PhaseRestorationMultiplications;
row.TotalRealAdditionsPerSample = row.FeatureGenerationAdditions + ...
    row.AccumulationAdditions + row.PhaseNormalizationAdditions + ...
    row.PhaseRestorationAdditions;
end
