function study = runPNGMPDOMPStudy(x, y, split, cfg)
% runPNGMPDOMPStudy - Fit and evaluate the six linear DOMP models.
% Lambda selection uses the internal split; supports and coefficients are
% then regenerated on all identification rows before full-signal evaluation.

%% Validate inputs and regularization modes
% Align the signals and define the three coefficient-estimation variants.
studyTimer = tic;
x = x(:);
y = y(:);
requiredFields = {'internalTrainIndices','internalValidationIndices', ...
    'identificationIndices','fullSignalIndices'};
if numel(x) ~= numel(y) || ~all(isfield(split, requiredFields)) || ...
        ~all(ismember(split.identificationIndices, split.fullSignalIndices))
    error('runPNGMPDOMPStudy:InvalidInput', ...
        'Signals and the shared comparison split are inconsistent.');
end

fixedRidgeLambda = cfg.fixedRidgeLambda;
lsGridIndex = find(cfg.lambdaGrid == 0);
fixedGridIndex = find(cfg.lambdaGrid == fixedRidgeLambda);
if fixedRidgeLambda ~= 1e-5 || numel(lsGridIndex) ~= 1 || ...
        numel(fixedGridIndex) ~= 1
    error('runPNGMPDOMPStudy:InvalidRegularizationGrid', ...
        'The lambda grid must contain exactly one LS zero and fixed 1e-5.');
end
regularizationModes = ["LS"; "Fixed Ridge"; ...
    "Validation-selected Ridge"];
variantFields = {'ls','fixedRidge','selectedRidge'};
nVariants = numel(regularizationModes);

%% Build candidate feature populations
% Create one shared GMP population and the four evaluation row domains.
rows.train = split.internalTrainIndices;
rows.validation = split.internalValidationIndices;
rows.identification = split.identificationIndices;
rows.fullSignal = split.fullSignalIndices;
manager = GMP_createRegressorManager(x, y, cfg.gmp);
populationSize = numel(manager.regPopulation);
population = (1:populationSize).';
baseSupportSize = cfg.gmp.maxPopulation;
maximumPathSize = min(2*baseSupportSize, populationSize);

%% Internal DOMP and lambda selection
% Select supports and regularization without using full-signal results.
train.U = buildGMPRegressorRows(x, rows.train, manager, population);
train.y = y(rows.train);
validation.U = buildGMPRegressorRows( ...
    x, rows.validation, manager, population);
validation.y = y(rows.validation);
[trainPath, trainPathHistory] = selectDOMPSupport( ...
    train.U, train.y, maximumPathSize, cfg.gmp.dompOptions);
requirePathLength(trainPath, baseSupportSize, 'internal train base');
supportTrainBase = trainPath(1:baseSupportSize);

[train.pnRaw, train.pnDetails] = buildPhaseNormalizedIQRegressors( ...
    x, rows.train, manager, supportTrainBase);
[train.pn, train.pnReduction] = removeStructurallyZeroQFeatures( ...
    train.pnRaw, train.pnDetails.featureMetadata, 1e-12);
[validation.pnRaw, validation.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.validation, manager, supportTrainBase);
validation.pn = validation.pnRaw(:, train.pnReduction.keptIndices);
train.yPN = train.pnDetails.phaseRotation .* train.y;
validation.yPN = validation.pnDetails.phaseRotation .* validation.y;

[complexBaseGrid, metrics.complexBaseTrain, ...
    metrics.complexBaseValidation, indices.complexBase, ...
    lambdas.complexBase] = selectComplexLambda( ...
    train.U, validation.U, train.y, validation.y, ...
    supportTrainBase, cfg.lambdaGrid);
[metrics.pnFullTrain, metrics.pnFullValidation, ...
    indices.pnFull, lambdas.pnFull] = selectIndependentLambda( ...
    train.pn, validation.pn, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, train.pnReduction, ...
    "Independent PN-IQ full");

[train.noPNRaw, train.noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, rows.train, manager, supportTrainBase);
[train.noPN, train.noPNReduction] = reduceStructuralFeatures( ...
    train.noPNRaw, train.noPNDetails.featureMetadata, 1e-12);
validation.noPNRaw = buildUnnormalizedIQRegressors( ...
    x, rows.validation, manager, supportTrainBase);
validation.noPN = validation.noPNRaw(:, train.noPNReduction.keptIndices);
[metrics.noPNTrain, metrics.noPNValidation, ...
    indices.noPN, lambdas.noPN] = selectIndependentLambda( ...
    train.noPN, validation.noPN, train.y, ...
    ones(numel(rows.train), 1), ones(numel(rows.validation), 1), ...
    train.y, validation.y, cfg.lambdaGrid, train.noPNReduction, ...
    "Independent I/Q without PN");

reducedFeatureCount = floor(cfg.reducedRealParameterTarget/2);
reducedTrainSelection = selectSharedIQFeatures( ...
    train.pn, train.yPN, reducedFeatureCount, cfg.gmp.dompOptions);
train.pnReduced = train.pn(:, reducedTrainSelection.supportFeatures);
validation.pnReduced = validation.pn( ...
    :, reducedTrainSelection.supportFeatures);
reducedTrainReduction = restrictReduction( ...
    train.pnReduction, reducedTrainSelection.supportFeatures);
[metrics.pnReducedTrain, metrics.pnReducedValidation, ...
    indices.pnReduced, lambdas.pnReduced] = selectIndependentLambda( ...
    train.pnReduced, validation.pnReduced, train.yPN, ...
    train.pnDetails.phaseRotation, validation.pnDetails.phaseRotation, ...
    train.y, validation.y, cfg.lambdaGrid, reducedTrainReduction, ...
    "Independent PN-IQ reduced DOMP");

variantIndices.complexBase = ...
    [lsGridIndex, fixedGridIndex, indices.complexBase];
variantLambdas.complexBase = ...
    [0, fixedRidgeLambda, lambdas.complexBase];
metrics.coupledTrain = zeros(1, nVariants);
metrics.coupledValidation = zeros(1, nVariants);
equivalenceTrain = zeros(nVariants, 1);
equivalenceValidation = zeros(nVariants, 1);
for variant = 1:nVariants
    coefficients = complexBaseGrid.coefficients( ...
        :, variantIndices.complexBase(variant));
    trainCoupled = mapComplexFit(supportTrainBase, coefficients, ...
        populationSize, variantLambdas.complexBase(variant), ...
        complexBaseGrid.normU);
    trainComplexPrediction = train.U(:, supportTrainBase)*coefficients;
    validationComplexPrediction = ...
        validation.U(:, supportTrainBase)*coefficients;
    trainCoupledPrediction = coupledPrediction( ...
        train.pnDetails.phaseRotation.*train.U(:, supportTrainBase), ...
        trainCoupled.hReal, train.pnDetails.phaseRotation);
    validationCoupledPrediction = coupledPrediction( ...
        validation.pnDetails.phaseRotation.* ...
        validation.U(:, supportTrainBase), trainCoupled.hReal, ...
        validation.pnDetails.phaseRotation);
    equivalenceTrain(variant) = assertEquivalent( ...
        trainComplexPrediction, trainCoupledPrediction, train.y, ...
        "internal train " + regularizationModes(variant), cfg.equivalence);
    equivalenceValidation(variant) = assertEquivalent( ...
        validationComplexPrediction, validationCoupledPrediction, ...
        validation.y, "internal validation " + ...
        regularizationModes(variant), cfg.equivalence);
    metrics.coupledTrain(variant) = ...
        nmseComplexDb(train.y, trainCoupledPrediction);
    metrics.coupledValidation(variant) = ...
        nmseComplexDb(validation.y, validationCoupledPrediction);
end

%% Final fits on the identification set
% Rebuild supports and fit all regularization modes on identification.
identification.U = buildGMPRegressorRows( ...
    x, rows.identification, manager, population);
identification.y = y(rows.identification);
[identificationPath, identificationPathHistory] = selectDOMPSupport( ...
    identification.U, identification.y, maximumPathSize, ...
    cfg.gmp.dompOptions);
requirePathLength(identificationPath, baseSupportSize, ...
    'identification base');
supportBase = identificationPath(1:baseSupportSize);

[identification.pnRaw, identification.pnDetails] = ...
    buildPhaseNormalizedIQRegressors( ...
    x, rows.identification, manager, supportBase);
[identification.pn, identification.pnReduction] = ...
    removeStructurallyZeroQFeatures(identification.pnRaw, ...
    identification.pnDetails.featureMetadata, 1e-12);
identification.yPN = ...
    identification.pnDetails.phaseRotation .* identification.y;
targetParameters = 2*size(identification.pn, 2);
matchedSupportSize = ceil(targetParameters/2);
requirePathLength(trainPath, matchedSupportSize, ...
    'internal train parameter match');
requirePathLength(identificationPath, matchedSupportSize, ...
    'identification parameter match');
supportTrainMatched = trainPath(1:matchedSupportSize);
supportMatched = identificationPath(1:matchedSupportSize);
[~, metrics.complexMatchedTrain, metrics.complexMatchedValidation, ...
    indices.complexMatched, lambdas.complexMatched] = ...
    selectComplexLambda(train.U, validation.U, train.y, validation.y, ...
    supportTrainMatched, cfg.lambdaGrid);

variantIndices.pnFull = [lsGridIndex, fixedGridIndex, indices.pnFull];
variantIndices.complexMatched = ...
    [lsGridIndex, fixedGridIndex, indices.complexMatched];
variantIndices.noPN = [lsGridIndex, fixedGridIndex, indices.noPN];
variantIndices.pnReduced = ...
    [lsGridIndex, fixedGridIndex, indices.pnReduced];
variantLambdas.pnFull = [0, fixedRidgeLambda, lambdas.pnFull];
variantLambdas.complexMatched = ...
    [0, fixedRidgeLambda, lambdas.complexMatched];
variantLambdas.noPN = [0, fixedRidgeLambda, lambdas.noPN];
variantLambdas.pnReduced = [0, fixedRidgeLambda, lambdas.pnReduced];
selectedLambdas = [lambdas.complexBase, lambdas.pnFull, ...
    lambdas.complexMatched, lambdas.noPN, lambdas.pnReduced];
if ~all(ismember(selectedLambdas, cfg.lambdaGrid))
    error('runPNGMPDOMPStudy:SelectedLambdaOutsideGrid', ...
        'Every validation-selected lambda must belong to cfg.lambdaGrid.');
end

complexBase = fitComplexGMPGrid(identification.U, identification.y, ...
    supportBase, variantLambdas.complexBase);
complexMatched = fitComplexGMPGrid( ...
    identification.U, identification.y, ...
    supportMatched, variantLambdas.complexMatched);
coupled = mapComplexVariants(supportBase, complexBase.coefficients, ...
    populationSize, variantLambdas.complexBase, complexBase.normU);
pnFull = fitIndependentVariants(identification.pn, ...
    identification.yPN, variantLambdas.pnFull, ...
    identification.pnReduction, "Independent PN-IQ full");

[noPNRaw, noPNDetails] = buildUnnormalizedIQRegressors( ...
    x, rows.identification, manager, supportBase);
[noPNFeatures, noPNReduction] = reduceStructuralFeatures( ...
    noPNRaw, noPNDetails.featureMetadata, 1e-12);
noPN = fitIndependentVariants(noPNFeatures, identification.y, ...
    variantLambdas.noPN, noPNReduction, ...
    "Independent I/Q without PN");

reducedSelection = selectSharedIQFeatures( ...
    identification.pn, identification.yPN, reducedFeatureCount, ...
    cfg.gmp.dompOptions);
reducedSupport = reducedSelection.supportFeatures;
reducedReduction = restrictReduction( ...
    identification.pnReduction, reducedSupport);
pnReduced = fitIndependentVariants( ...
    identification.pn(:, reducedSupport), identification.yPN, ...
    variantLambdas.pnReduced, reducedReduction, ...
    "Independent PN-IQ reduced DOMP");

if any([coupled.nActiveReal] ~= 2*numel(supportBase)) || ...
        any([pnFull.realParameters] ~= pnFull(1).realParameters) || ...
        any([noPN.realParameters] ~= noPN(1).realParameters) || ...
        any([pnReduced.realParameters] ~= pnReduced(1).realParameters)
    error('runPNGMPDOMPStudy:VariantParameterMismatch', ...
        'Regularization variants must share their model parameter count.');
end

%% Build final predictions
% Predict identification and full-signal rows for every model variant.
yFull = y(rows.fullSignal);
equivalenceIdentification = zeros(nVariants, 1);
equivalenceFull = zeros(nVariants, 1);
for variant = 1:nVariants
    field = variantFields{variant};
    fullPredictions.complexGMP.(field) = GMP_blockPredict( ...
        x, manager, supportBase, complexBase.coefficients(:, variant), ...
        cfg.gmp.blockSize, rows.fullSignal);
    fullPredictions.coupledPNIQ.(field) = predictPhaseNormGMPReal( ...
        x, rows.fullSignal, manager, coupled(variant), cfg.gmp.blockSize);
    fullPredictions.independentPNIQ.(field) = predictIndependentIQGMP( ...
        x, rows.fullSignal, manager, supportBase, pnFull(variant), ...
        cfg.gmp.blockSize);
    fullPredictions.complexParameterMatched.(field) = GMP_blockPredict( ...
        x, manager, supportMatched, ...
        complexMatched.coefficients(:, variant), ...
        cfg.gmp.blockSize, rows.fullSignal);
    fullPredictions.independentNoPN.(field) = predictIndependentIQNoPN( ...
        x, rows.fullSignal, manager, supportBase, noPN(variant), ...
        cfg.gmp.blockSize);
    fullPredictions.independentPNIQReduced.(field) = ...
        predictIndependentIQGMP(x, rows.fullSignal, manager, ...
        supportBase, pnReduced(variant), cfg.gmp.blockSize);

    identificationPredictions.complexGMP.(field) = ...
        identification.U(:, supportBase)* ...
        complexBase.coefficients(:, variant);
    identificationPredictions.coupledPNIQ.(field) = coupledPrediction( ...
        identification.pnDetails.phaseRotation.* ...
        identification.U(:, supportBase), coupled(variant).hReal, ...
        identification.pnDetails.phaseRotation);
    identificationPredictions.independentPNIQ.(field) = ...
        independentPrediction(identification.pn, pnFull(variant), ...
        identification.pnDetails.phaseRotation);
    identificationPredictions.complexParameterMatched.(field) = ...
        identification.U(:, supportMatched)* ...
        complexMatched.coefficients(:, variant);
    identificationPredictions.independentNoPN.(field) = ...
        independentPrediction(noPNFeatures, noPN(variant), ...
        ones(numel(rows.identification), 1));
    identificationPredictions.independentPNIQReduced.(field) = ...
        independentPrediction(identification.pn(:, reducedSupport), ...
        pnReduced(variant), identification.pnDetails.phaseRotation);

    equivalenceIdentification(variant) = assertEquivalent( ...
        identificationPredictions.complexGMP.(field), ...
        identificationPredictions.coupledPNIQ.(field), ...
        identification.y, "identification " + ...
        regularizationModes(variant), cfg.equivalence);
    equivalenceFull(variant) = assertEquivalent( ...
        fullPredictions.complexGMP.(field), ...
        fullPredictions.coupledPNIQ.(field), yFull, ...
        "full signal " + regularizationModes(variant), cfg.equivalence);
end

%% Complex GMP / coupled PN-IQ equivalence
% Summarize the numerical mapping error for all regularization modes.
equivalenceError = equivalenceFull(3);
equivalenceByRegularization = table(regularizationModes, ...
    variantLambdas.complexBase(:), equivalenceTrain, ...
    equivalenceValidation, equivalenceIdentification, equivalenceFull, ...
    'VariableNames', {'RegularizationMode','Lambda', ...
    'InternalTrainRelativeError','InternalValidationRelativeError', ...
    'IdentificationRelativeError','FullSignalRelativeError'});

%% Predictions and NMSE
% Compute NMSE and create one explicit row per model and fit mode.
modelNames = ["Complex GMP DOMP-100"; ...
    "Coupled PN-IQ (shared DOMP-100)"; "Independent PN-IQ full"; ...
    "Complex GMP DOMP parameter-matched"; ...
    "Independent I/Q without PN"; "Independent PN-IQ reduced DOMP"];
identificationValues = { ...
    identificationPredictions.complexGMP.ls, ...
        identificationPredictions.complexGMP.fixedRidge, ...
        identificationPredictions.complexGMP.selectedRidge; ...
    identificationPredictions.coupledPNIQ.ls, ...
        identificationPredictions.coupledPNIQ.fixedRidge, ...
        identificationPredictions.coupledPNIQ.selectedRidge; ...
    identificationPredictions.independentPNIQ.ls, ...
        identificationPredictions.independentPNIQ.fixedRidge, ...
        identificationPredictions.independentPNIQ.selectedRidge; ...
    identificationPredictions.complexParameterMatched.ls, ...
        identificationPredictions.complexParameterMatched.fixedRidge, ...
        identificationPredictions.complexParameterMatched.selectedRidge; ...
    identificationPredictions.independentNoPN.ls, ...
        identificationPredictions.independentNoPN.fixedRidge, ...
        identificationPredictions.independentNoPN.selectedRidge; ...
    identificationPredictions.independentPNIQReduced.ls, ...
        identificationPredictions.independentPNIQReduced.fixedRidge, ...
        identificationPredictions.independentPNIQReduced.selectedRidge};
fullValues = { ...
    fullPredictions.complexGMP.ls, ...
        fullPredictions.complexGMP.fixedRidge, ...
        fullPredictions.complexGMP.selectedRidge; ...
    fullPredictions.coupledPNIQ.ls, ...
        fullPredictions.coupledPNIQ.fixedRidge, ...
        fullPredictions.coupledPNIQ.selectedRidge; ...
    fullPredictions.independentPNIQ.ls, ...
        fullPredictions.independentPNIQ.fixedRidge, ...
        fullPredictions.independentPNIQ.selectedRidge; ...
    fullPredictions.complexParameterMatched.ls, ...
        fullPredictions.complexParameterMatched.fixedRidge, ...
        fullPredictions.complexParameterMatched.selectedRidge; ...
    fullPredictions.independentNoPN.ls, ...
        fullPredictions.independentNoPN.fixedRidge, ...
        fullPredictions.independentNoPN.selectedRidge; ...
    fullPredictions.independentPNIQReduced.ls, ...
        fullPredictions.independentPNIQReduced.fixedRidge, ...
        fullPredictions.independentPNIQReduced.selectedRidge};
if any(cellfun(@(prediction) any(~isfinite(prediction)), ...
        [identificationValues(:); fullValues(:)]))
    error('runPNGMPDOMPStudy:NonFinitePrediction', ...
        'Every identification and full-signal prediction must be finite.');
end

identificationNMSEByModel = cellfun( ...
    @(prediction) nmseComplexDb(identification.y, prediction), ...
    identificationValues);
fullSignalNMSEByModel = cellfun( ...
    @(prediction) nmseComplexDb(yFull, prediction), fullValues);
internalTrainByModel = [ ...
    metrics.complexBaseTrain(variantIndices.complexBase).'; ...
    metrics.coupledTrain; ...
    metrics.pnFullTrain(variantIndices.pnFull).'; ...
    metrics.complexMatchedTrain(variantIndices.complexMatched).'; ...
    metrics.noPNTrain(variantIndices.noPN).'; ...
    metrics.pnReducedTrain(variantIndices.pnReduced).'];
internalValidationByModel = [ ...
    metrics.complexBaseValidation(variantIndices.complexBase).'; ...
    metrics.coupledValidation; ...
    metrics.pnFullValidation(variantIndices.pnFull).'; ...
    metrics.complexMatchedValidation(variantIndices.complexMatched).'; ...
    metrics.noPNValidation(variantIndices.noPN).'; ...
    metrics.pnReducedValidation(variantIndices.pnReduced).'];
lambdaByModel = [variantLambdas.complexBase; ...
    variantLambdas.complexBase; variantLambdas.pnFull; ...
    variantLambdas.complexMatched; variantLambdas.noPN; ...
    variantLambdas.pnReduced];

Model = repelem(modelNames, nVariants, 1);
SelectionMethod = repmat("DOMP", numel(Model), 1);
RegularizationMode = repmat(regularizationModes, numel(modelNames), 1);
parametersByModel = [2*baseSupportSize; 2*baseSupportSize; ...
    pnFull(1).realParameters; 2*numel(supportMatched); ...
    noPN(1).realParameters; pnReduced(1).realParameters];
targetsByModel = [NaN; NaN; targetParameters; targetParameters; ...
    NaN; cfg.reducedRealParameterTarget];
NumRealParameters = repelem(parametersByModel, nVariants, 1);
ParameterMatchedTarget = repelem(targetsByModel, nVariants, 1);
ParameterDifference = NumRealParameters - ParameterMatchedTarget;
InternalTrainNMSEdB = reshape(internalTrainByModel.', [], 1);
InternalValidationNMSEdB = ...
    reshape(internalValidationByModel.', [], 1);
IdentificationNMSEdB = reshape(identificationNMSEByModel.', [], 1);
FullSignalNMSEdB = reshape(fullSignalNMSEByModel.', [], 1);
SelectedLambda = reshape(lambdaByModel.', [], 1);
supportSizeByModel = [baseSupportSize; baseSupportSize; ...
    baseSupportSize; numel(supportMatched); baseSupportSize; ...
    reducedFeatureCount];
DOMPSupportSize = repelem(supportSizeByModel, nVariants, 1);
featureCountByModel = [baseSupportSize; 2*baseSupportSize; ...
    pnFull(1).effectiveRealFeatures; numel(supportMatched); ...
    noPN(1).effectiveRealFeatures; pnReduced(1).effectiveRealFeatures];
EffectiveFeatureCount = repelem(featureCountByModel, nVariants, 1);
PhaseNormalization = repelem( ...
    [false; true; true; false; false; true], nVariants, 1);
IQCoupling = repelem(["complex coefficients"; ...
    "coupled complex-equivalent"; "independent I/Q"; ...
    "complex coefficients"; "independent I/Q"; "independent I/Q"], ...
    nVariants, 1);
relativeErrorByModel = [zeros(1, nVariants); equivalenceFull.'; ...
    NaN(4, nVariants)];
RelativePredictionErrorToComplex = ...
    reshape(relativeErrorByModel.', [], 1);

%% Parameter counts and FLOPs
% Reuse each model's inference cost across its regularization variants.
[complexityFLOPs, flopConvention] = buildLinearFLOPs( ...
    manager.regPopulation, supportBase, supportMatched, ...
    identification.pnReduction, noPN(1), pnReduced(1));
[~, costRows] = ismember(modelNames, complexityFLOPs.Model);
FLOPsPerSample = repelem( ...
    complexityFLOPs.FLOPsPerSample(costRows), nVariants, 1);
additionalByModel = strings(numel(modelNames), 1);
for model = 1:numel(modelNames)
    additionalByModel(model) = ...
        describeAdditionalOperations(complexityFLOPs(costRows(model), :));
end
AdditionalOperationsPerSample = ...
    repelem(additionalByModel, nVariants, 1);
comparisonResults = table(Model, SelectionMethod, RegularizationMode, ...
    NumRealParameters, ParameterMatchedTarget, ParameterDifference, ...
    InternalTrainNMSEdB, InternalValidationNMSEdB, ...
    IdentificationNMSEdB, FullSignalNMSEdB, SelectedLambda, DOMPSupportSize, ...
    EffectiveFeatureCount, PhaseNormalization, IQCoupling, ...
    RelativePredictionErrorToComplex, FLOPsPerSample, ...
    AdditionalOperationsPerSample);

[regressorStructureSummary, ~] = analyzeRegressorStructure( ...
    manager.regPopulation, supportBase);
historyLabels = ["INTERNAL_TRAIN complex path"; ...
    "IDENTIFICATION complex path"; "INTERNAL_TRAIN reduced PN-IQ"; ...
    "IDENTIFICATION reduced PN-IQ"];
historyTables = {summarizeDOMPHistory(trainPathHistory); ...
    summarizeDOMPHistory(identificationPathHistory); ...
    summarizeDOMPHistory(reducedTrainSelection.dompHistory); ...
    summarizeDOMPHistory(reducedSelection.dompHistory)};
dompHistorySummary = addvars(vertcat(historyTables{:}), historyLabels, ...
    'Before', 1, 'NewVariableNames', 'Stage');

%% Package study results
% Return tables, supports, predictions and equivalence checks together.
study = struct( ...
    'comparisonResults', comparisonResults, ...
    'complexityFLOPs', complexityFLOPs, ...
    'flopConvention', flopConvention, ...
    'dompHistorySummary', dompHistorySummary, ...
    'regressorStructureSummary', regressorStructureSummary, ...
    'supports', struct('supportDOMP', supportBase, ...
        'supportParameterMatchedDOMP', supportMatched, ...
        'reducedFeatureSupportDOMP', reducedSupport, ...
        'supportTrainBase', supportTrainBase, ...
        'supportTrainParameterMatched', supportTrainMatched), ...
    'dompHistories', struct( ...
        'internalTrainComplex', trainPathHistory, ...
        'identificationComplex', identificationPathHistory, ...
        'internalTrainReducedPNIQ', reducedTrainSelection.dompHistory, ...
        'identificationReducedPNIQ', reducedSelection.dompHistory), ...
    'identificationPredictions', identificationPredictions, ...
    'fullSignalPredictions', fullPredictions, ...
    'equivalenceRelativeError', equivalenceError, ...
    'equivalenceByRegularization', equivalenceByRegularization, ...
    'totalTimeSeconds', toc(studyTimer));
end

function [fit, trainNMSE, validationNMSE, index, lambda] = ...
    selectComplexLambda(UTrain, UValidation, yTrain, yValidation, ...
    support, lambdaGrid)
fit = fitComplexGMPGrid(UTrain, yTrain, support, lambdaGrid);
trainNMSE = zeros(numel(lambdaGrid), 1);
validationNMSE = zeros(numel(lambdaGrid), 1);
for candidate = 1:numel(lambdaGrid)
    coefficients = fit.coefficients(:, candidate);
    trainNMSE(candidate) = ...
        nmseComplexDb(yTrain, UTrain(:, support)*coefficients);
    validationNMSE(candidate) = ...
        nmseComplexDb(yValidation, UValidation(:, support)*coefficients);
end
[~, index] = min(validationNMSE);
lambda = lambdaGrid(index);
end

function [trainNMSE, validationNMSE, index, lambda] = ...
    selectIndependentLambda(trainFeatures, validationFeatures, ...
    trainTarget, trainRotation, validationRotation, yTrain, yValidation, ...
    lambdaGrid, reduction, modelName)
trainNMSE = zeros(numel(lambdaGrid), 1);
validationNMSE = zeros(numel(lambdaGrid), 1);
for candidate = 1:numel(lambdaGrid)
    fit = fitIndependentIQGMP(trainFeatures, trainTarget, ...
        lambdaGrid(candidate), reduction, modelName);
    trainNMSE(candidate) = nmseComplexDb(yTrain, ...
        independentPrediction(trainFeatures, fit, trainRotation));
    validationNMSE(candidate) = nmseComplexDb(yValidation, ...
        independentPrediction(validationFeatures, fit, validationRotation));
end
[~, index] = min(validationNMSE);
lambda = lambdaGrid(index);
end

function fit = mapComplexFit(support, coefficients, populationSize, ...
    lambda, columnNorms)
support = support(:);
coefficients = coefficients(:);
fit = struct( ...
    'supportComplex', support, ...
    'supportReal', [support; populationSize + support], ...
    'hReal', [real(coefficients); imag(coefficients)], ...
    'hComplexRecovered', coefficients, ...
    'normUComplex', columnNorms(:), 'lambda', lambda, ...
    'selectionMethod', 'DOMP', 'nComplexTotal', populationSize, ...
    'nActiveComplex', numel(support), 'nActiveReal', 2*numel(support));
end

function fits = mapComplexVariants(support, coefficients, populationSize, ...
    lambdas, columnNorms)
fits = repmat(mapComplexFit(support, coefficients(:, 1), ...
    populationSize, lambdas(1), columnNorms), 1, numel(lambdas));
for variant = 2:numel(lambdas)
    fits(variant) = mapComplexFit(support, coefficients(:, variant), ...
        populationSize, lambdas(variant), columnNorms);
end
end

function fits = fitIndependentVariants( ...
    features, target, lambdas, reduction, modelName)
fits = repmat(fitIndependentIQGMP(features, target, lambdas(1), ...
    reduction, modelName), 1, numel(lambdas));
for variant = 2:numel(lambdas)
    fits(variant) = fitIndependentIQGMP( ...
        features, target, lambdas(variant), reduction, modelName);
end
end

function reduction = restrictReduction(baseReduction, support)
support = double(support(:));
reduction = baseReduction;
reduction.keptIndices = baseReduction.keptIndices(support);
reduction.effectiveFeatureCount = numel(support);
reduction.groupSupportFeatures = support;
reduction.selectionMethod = 'DOMP';
end

function prediction = independentPrediction(features, fit, rotation)
predictionPN = features*fit.coefficientsI + ...
    1j*(features*fit.coefficientsQ);
prediction = conj(rotation(:)).*predictionPN;
end

function prediction = coupledPrediction(UPhase, hReal, rotation)
nRows = size(UPhase, 1);
UReal = [real(UPhase), -imag(UPhase); imag(UPhase), real(UPhase)];
predictionReal = UReal*hReal;
predictionPN = predictionReal(1:nRows) + ...
    1j*predictionReal(nRows+1:end);
prediction = conj(rotation(:)).*predictionPN;
end

function relativeError = assertEquivalent( ...
    reference, candidate, target, domain, tolerances)
relativeError = norm(candidate-reference)/max(norm(reference), realmin);
nmseDifference = abs(nmseComplexDb(target, reference) - ...
    nmseComplexDb(target, candidate));
if relativeError >= tolerances.relativePredictionTolerance || ...
        nmseDifference >= tolerances.nmseDifferenceToleranceDb
    error('runPNGMPDOMPStudy:CoupledEquivalenceFailed', ...
        ['Complex/coupled equivalence failed on %s: relative %.3e, ' ...
        'NMSE difference %.3e dB.'], domain, relativeError, nmseDifference);
end
end

function requirePathLength(path, requiredLength, stage)
if numel(path) < requiredLength
    error('runPNGMPDOMPStudy:ShortDOMPPath', ...
        'DOMP produced %d terms for %s; %d are required.', ...
        numel(path), stage, requiredLength);
end
end

function [flops, convention] = buildLinearFLOPs( ...
    population, supportBase, supportMatched, pnReduction, noPN, pnReduced)
convention = getFLOPConvention();
[baseOperations, ~] = countModelOperations( ...
    population, supportBase, pnReduction);
[matchedOperations, ~] = countModelOperations(population, supportMatched);
[baseFLOPs, ~] = countModelFLOPs(baseOperations, convention);
[matchedFLOPs, ~] = countModelFLOPs(matchedOperations, convention);

complexBase = baseFLOPs(baseFLOPs.Model == "Complex GMP", :);
complexBase.Model = "Complex GMP DOMP-100";
coupled = baseFLOPs( ...
    baseFLOPs.Model == "Coupled PN-IQ-GMP structure-aware", :);
coupled.Model = "Coupled PN-IQ (shared DOMP-100)";
independent = baseFLOPs( ...
    baseFLOPs.Model == "Independent PN-IQ-GMP", :);
independent.Model = "Independent PN-IQ full";
complexMatched = matchedFLOPs(matchedFLOPs.Model == "Complex GMP", :);
complexMatched.Model = "Complex GMP DOMP parameter-matched";

complexOperations = baseOperations(baseOperations.Model == "Complex GMP", :);
independentOperations = baseOperations( ...
    baseOperations.Model == "Independent PN-IQ-GMP", :);
noPNOperations = customOperationRow(complexOperations, ...
    "Independent I/Q without PN", noPN.realParameters, ...
    noPN.effectiveRealFeatures);
reducedOperations = customOperationRow(independentOperations, ...
    "Independent PN-IQ reduced DOMP", pnReduced.realParameters, ...
    pnReduced.effectiveRealFeatures);
[customFLOPs, ~] = countModelFLOPs( ...
    [noPNOperations; reducedOperations], convention);
flops = [complexBase; coupled; independent; complexMatched; customFLOPs];
end

function row = customOperationRow(row, model, parameters, features)
row.Model = model;
row.EffectiveRealFeatures = features;
row.RealParameters = parameters;
row.CoefficientMemoryBytes = 8*parameters;
row.CoefficientMultiplications = 2*features;
row.CoefficientProductAdditions = 0;
row.AccumulationAdditions = 2*max(features-1, 0);
row.TotalRealMultiplicationsPerSample = ...
    row.FeatureGenerationMultiplications + row.CoefficientMultiplications + ...
    row.PhaseNormalizationMultiplications + ...
    row.PhaseRestorationMultiplications;
row.TotalRealAdditionsPerSample = row.FeatureGenerationAdditions + ...
    row.AccumulationAdditions + row.PhaseNormalizationAdditions + ...
    row.PhaseRestorationAdditions;
end
