function saveComparisonStudy(data, split, study, cfg, resultDirectory)
% saveComparisonStudy - Persist the established comparison artifacts.
% Model fitting is complete before this function runs; it writes the frozen
% tables, supports, predictions, metadata, figures, and short report.

writetable(study.comparisonResults, ...
    fullfile(resultDirectory, 'comparison_results.csv'));
writetable(study.parameterSummary, ...
    fullfile(resultDirectory, 'parameter_summary.csv'));
writetable(study.selectedHyperparameters, ...
    fullfile(resultDirectory, 'selected_hyperparameters.csv'));
writetable(study.complexityFLOPs, ...
    fullfile(resultDirectory, 'complexity_flops.csv'));
writetable(study.linear.flopConvention, ...
    fullfile(resultDirectory, 'flop_convention.csv'));
writetable(study.linear.dompHistorySummary, ...
    fullfile(resultDirectory, 'domp_history_summary.csv'));
writetable(study.linear.regressorStructureSummary, ...
    fullfile(resultDirectory, 'regressor_structure_summary.csv'));

identification_indices = split.identificationIndices;
full_signal_indices = split.fullSignalIndices;
internal_train_indices = split.internalTrainIndices;
internal_validation_indices = split.internalValidationIndices;
save(fullfile(resultDirectory, 'split_indices.mat'), ...
    'identification_indices','full_signal_indices', ...
    'internal_train_indices','internal_validation_indices','split');

supports = study.linear.supports;
domp_histories = study.linear.dompHistories;
save(fullfile(resultDirectory, 'domp_supports.mat'), ...
    'supports','domp_histories');

identification_predictions = study.linear.identificationPredictions;
identification_predictions.pnnnH4Dense = ...
    study.pnnn.h4DenseFit.identificationPrediction;
identification_predictions.pnnnN12Dense = ...
    study.pnnn.n12DenseFit.identificationPrediction;
identification_predictions.pnnnN12Sparse = ...
    study.pnnn.n12SparseFit.identificationPrediction;
full_signal_predictions = study.linear.fullSignalPredictions;
full_signal_predictions.pnnnH4Dense = ...
    study.pnnn.h4DenseFit.fullSignalPrediction;
full_signal_predictions.pnnnN12Dense = ...
    study.pnnn.n12DenseFit.fullSignalPrediction;
full_signal_predictions.pnnnN12Sparse = ...
    study.pnnn.n12SparseFit.fullSignalPrediction;
target_identification = data.y(identification_indices);
target_full_signal = data.y(full_signal_indices);
prediction_metadata = struct( ...
    'identificationSamples', numel(identification_indices), ...
    'fullSignalSamples', numel(full_signal_indices), ...
    'identificationIncludedInFullSignal', true, ...
    'fullSignalIsIndependentHoldout', false);
save(fullfile(resultDirectory, 'full_signal_predictions.mat'), ...
    'target_identification','target_full_signal', ...
    'identification_indices','full_signal_indices', ...
    'identification_predictions','full_signal_predictions', ...
    'prediction_metadata','-v7.3');

comparison_results = study.comparisonResults;
comparison_metadata = buildComparisonMetadata(study, split, cfg);
save(fullfile(resultDirectory, 'comparison_results.mat'), ...
    'comparison_results','comparison_metadata');
runtime_cfg = study.pnnn.runtimeConfig;
save(fullfile(resultDirectory, 'comparison_config.mat'), ...
    'runtime_cfg','cfg');

createComparisonPlots(comparison_results, resultDirectory);
sparseCost = study.complexityFLOPs( ...
    study.complexityFLOPs.Model == "PNNN N12 sparse", :);
reportFile = fullfile(resultDirectory, 'fair_comparison_report.tex');
writeFairComparisonReport(reportFile, study.mainResults, split, cfg, ...
    study.linear.equivalenceRelativeError, ...
    sparseCost.DenseMatrixFLOPsPerSample);
end

function metadata = buildComparisonMetadata(study, split, cfg)
metadata = struct( ...
    'measurementName', cfg.measurementName, ...
    'mappingMode', cfg.mappingMode, ...
    'sharedDCRemoval', cfg.pnnn.removeDC, ...
    'inputDimension', study.pnnn.inputDimension, ...
    'identificationSamples', numel(split.identificationIndices), ...
    'fullSignalSamples', numel(split.fullSignalIndices), ...
    'identificationIncludedInFullSignal', true, ...
    'fullSignalIsIndependentHoldout', false, ...
    'targetActiveParams', targetActiveParameters(study), ...
    'pnnnSelection', study.pnnn.selection, ...
    'trainingBudget', study.pnnn.budget, ...
    'linearStudySeconds', study.linear.totalTimeSeconds, ...
    'equivalenceRelativeError', study.linear.equivalenceRelativeError, ...
    'h4Dense', stripPNNNFit(study.pnnn.h4DenseFit), ...
    'n12Dense', stripPNNNFit(study.pnnn.n12DenseFit), ...
    'n12Sparse', stripPNNNFit(study.pnnn.n12SparseFit));
end

function target = targetActiveParameters(study)
row = study.comparisonResults.Model == "Independent PN-IQ full";
if nnz(row) ~= 1
    error('saveComparisonStudy:MissingParameterTarget', ...
        'Independent PN-IQ must define one dynamic parameter target.');
end
target = study.comparisonResults.NumRealParameters(row);
end

function summary = stripPNNNFit(fit)
largeFields = {'network','normalization','identificationPrediction', ...
    'fullSignalPrediction','pruningState','finalTrainingInfo', ...
    'finalFineTuneInfo'};
summary = rmfield(fit, intersect(largeFields, fieldnames(fit), 'stable'));
end
