function writeFairComparisonReport(filename, mainResults, split, cfg, ...
    equivalenceError, sparseDenseMatrixFLOPs)
% writeFairComparisonReport - Write the established short LaTeX report.
% Percentages and activation names come from configuration so the prose
% cannot drift from the scientific protocol used by the runner.

fileId = fopen(filename, 'w');
if fileId < 0
    error('writeFairComparisonReport:OpenFailed', ...
        'Could not create the LaTeX report.');
end
cleanup = onCleanup(@() fclose(fileId));
identificationPercent = 100*split.identificationFraction;
activation = lower(string(cfg.pnnn.actType));

fprintf(fileId, '\\documentclass[10pt]{article}\n');
fprintf(fileId, '\\usepackage[margin=1.35cm]{geometry}\n');
fprintf(fileId, '\\usepackage{booktabs,amsmath,array,tabularx}\n');
fprintf(fileId, '\\setlength{\\emergencystretch}{2em}\n');
fprintf(fileId, '\\title{Full-Signal PNNN versus PN-GMP DOMP Comparison}\n');
fprintf(fileId, '\\author{}\\date{}\\begin{document}\\maketitle\n');
fprintf(fileId, ['\\paragraph{Objective and methodology.} Complex GMP, ' ...
    'its exactly equivalent coupled PN-IQ representation, independent ' ...
    'PN-IQ controls, and parameter-matched PNNNs use the same modeled-block ' ...
    'X/Y samples. DOMP is used only during linear identification.\n']);
fprintf(fileId, ['\\paragraph{Fair comparison protocol.} The classic ' ...
    'selector provides %d identification rows (configured %.3g\\%% of ' ...
    'the capture). An internal %d/%d split selects regularization and ' ...
    'neural epochs. Every final model is fitted on all identification ' ...
    'rows and evaluated on all %d signal rows. \\textbf{The full-signal ' ...
    'evaluation includes the identification samples and therefore must ' ...
    'not be interpreted as an independent generalization test.}\n'], ...
    numel(split.identificationIndices), identificationPercent, ...
    numel(split.internalTrainIndices), ...
    numel(split.internalValidationIndices), ...
    numel(split.fullSignalIndices));
fprintf(fileId, ['\\paragraph{Main results.} NMSE uses ' ...
    '$10\\log_{10}(\\sum|y-\\hat y|^2/\\sum|y|^2)$.\n']);
fprintf(fileId, ...
    '\\begin{center}\\small\\begin{tabularx}{\\linewidth}{XrrrX}\n');
fprintf(fileId, '\\toprule\n');
fprintf(fileId, ['Model & Real parameters & Full-signal NMSE (dB) & ' ...
    'FLOPs/sample & Additional operations/sample \\\\ \\midrule\n']);
for index = 1:height(mainResults)
    fprintf(fileId, '%s & %d & %.3f & %d & %s \\\\ \n', ...
        latexEscape(mainResults.Model(index)), ...
        mainResults.NumRealParameters(index), ...
        mainResults.FullSignalNMSEdB(index), ...
        mainResults.FLOPsPerSample(index), ...
        latexEscape(mainResults.AdditionalOperationsPerSample(index)));
end
fprintf(fileId, '\\bottomrule\\end{tabularx}\\end{center}\n');
fprintf(fileId, ['\\paragraph{Computational cost.} FLOPs/sample counts ' ...
    'real additions and multiplications required for one complex output, ' ...
    'including feature generation, coefficients or weights, biases, phase ' ...
    'normalization, and phase restoration. Magnitudes, roots, divisions, ' ...
    'exponentials, and activation evaluations remain separate. DOMP is not ' ...
    'an inference cost. The sparse-PNNN FLOP count assumes that zero weights ' ...
    'are skipped. An implementation that executes the original full matrices ' ...
    'will require %d FLOPs/sample instead.\n'], sparseDenseMatrixFLOPs);
fprintf(fileId, ['\\paragraph{Interpretation and limitations.} Independent ' ...
    'PN-IQ provides the strongest NMSE in the main comparison; all three ' ...
    'main models use exactly the same number of active real parameters; and ' ...
    'the sparse PNNN uses the fewest counted FLOPs when zero weights are ' ...
    'actually skipped, while adding %s evaluations. Complex GMP DOMP-100 ' ...
    'and coupled PN-IQ remain numerically equivalent with relative error ' ...
    '$%.3e$. These analytical counts do not establish latency, energy, ' ...
    'or FPGA resource superiority.\n'], activation, equivalenceError);
fprintf(fileId, '\\end{document}\n');

if cfg.report.compilePDF
    compileReport(filename);
end
end

function value = latexEscape(value)
value = char(string(value));
value = strrep(value, '\\', '\\textbackslash{}');
value = strrep(value, '_', '\\_');
value = strrep(value, '%', '\\%');
value = strrep(value, '&', '\\&');
end

function compileReport(reportFile)
[outputDirectory, reportStem] = fileparts(reportFile);
command = sprintf(['pdflatex -interaction=nonstopmode -halt-on-error ' ...
    '-output-directory="%s" "%s"'], outputDirectory, reportFile);
[status, output] = system(command);
if status == 0
    [status, secondOutput] = system(command);
    output = [output newline secondOutput];
end
if status ~= 0
    error('writeFairComparisonReport:LaTeXFailed', ...
        'pdflatex failed:%s%s', newline, output);
end
for extension = ["aux", "log", "out", "toc"]
    temporaryFile = fullfile(outputDirectory, ...
        reportStem + "." + extension);
    if isfile(temporaryFile)
        delete(temporaryFile);
    end
end
end
